### ISSUE TITLE
Missing awakenings on some cards.

### ISSUE THREAD

**Issue by dashwolfpad** [madcowfred/padherder-issues#1000]
Awokens are missing from the following monsters:
2444 Hokuto Shinken's Successor, Kenshiro (stats buffed too)
2328 Misato&AAA Wunder, Main Battery Gunfire (stats buffed too)
3076 The Man who aimed to be the Ken-oh, Toki (stats buffed too)
2410 Moonlit Prowler, Vampire Lord
2411 Spirit of the Masquerade, Alraune

Possibly the whole set of the old xmas cards and old hokuto characters were forgotten when they were buffed on the collab rerun.  Could only attest for the above with my box.

**Comment by ryuujinzero** [comment]
Issue resolved.
