### ISSUE TITLE
Teams with G/D Osiris don't display

### ISSUE THREAD

**Issue by monger99** [madcowfred/padherder-issues#1004]
If I set the G/D Osiris from my box as a team lead/sub, the team will not display when I click on it (the team information is the previous team).

I can still edit/delete the team. Removing/readding Osiris does not fix this issue. A friend G/D Osiris does not trigger it. I believe that using the max stats button also does not change the team information (with another form of Osiris).

Could this be related to the 7C awakening? It doesn't display in my box or with a friend Osiris.

**Comment by ryuujinzero** [comment]
Yes, this is due to the 7c awakening.

**Comment by madcowfred** [comment]
This should be fixed now.
