### ISSUE TITLE
Missing Awoken Amon and Awoken Baal from evo lists of base forms

### ISSUE THREAD

**Issue by DreadPirateShawn** [madcowfred/padherder-issues#1009]
I have "King's Gaze Demon Lord, Baal" [2506] and "Resolved Demon Lord, Amon" [2504] in my monsters list, but neither of them includes the Awoken forms in their evo lists.

![missingawokenamon](https://cloud.githubusercontent.com/assets/1418951/25020443/3b645a14-2043-11e7-887f-a0b2f7389bdf.png)
![missingawokenbaal](https://cloud.githubusercontent.com/assets/1418951/25020444/3b673338-2043-11e7-9e1d-c1ebb0c8499f.png)

**Comment by ryuujinzero** [comment]
I fixed this issue last night. It's pending deploy.

**Comment by DreadPirateShawn** [comment]
@ryuujinzero Any update on when this might be deployed? (My apologies for pestering, just want to make sure this hasn't fallen off the radar.)

**Comment by ryuujinzero** [comment]
Fixed.
