### ISSUE TITLE
"Sets" Suggestions

### ISSUE THREAD

**Issue by Gannonball09** [madcowfred/padherder-issues#101]
Under the "Sets" tab, is it possible to have more than one ultimate evolution to show for the applicable monsters? like a slideshow? I know it's petty, just curious. Especially since multiple evolutions are starting to become available. Also, a suggestion to have the Demons and Knights listed under the sets tabs for those of us who collect them. Lol.

**Comment by madcowfred** [comment]
Demons and knights added, slideshow sort of thing is too much effort right now.
