### ISSUE TITLE
Wrong evo material in Reincarnated Loki chain

### ISSUE THREAD

**Issue by unsolicitedcrap** [madcowfred/padherder-issues#1010]
Evolving from card 377 Loki, the God of Guile to 3486 Reincarnated Loki goes through 2396 Awoken Loki, but the evo material being displayed is that of 656 Loki, the Finisher instead of Awoken Loki.

**Comment by wmedlar** [comment]
Can you post a screenshot?

**Comment by ryuujinzero** [comment]
This has also been fixed. It is pending deploy.

**Comment by unsolicitedcrap** [comment]
Still need a screenshot then?

**Comment by wmedlar** [comment]
I'm not totally sure this is the issue we worked on, so a screenshot would be great!

**Comment by unsolicitedcrap** [comment]
First, add Loki, the God of Guile and select to evolve to Reincarnated Loki

![loki1](https://cloud.githubusercontent.com/assets/6231629/25072322/053947d0-2299-11e7-9720-0c0d951bdc05.png)

Notice Loki the Finisher is displayed as the evolve path

![loki2](https://cloud.githubusercontent.com/assets/6231629/25072323/0b78cb20-2299-11e7-8f67-4fed664776be.png)

Notice Awoken Loki should be displayed instead

![loki3](https://cloud.githubusercontent.com/assets/6231629/25072324/0ec33004-2299-11e7-9263-d40688016fcc.png)

**Comment by ryuujinzero** [comment]
This is related to issue #961. It has already been fixed and is pending deploy. You can keep an eye on #961 for updates.
