### ISSUE TITLE
New Card Add Finds Wrong Card

### ISSUE THREAD

**Issue by unsolicitedcrap** [madcowfred/padherder-issues#1014]
Attempting to add the Voltron collab cards returns cards with IDs that should be above 10,000. For example, Card 2625 should be Sendak, but it finds Tomoyuki Ooshima instead. Tomoyuki Ooshima is card 12625.

http://www.puzzledragonx.com/en/monster.asp?n=2625
http://www.puzzledragonx.com/en/monster.asp?n=12625

**Comment by JHunz** [comment]
The actual IDs (in NA) of the Voltron collab cards are the same as the IDs (in Japan) of the Crows collab cards.  PDX's workaround has been to add 10,000 to the IDs of the Crows cards.  We'll have everything sorted out and matching up soon.

**Comment by unsolicitedcrap** [comment]
It looks like the ID workaround may be in place now, but the wrong image is being returned still.

**Comment by ryuujinzero** [comment]
Issue resolved.
