### ISSUE TITLE
2623 - Drazil Robeast - Wrong Icon

### ISSUE THREAD

**Issue by brainfailed** [madcowfred/padherder-issues#1016]
Icon for 2623 - Drazil Robeast is incorrect.

**Comment by ryuujinzero** [comment]
All of the icons for the Voltron collab are incorrect because they conflict with the Crows collab monsters. They share the same monster ID numbers, except Voltron is for NA and Crows is for JP. A fix for this should be rolled out shortly.

**Comment by brainfailed** [comment]
Thanks for the clarification and quick response.

BrainFailed

**Comment by ryuujinzero** [comment]
Issue resolved.
