### ISSUE TITLE
Monster list is not appearing

### ISSUE THREAD

**Issue by sickcat99** [madcowfred/padherder-issues#1018]
Load the site
select My Monsters

Nothing is appearing in the list anymore. For about 12 hours since this issue was logged.

Looks like it might be DAthena with the new physical killer latent breaking it.

**Comment by ryuujinzero** [comment]
Can you confirm what URL you're using, and also try it at http://www.padherder.com? Also, please try clearing your cache.

**Comment by sickcat99** [comment]
https://www.padherder.com/user/sickcat99/monsters/
The link I am using. Cache has been cleared.

**Comment by sickcat99** [comment]
<img width="1373" alt="screen shot 2017-05-10 at 20 39 54" src="https://cloud.githubusercontent.com/assets/7051547/25917757/131c21a2-35c1-11e7-8917-ee97d6786a2e.png">

**Comment by sickcat99** [comment]
That timer in the top right has been messed up in months too.

**Comment by sickcat99** [comment]
A friend said he was having this problem too. Start occurring at 22:45 gmt 09 May

**Comment by sickcat99** [comment]
It's only My Monsters tab that has nothing appearing. All other tabs are showing things.

**Comment by sickcat99** [comment]
Console error:
`padherder.min.74e952e0058c.js:33 Uncaught TypeError: Cannot read property 'get_sprite' of undefined
    at UserMonster.<anonymous> (padherder.min.74e952e0058c.js:33)
    at Object.main (padherder.min.74e952e0058c.js:31)
    at Object.r [as row] (libs.min.78037c253aad.js:4)
    at m (padherder.min.74e952e0058c.js:33)
    at Object.c (padherder.min.74e952e0058c.js:33)
    at Object.trigger (libs.min.78037c253aad.js:5)
    at Object.success (padherder.min.74e952e0058c.js:1)
    at l (libs.min.78037c253aad.js:2)
    at Object.fireWith [as resolveWith] (libs.min.78037c253aad.js:2)
    at i (libs.min.78037c253aad.js:3)`

**Comment by sickcat99** [comment]
Get this as well
`libs.min.78037c253aad.js:5 [EventDispatcher] trigger: no subscribers for event "Resize"`

**Comment by sickcat99** [comment]
Occurs on Chrome and Safari.

**Comment by Raijinili** [comment]
Five bucks says you:

1. use JSON upload.
2. won a new latent in last week's challenge dungeons.
3. gave one of your monsters a new latent 
4. just uploaded a JSON.

**Comment by sickcat99** [comment]
5 bucks says you are right.

**Comment by sickcat99** [comment]
So it is DAthena with Physical killer that has broken our padherders. My friend also has this so it makes sense.

**Comment by sickcat99** [comment]
Is there a way of deleting Athena to fix it? I can't see a way of removing it as I can't see the monster list.

**Comment by Raijinili** [comment]
Working on a workaround.

**Comment by wmedlar** [comment]
We haven't gotten support for the killer latents set up yet, but the JSON upload will still attempt to inject them. We'll see if we can get a bugfix out for you soon. In the meantime you'll have to manually remove DAthena from your JSON, then add her using PADherder's add monster interface.

You can identify DAthena in your JSON by looking in the `cards` array. DAthena's record should have her id (3193) in the second index. This array is in chronological order so look near the end. Remove her record and try re-uploading, should work after that!

**Comment by sickcat99** [comment]
I did that. :D It worked. So it is definitely Athena breaking it.

**Comment by wmedlar** [comment]
Awesome! I'll ping you back with any updates as we continue to work on this.

**Comment by madcowfred** [comment]
This is "fixed" for now, it will just not display killer latents so this stops happening until we fix it properly :\
