### ISSUE TITLE
Goddess Kush 804 is showing the wrong image

### ISSUE THREAD

**Issue by sickcat99** [madcowfred/padherder-issues#1019]
It is currently showing - Devoted Miko Goddess, Kushinadahime. I have just devolved it from 2280

**Comment by sickcat99** [comment]
<img width="977" alt="screen shot 2017-05-10 at 21 34 15" src="https://cloud.githubusercontent.com/assets/7051547/25920041/7a09c30e-35c8-11e7-9370-8b943b517d44.png">

**Comment by ryuujinzero** [comment]
I don't understand. 804 Goddess of the Rice Fields, Kushinadahime does have the correct image. The monster you have displayed there IS 1298 Devoted Miko Goddess, Kushinadahime, and that is her correct image. Am I missing something?

**Comment by sickcat99** [comment]
Have you tried the steps to reproduce? If not, try that and you will see the problem.
If you look at the picture on the right they are clearly not matching up.

**Comment by sickcat99** [comment]
804 shows 1298 instead.

**Comment by Raijinili** [comment]
As far as I can see, the images agree with PadGuide and PDX. The images in your screenshot are 1298, as they should be.

There's a wrong-evolution issue, though. Is that what you're seeing?

**Comment by ryuujinzero** [comment]
Unable to find any fault with 804 or 1298, though the incorrect evo issue is related to #961.
