### ISSUE TITLE
Timer in the corner are wrong

### ISSUE THREAD

**Issue by sickcat99** [madcowfred/padherder-issues#1020]
TAMADRA Infestation! in 594h 58m 
It always shows something like this.

I believe my settings are all correct:
<img width="533" alt="screen shot 2017-05-10 at 21 32 14" src="https://cloud.githubusercontent.com/assets/7051547/25919964/36b1c16a-35c8-11e7-9dac-9aa23c739894.png">

**Comment by sickcat99** [comment]
Not my friend ID. I edited it for this.

**Comment by Raijinili** [comment]
Dupe of #986.

(removed extra comment)

**Comment by sickcat99** [comment]
oh :P

**Comment by ryuujinzero** [comment]
Closing.
