### ISSUE TITLE
json is too large if you have 5000 monsters

### ISSUE THREAD

**Issue by minaheart** [madcowfred/padherder-issues#1035]
if you have 5000 monsters the json file is larger than the upload limit

**Comment by ryuujinzero** [comment]
The maximum box size in PAD is currently 4500. How do you have 5000 in your json? This is something that will need to be fixed for future proofing.

**Comment by JayHuang** [comment]
++ this issue. File limit is 200KB but my JSON is 211KB, there doesn't seem to be a way to upload in multiple parts, either.

**Comment by madcowfred** [comment]
Bumped the limit up to 1MB, that should last us until... I don't even know now, 25k box size?
