### ISSUE TITLE
Limit Breaking and Super Awakenings

### ISSUE THREAD

**Issue by Boxarin** [madcowfred/padherder-issues#1050]
Limit breaking needs to be added for:
- [] Healer girls
- [] REVO mystic knights
- [] Orpharion and Despharion
- [] Rouge Bosses
- [] Fagans
- [] Ana Valk
- [] Gran Reverse
- [] My
- [] Rikuu
- [] Jil Legato

- [] MP Dragons
- [] Attacker Odin Dragon
- [] Soprano
- [] Linka
- [] Ana Eldora

- [] Elementals
- [] Late bloomer dragons
- [] Riders
- [] PADZ Silvers
- [] Valkyries
- [] Legendary Heroes
- [] Reincarnated Evos
- [] UUVOs

- [] ECO super dumpty alma and tiny alma
- [] Amberjack
- [] Anne Punt
- [] GC Crab V3
- [] Gunma
- [] Mastering
- [] Arthur
- [] Pianist
- [] Udon
- [] Taiko God Don-chan
- [] Kenshin, Saiko, Hiiko
- [] Shishio
- [] FMA “Father”

- [] Halloween Sonia, Sonia Gran
- [] Halloween Kali, Xiang Mei
- [] Christmas Hera Ur, Sakuya, Kali, Sonia, Liu Bei, Gremory

https://www.reddit.com//r/PuzzleAndDragons/wiki/limitbreak

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Boxarin** [comment]
Possibly have a list of cards that can LB and give the option to level 101-> Limit Break, and once past “max” a super awakening drop down box opens

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ryuujinzero** [comment]
A little less of a headache: Introducing a `limitBreak` flag. 0 for no Limit Break and 1 for Limit Break. Monsters with `limitBreak=1` can scroll from 1 to Max (Max being 110). As the Super Awakenings will all be assigned a number (similar to the way Awakenings and Latents are), a `superAwoken` flag can also be incorporated for each monster that can Limit Break, and you can select one of the three from a dropdown.
