### ISSUE TITLE
Captcha Broken

### ISSUE THREAD

**Issue by aborders75** [madcowfred/padherder-issues#1054]
Captcha broken on the register screen.

https://www.padherder.com/auth/register/

**Comment by foad** [comment]
Any update on this? I feel like it's a pretty major issue to be left unfixed

**Comment by madcowfred** [comment]
This should be fixed now :( I've been super busy with life and apparently need to find some people able to fix things like this if I'm not available.

**Comment by aborders75** [comment]
There are a lot of people out there that love PADHerder and would be glad to help.  I would be happy to but I would not be able to commit a lot of time.  I know there have been several threads out there of people willing to help to get it back up to date.  :)  Let me know if I can help in any way.
