### ISSUE TITLE
UK/EU option in Account settings

### ISSUE THREAD

**Issue by omnibon** [madcowfred/padherder-issues#106]
My Account -> Settings -> PAD Account has the option for Country and Friend ID. Currently the drop down option for country only has America and Japan as options. An EU/UK option would be much appreciated.

**Comment by madcowfred** [comment]
Is there actually a separate game server/friends list for an EU version? That's all the Country identifier is there for.

**Comment by incrediblehulf** [comment]
Yes, there is an EU version and a KR version, too, though the Korean one has been around for much longer.

**Comment by madcowfred** [comment]
Added South Korea/European Union options.
