### ISSUE TITLE
DarkThing theme is broken

### ISSUE THREAD

**Issue by A-zu-ra** [madcowfred/padherder-issues#107]
This isn't directly related to PADHerder as a system, but the DarkThing theme does not display properly when it used to before. Formatting is completely absent and is more or less unusable.

**Comment by madcowfred** [comment]
Confirming that it's broken right now due to internal changes from upgrading to Bootstrap 3. I've disabled access to it until I can fix it, or find something better.

**Comment by Hansekins** [comment]
Nooo... I much prefer the dark theme - much easier on the eyes. Hope some kind of replacement can be found.

**Comment by madcowfred** [comment]
Fixed so people stop bugging me about it :scream:
