### ISSUE TITLE
Mouseover monster tooltips on "Sets" page

### ISSUE THREAD

**Issue by Hansekins** [madcowfred/padherder-issues#109]
I love the info tooltips that come up when mousing over monster images on the main page and sets page, but the ones in the top two rows on the sets page seem to get partially cut off. (presumably because they're to close to the top of the page?)

Using Chrome, in case that matters.

**Comment by madcowfred** [comment]
"Fixed" - tooltips should hopefully always be on screen now but the arrow tends to appear in strange places.
