### ISSUE TITLE
Add "Total Line" back into teams screen.

### ISSUE THREAD

**Issue by Dakiton** [madcowfred/padherder-issues#110]
It's helpful for seeing base health and team cost when future planning teams.  It might even be good to see damage based on color and such.  But health and cost is what I used teams for most.

**Comment by madcowfred** [comment]
It has been re-added in a ~fancy~ fashion.

**Comment by Dakiton** [comment]
What does NYI mean? Is it going to be in the patch notes?

On Tue, Dec 3, 2013 at 9:33 AM, Freddie notifications@github.com wrote:

> It has been re-added in a ~fancy~ fashion.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/madcowfred/padherder-issues/issues/110#issuecomment-29725476
> .

## 

```
Ian Harden
```
