### ISSUE TITLE
Credits Modal not working +minor

### ISSUE THREAD

**Issue by omnibon** [madcowfred/padherder-issues#114]
Credits button at footer no longer seems to be working.

Also minor 'error' thrown up by Chrome:
event.returnValue is deprecated. Please use the standard event.preventDefault() instead.
fixed with latest jquery beta 
http://code.jquery.com/jquery-1.11.0-beta2.js

**Comment by madcowfred** [comment]
Fixed the credits thing, will update to jQuery 1.11.0 once it is non-beta.
