### ISSUE TITLE
Adding a new monster results in undefined in Pendras column until refreshing the page.

### ISSUE THREAD

**Issue by jdkramar** [madcowfred/padherder-issues#115]
It looks like when using the Add Monster menu that once you add the monster to your list it doesn't quite know the number of Pendras needed, although it does know the amount of XP needed. Once you refresh the page though it knows the number of Pendras. 

![Screenshot](https://f.cloud.github.com/assets/6087742/1656310/272fcc94-5b71-11e3-9464-d5cc043bcd0a.jpg)

**Comment by madcowfred** [comment]
Fixed.
