### ISSUE TITLE
Rainbow Crystal in the Commonly used materials section

### ISSUE THREAD

**Issue by Fandelix** [madcowfred/padherder-issues#118]
IMO it should go in the Rarely used materials section because:
1. It's not used in 10 or more evolutions (8 according to PDX, 9 according to PAD Wikia)
2. It's a collab evo material (you can only get it when the collab rolls around, aka not often)
3. The rest of the FF collab crystals are in the Rarely used section
4. It's not available in US and EU (where I assume most Padherder users are)

**Comment by madcowfred** [comment]
1. Actually a different bug where it counts the Malboro King evolution as 5 evolutions, oops.
2. Way too much of a pain to deal with tracking.
3. Meh.
4. This sways me.

My Materials will now filter out JP-only materials for non-JP accounts.

**Comment by iscribble** [comment]
I just created a new (alternate) PADHerder account for my Japanese game and noticed that the Japanese-only materials are not listed. Furthermore, the next metal dragon dungeon is not listed (I know what it is from another application).

I double-checked that my account tab lists Japan as country, includes my ID, and Timezone is set to US/Pacific.

For reference, my username on the new account is iscribble2.
