### ISSUE TITLE
Preserve formatting (line breaks) in team description

### ISSUE THREAD

**Issue by iscribble** [madcowfred/padherder-issues#119]
The new team layout is great, thanks for that!

Could you please preserve line breaks in the team description textbox?

On Save:

> $(this).val().replace(/\r\n|\r|\n/g,"&lt;br /&gt;");

On Edit:

> descriptionText.replace(/&lt;br\s?\/?&gt;/g,"\n");

Thanks!

**Comment by madcowfred** [comment]
Oops, I forgot to fix this when changing things. Fixed now.
