### ISSUE TITLE
Up/Down arrows of team list lost w/ 11+ teams

### ISSUE THREAD

**Issue by iscribble** [madcowfred/padherder-issues#120]
The up/down arrows are not placed properly next to team title with 11 teams listed (Chrome).

**Comment by madcowfred** [comment]
My 12 teams display fine in Chrome/Windows, what OS are you using? Also could you provide a screenshot?

**Comment by iscribble** [comment]
Here you go! =)
http://i.imgur.com/8cUxGso.png

**Comment by madcowfred** [comment]
Looks like it breaks if the team name is a bit too long, how annoying.

**Comment by madcowfred** [comment]
Deployed a fix for this - long team names should now truncate with '...' instead of completely breaking the layout.
