### ISSUE TITLE
Table "wrapping" issues

### ISSUE THREAD

**Issue by magusonline** [madcowfred/padherder-issues#121]
If I don't maximize the window, the team windows and tables wrap around oddly. Is it possible to use fixed values, rather than relative?

http://i.imgur.com/8FjYFqd.png

http://i.imgur.com/uf8Kvd9.png

If I force the font size one notch smaller, it "fixes" it.

**Comment by madcowfred** [comment]
At default zoom the teams table should display fine down to around 1200px wide. Those images are 1258px wide but the zoom is definitely not default :-\ Can't really do much to fix this, the columns are already fixed width.
