### ISSUE TITLE
A new home for Dungeon Reminders?

### ISSUE THREAD

**Issue by incrediblehulf** [madcowfred/padherder-issues#122]
Would it be possible to move the Dungeon Reminders to the header as a dropdown like the metal/jewel schedule? It's a very useful feature but not something a user wants or needs to see 24/7 on every screen.

Maybe just removing it from My Sets/My Teams could work, too, as a quick fix.

**Comment by dr-ishmael** [comment]
An alternative would be to make it so we can close the reminder, and not have it appear again that day.  I like getting the reminder in the morning, but after I've farmed the dungeon a time or two to get the most critical materials that week, I don't need to see it anymore.

**Comment by Tygre** [comment]
I think its nice always being up there, I've got alot going on and its good to see it.  I can imagine those with multiple accounts would find it useful to see it all the time too.  But maybe an option in the account settings to set it for what ppl prefer?

BTW, AWESOME!!!! job on this site, I was just looking for a simple team builder to give me some ability to mock team setups for descends, this goes so far beyond that...its wonderful!

**Comment by madcowfred** [comment]
Implemented two different things for this:
- Reminder boxes are closable by pressing the 'x' looking thing in the top right of the box.
- Reminder boxes are closable for today in the **current browser** (it stores this in LocalStorage) by clicking the 'Hide for today' button.
