### ISSUE TITLE
Team total cost includes friend leader

### ISSUE THREAD

**Issue by dr-ishmael** [madcowfred/padherder-issues#123]
On the My Teams page, when viewing a team, the value calculated for Total Cost includes Leader, Sub 1-4, and Friend Leader.  I don't think the friend leader should be included, since the team cost limit only affects the choice of _your_ leader and subs; you can pick any friend leader you want regardless of your team cost limit.

**Comment by madcowfred** [comment]
Oops, fixed.

**Comment by dr-ishmael** [comment]
Awesome, thanks!
