### ISSUE TITLE
Request: Highlight max level monsters

### ISSUE THREAD

**Issue by dr-ishmael** [madcowfred/padherder-issues#124]
On the My Monsters page: The only special notation for a max-level monster is when the monster is _also_ the highest evolution, in which chase the "Priority" column is automatically changed to "MAX".  For non-max-evolution monsters, however, there is nothing to indicate visually that it is at max level.

I would suggest something similar to the "Skill" column.  Instead of showing "Max," however, I would keep the level number and just make it bold with a green background.

**Comment by madcowfred** [comment]
Seems reasonable enough, implemented.

**Comment by dr-ishmael** [comment]
That looks nice, thanks again!
