### ISSUE TITLE
Change from Current XP to Lv + exp until next?

### ISSUE THREAD

**Issue by nchen24** [madcowfred/padherder-issues#126]
Unless I'm just missing something, there isn't a way to view a monster's current total XP, so it seems to me like it would be more helpful to have the input be in current level + remaining until next.  Not really a big deal until 4M curve monsters are relatively high level, but I figured I'd mention it.

**Comment by dr-ishmael** [comment]
If you go to Power-Up Fusion and select the monster, it displays the Current EXP.
<img src="https://f.cloud.github.com/assets/1929447/1827649/d0178c62-723b-11e3-8db3-5d78cc2441a1.jpg" height=200 />

**Comment by madcowfred** [comment]
^ What that person said - if you're updating XP manually it's expected that you've just fusioned the monster and have access to the XP that way. If it's level 50/99 the difference between 50 and 50.9 is very very small compared to the several million XP you need anyway, just update level.
