### ISSUE TITLE
Allow dragging/dropping or key-control of team ordering

### ISSUE THREAD

**Issue by ryanscott** [madcowfred/padherder-issues#127]
hi,

love the new site!

It is extremely difficult, almost unusable, to sort teams...with the little up/down arrows to click on.  If we could have a keystroke to move up/down (or move to #), or the ability to drag/drop the teams, that would be amazing

**Comment by madcowfred** [comment]
Seems reasonable enough, you can now drag and drop teams to reorder them (though there's no real UI notification that you can do this).
