### ISSUE TITLE
New Ultimate Evolutions

### ISSUE THREAD

**Issue by bianbianchong** [madcowfred/padherder-issues#129]
Hi, I'm a Japanese version player, and there have been updates of some new ultimate evolutions since months ago, e.g. Awoken Hera, Demon Viper Orochi, Awoken Zeus etc. I noticed there are such records of these monsters in the system, but they didn't appear on the Evolution column of My Monsters. Could you fix these so I could monitor the evolutions materials more effectively? Thank you.

**Comment by madcowfred** [comment]
Fixed.
