### ISSUE TITLE
Max lvl bug in My Sets

### ISSUE THREAD

**Issue by incrediblehulf** [madcowfred/padherder-issues#132]
Some monsters (I only noticed Vamp and Gigas) are displaying 99 instead of the star and they're not counted as being max level in the heart icon tooltip.

**Comment by incrediblehulf** [comment]
Oh! It's happening to Yomi, too. It must be an issue caused by the new ults that were added.

**Comment by madcowfred** [comment]
Yup, the new JP evolutions highlighted a few bugs with the sets code. Should be fixed now.
