### ISSUE TITLE
Misc Dragons Suggestion

### ISSUE THREAD

**Issue by Gannonball09** [madcowfred/padherder-issues#133]
Since the release of Kouryu, I noticed there is no room for him in the "Misc Dragons" Set. Would it be possible (instead of Misc Dragons 2) to have a set called "Invade Dragons", "Copycat Dragons", or something for Green Skydragon Elysium, Chaos Blizzard Dragon, and Blue Flamedragon Muspelheim? This would leave Dragon Lord Zaerog, Sacred Flame Dragon, Formula and Kouryu the Star Emperor, Fagan in the "Misc Dragons" Set with room to add in each of them. Just a suggestion! :)

**Comment by madcowfred** [comment]
Seems reasonable, changed.
