### ISSUE TITLE
JP Account: No JP Materials and No Events

### ISSUE THREAD

**Issue by iscribble** [madcowfred/padherder-issues#134]
I recently created an alt account for the JP version of the game. Despite having entered all my info, I do not see upcoming events\* listed nor do I see the JP-only materials (such as crystals).

This is possibly related to (GH-118)

*It's possible there are no upcoming events today...

**Comment by madcowfred** [comment]
The materials part should be fixed, events will require some more extensive changes.

**Comment by madcowfred** [comment]
Events should also be fixed now.
