### ISSUE TITLE
Dungeon Reminder's remaining time is 1hr too early

### ISSUE THREAD

**Issue by heartsofruin** [madcowfred/padherder-issues#136]
The dungeon reminder's remaining time states the day's dungeon cuts off at 2:00am EDT but the schedule on padx goes by 2:59am EDT.

1:58am right now and special dungeon list in game shows 1hr to go for Wednesday dungeon, while herder is saying 2m left.

Didn't check other timezones, this was with both US/Eastern and America/New_York

**Comment by madcowfred** [comment]
Looks like this was a combination of things - foolishly hard-coded timezone calculations (UTC -7 forever) and PAD being broken as fuck with DST (my PAD says 1 hour less remaining than there really is). Should be fixed now.
