### ISSUE TITLE
Calculate Leader Skill boosts in My Teams? how about a My Friends? 

### ISSUE THREAD

**Issue by Tygre** [madcowfred/padherder-issues#138]
I was primarily looking for a team mock up site so I could see how my team might measure up against some descend dungeons, and stumbled onto this project.  What a wonderful and amazing tool!  Thanks so much for your hard work!!!!

I was hoping I might find something that would calculate what my friends leader skills would do for my hp/atk/rcv, thats one thing I noticed this doesn't do.  The link to the PDX simulator does it I guess, but it would be nice to have it local here.  PDX is such an ugly, hard to wade through site....:-P  (pad.wikia is almost as well organized as your site!)

Also, I'm kinda a noob, and my friends are all noobs too, it would be awesome to be able to type in stats for their leaders too, instead of it assuming that they are all max lvl +0 no awoken....

Something i've been wanting in the game itself is a way to track which friend has what leaders, something to organize that here, and a way to link with friends here who have a PADherder acct would be cool too! (just look at me heap the work on you, lolz) 

 I'm not a programmer, or I'd offer to help.  This site is exactly what I was looking for!  I'm thinking of messenging all my friends ingame and pointing them to PADherder!

**Comment by Tygre** [comment]
OK, I'm blind.  I see that you are planning on implementing the effect of leader skill bonuses, but haven't yet.  Sorry!

I still would love a My Friends section, and maybe a My Leaders section to go with it, so we can friend our friends here and see their leaders and lineups!

**Comment by madcowfred** [comment]
I get asked all the time for the friend stuff, it's coming.

re:teams, I'd definitely like to be able to add a specific friend leader instead of a generic monster but there's some internal changes that need to be made first.
