### ISSUE TITLE
Multiple things

### ISSUE THREAD

**Issue by w1drose** [madcowfred/padherder-issues#139]
Small details: 
1. All my Legendary Dragons are max awoken, yet the color on "My Sets" doesn't appear. Perhaps this is because one of my dragons are not yet ultimate evo'ed yet? (Valhalla)
2. Holiday Dragons (Rouges) come max skilled, but the color on "My Sets" doesn't appear. 
3. Add Top Droidragon to Misc. Dragons? 
4. Using PADHerder on Mobile is pretty tough, the banner at the top blocks half the screen. I know herder isn't designed for mobile, so it's understandable, but before it was changed, it worked great on mobile. 

---

Suggestions: 
1. Perhaps it might be easier to do a +Pengdra, or +Super King, option so that I don't have to recalculate how much EXP i need. Simply when I feed a monster a King, I can just press "Add On-Color King" and boom, my exp/levels are adjusted. 
2. This may be too advanced? (Sorry I'm not a computer guy) But could you guys do something like PADx where everyone's accounts can be saved onto a server as some sort of friend finder? So if I need a Neptune, I can search up people with Neptune in their friend finder? 

Or maybe, something like having us put our ID, and making a list of our "friends ID" so we can check what monsters a friend has?

**Comment by madcowfred** [comment]
Multiple things in a single ticket is annoying, ugh.

Small stuff:
1. Fixed.
2. Fixed.
3. Added.
4. Not sure what you mean by 'the banner' - the nav bar with 'PADHerder   News' etc? The floating table header thing?

Suggestions:
1. Unlikely given how much space the horrible table takes up already. When you power up a monster the right side of the monster thing says "Current EXP:     1234", I just assume people use that to update the XP field (which is definitely current XP when editing).
2. Yes I know people want this, ugh.

**Comment by w1drose** [comment]
Sorry! I never use this system so I didn't know it would be annoying :(

Thanks for fixing :)
