### ISSUE TITLE
Enhance Materials cannot be added to teams

### ISSUE THREAD

**Issue by xialiu** [madcowfred/padherder-issues#14]
Most notably, Rainbow keepers are used enough that they should be there.

**Comment by madcowfred** [comment]
Add them to your monster list and you can. This is quite unlikely to change due to internal, er, let's call them 'decisions'.

**Comment by xialiu** [comment]
HA.  That was dumb.  Kept trying to look up "rainbow keeper" and got nothing.  My bad about the spam :P.
