### ISSUE TITLE
Batman REM/collab monster id's changed on pdx

### ISSUE THREAD

**Issue by Kelbesq** [madcowfred/padherder-issues#140]
Current links in padherder link to the old IDs.  As example:
BAO Batman + Batarang links to 932, which is now BAO Deathstroke.   This particular batman got moved to 9320.

I believe all of the old batcha monsters got a 0 added to make room.   The new batman collab monsters are US only as far as I know, and there may be some issues with the numbering between US and Japan.

**Comment by nevets1219** [comment]
Another example: BAO Joker+A. Blossom currently points to BAO Firefly + Flamethrower (925) but should point to 9250.

**Comment by madcowfred** [comment]
Fixed the links, IDs will still be weird when adding thanks to GungHo being silly.
