### ISSUE TITLE
New Ultimate Evolutions

### ISSUE THREAD

**Issue by Gannonball09** [madcowfred/padherder-issues#141]
1) Ra/Isis/Horus/Angel/etc Ultimate Evolutions not present.

2)Water/Water Leviathan, Wood/Wood Fafnir, Wood Fire Graviton, etc not attached to their previous evolutions.

**Comment by madcowfred** [comment]
1. And they won't be until they're in the data files, random things announced on twitter can change a lot before they go love.
2. Fixed.
