### ISSUE TITLE
Navigation in Dolphin on Android

### ISSUE THREAD

**Issue by ghost** [madcowfred/padherder-issues#142]
When visiting the site using Dolphin (10.2.2 and previous versions running on Android 4.1.2) on my cellphone the full navbar is showing rather than the collapse toggle button. This wouldn't be a significant issue except that, whenever I zoom in to edit a text field, the un-collapsed navbar takes up half of the screen.
![screenshot_2014-01-01-08-52-35](https://f.cloud.github.com/assets/6297367/1829678/4f981310-72ed-11e3-897a-87bc75441f5f.png)

I checked a couple of other pages using bootstrap to make sure it wasn't an issue with bootstrap in general, but the collapse is working fine elsewhere.

**Comment by tvolpe2000** [comment]
This is also what the page looks like in Chrome on a phone/tablet when you zoom in.

**Comment by madcowfred** [comment]
Ah, this helped track down the issue. Fixed.
