### ISSUE TITLE
My Materials: excess materials

### ISSUE THREAD

**Issue by laurent** [madcowfred/padherder-issues#145]
Managing space in my monster box is a big issue for me. I'd love to be able to see a list of materials that I can sell to free up space.

I imagine it looking like the daily dungeon reminder bar in the monsters section. but it would list the materials that I don't need.

I think I'd classify "don't need" as any materials that I have in excess of whats needed for my high / medium / low priority monsters.

PS. Love the site, many thanks for developing it :)

**Comment by iscribble** [comment]
I second this enhancement request!

**Comment by scribblespad** [comment]
The feature is sort of there - when you go to the "My Materials" section, anything that is greyed out means that you don't need it for any of your current monsters.  But that doesn't solve the second part of the equation, which is if you have excess of what you actually do need (unless you are willing to do some quick math).

**Comment by SingedKitty** [comment]
If you do this, please make it subtle (maybe bottom of mats page?) or give us the ability to turn it on and off. Don't need a huge reminder every Friday that I have 50 excess Dragon Plants from Thursday farming. :)

**Comment by iscribble** [comment]
If you create a bookmark with the following script as the URL and then click that bookmark while on the materials page, you'll get approximately the desired results.

javascript:(function(){$(".material-box").each(function(e){var t={need:0},n=$(this);t.have=Number(n.find(":input").val());n.find("td").each(function(e){if(e%2===1){t.need+=Number(this.innerHTML)}});if(t.need<t.have){n.css("background","orange")}})})()

**Comment by madcowfred** [comment]
Added.
