### ISSUE TITLE
Missing monsters/duplicate numbers for Batman Collab 

### ISSUE THREAD

**Issue by scribblespad** [madcowfred/padherder-issues#146]
The monster drop-down box doesn't seem to have entries for some of the lower-level monsters that drop from the Batman Collab.  Some of the monster numbers seem off as well - for example, BAO Solomon Grundy is No. 926, but that number appears to be duplicated with BAO Catwoman (Although the wikia seems to denote BAO solomon grundy as no. 1926, see http://pad.wikia.com/wiki/BAO_Solomon_Grundy)

**Comment by scribblespad** [comment]
Oops, this looks like a dupe of an open ticket ((#140) already.  Closing this one.

**Comment by madcowfred** [comment]
Fixed the missing monsters part.
