### ISSUE TITLE
Request: Linking inside the team description box

### ISSUE THREAD

**Issue by Tygre** [madcowfred/padherder-issues#149]
I use the team description box to save research on team builds and I'd like to be able to make the links I put there into actual links so I can just click them to go back. 

 I tried to hard code one using  a href="etc  but ended up breaking the buttons below the team to edit and delete.  It made those buttons into the link I was trying to do and now I can't get back in to fix it, lol

**Comment by madcowfred** [comment]
I've just changed some things to strip HTML from user-editable things, that shouldn't ever have been allowed. I can see about adding a basic [url] tag in the future to link specific whitelisted URLs (youtube, puzzledragonforum, puzzledragonx, pad wiki?).

**Comment by Tygre** [comment]
Hmm, maybe it hasn't updated it yet, the buttons for that team are still broken.  I'm sure I was a nub about it and screwed something up, lol.  And yes, a basic [url] tag would be nice, but i'm not sure about the whitelisting.  Lots of ppl have blogs and such not on the common sites...idk, I'm certainly willing to defer to your judgement!

**Comment by Tygre** [comment]
Yay, it went through and that team is back to normal...thanks!  lol

**Comment by madcowfred** [comment]
The whitelisting thing is one way to deal with possible malicious links, I don't really want PADherder to be a vector for infection. I could also do something similar to what many wikis do - pop up a DANGER you are visiting an external site are you sure DANGER thing, idk.

**Comment by Tygre** [comment]
I totally get that, I wouldn't want it to be possible to link to malicious or unsavory stuff either!  A whitelist of all the common sites sounds great, and we can use this venue to ask you to add others we find along the way :)

**Comment by madcowfred** [comment]
A list of common sites would probably be useful, I can only think of: puzzledragonx, pad wiki, puzzleanddragonsforum, reddit. Are there any more to go in the first batch?

**Comment by Tygre** [comment]
Youtube for vids.  I have a link in my favs for ggftw.com too

**Comment by madcowfred** [comment]
Added this with a basic whitelist: padherder, youtube, pdx, wiki, padforum.
