### ISSUE TITLE
CoC Barbarian evo mats wrong

### ISSUE THREAD

**Issue by pfayze** [madcowfred/padherder-issues#15]
PADHerder and http://www.puzzledragonx.com/en/monster.asp?n=720 incorrectly report Yellow Evolve Mask (164) as an evo material for CoC Barbarian. http://pad.wikia.com/wiki/CoC_Barbarian correctly describes it, with Golden Demon Mask (169) instead.

![image](https://f.cloud.github.com/assets/4940277/791746/f64c1af6-eb4f-11e2-9702-296b26527a1e.png)

**Comment by madcowfred** [comment]
Fixed, should be fixed on PDX soon (if not already). You probably need to re-add any CoC Barbarians you had though, oops.
