### ISSUE TITLE
Team tables not showing well on mobile

### ISSUE THREAD

**Issue by Tygre** [madcowfred/padherder-issues#150]
I use Opera cause its the only browser that seems to be able to handle the picture overload of PaD sites, and the tables in the team section dont draw right.  I use the desktop setting instead of mobile and it still doesn't draw the tables like they are on my comp, though other sites do fine.

**Comment by madcowfred** [comment]
Could you post a screenshot?

**Comment by Tygre** [comment]
![screenshot_2014-01-07-00-42-57](https://f.cloud.github.com/assets/6262708/1857055/25e7ff66-7767-11e3-88ef-603976758056.png)

sure, here you go

**Comment by Tygre** [comment]
Heres one from the wikia thats properly formatted in the same browser:
![screenshot_2014-01-07-00-46-30](https://f.cloud.github.com/assets/6262708/1857072/9468355a-7767-11e3-9856-b4d96e2430f1.png)

**Comment by Tygre** [comment]
The table in the account linking section is doing the same thing

**Comment by Tygre** [comment]
The add monster and edit team screens are practically unusable too, I'm guessing the same issue
![screenshot_2014-01-09-01-40-00](https://f.cloud.github.com/assets/6262708/1875826/87d3c732-7901-11e3-9228-ee4356ed21f1.png)
![screenshot_2014-01-09-01-40-26](https://f.cloud.github.com/assets/6262708/1875828/978a4638-7901-11e3-8ef8-ef9f937ff21f.png)

**Comment by Tygre** [comment]
Both above screenshots are at max zoom out. It's not much better in landscape mode, which I hate cause the keyboard covers the whole screen.  I'm guessing the issue has something to do with dynamic sizing?  I'd really prefer to just scroll the screen around to see what I need than have it resized to un-usability.   I'd really like to be able to keep my box updated and work on my teams from my mobile for when I'm not around my comp =/

**Comment by madcowfred** [comment]
Hrm. At this point it's probably easier to just work on a mobile version of the site, it's really not working trying to support both. This mostly just means making some new templates that work better in a limited environment - browse monsters by icon, click team list to go to team display, idk what else. I shall add it to The List(tm).

**Comment by Tygre** [comment]
Hahaha, The List(tm)!  But I'm not using the mobile client, I set it to the desktop client and its doing it in there.  I'd rather scroll around in desktop mode where things usually display like they do on my...you know...desktop (though in my case its a laptop, xD)  I'm fairly sure the issue is with the dynamic resizing.  When I reduce my desktop browser to its smallest size, the tables go kinda wonky too.  Isn't there a way you can set a minimum size limit to the page width?  I seem to remember being able to do that in html, but I know even less css than I do html.  I'd really love to be able to use the site on my mobile, cause I'm not always sitting at my comp when I'm playing a mobile game, lol

**Comment by madcowfred** [comment]
See GH-184.
