### ISSUE TITLE
Example CSS to add +egg numbers to monster thumbnails

### ISSUE THREAD

**Issue by davethegr8** [madcowfred/padherder-issues#152]
I noticed that the thumbnails on the monsters don't include the total +egg numbers, so I prototyped it out. It's not perfect and the colors might need some tweaking, but this is the thumbnail link with some new css.

```
<a href="" style="position: relative; display: block;">
    <img src="221.cd3df10a06d7.png" style="display: block;">
    <span style="position: absolute; top: 0px; right: 0px; color: yellow; font-weight: bold; letter-spacing: -1px; text-shadow: 1px 1px 0px black;">+22</span>
</a>
```

It ends up looking like this:

![screen shot 2014-01-06 at 4 57 48 pm](https://f.cloud.github.com/assets/55392/1855691/dad88bb0-7736-11e3-9e1e-2fdce32f7d94.png)

**Comment by madcowfred** [comment]
It's not hard to do, I'm just wondering why I would want to add this. The UI is already rather busy, adding extra duplicated information isn't going to help things (and more DOM elements also increases rendering time).

**Comment by davethegr8** [comment]
_shrug_ don't know. I was using the app, noticed that +'s weren't showing and it confused me since I'm so used to them. heh. Then I thought, "oh, that shouldn't be too hard" and I did it because I wanted to see how I would do it. And then I thought maybe you'd want to see it in case you hadn't planned on adding that or hadn't got around to it or whatever. Feel free to close this issue, I just wanted to share in case it was helpful. :) I really dig your app and didn't want to be a total tourist.

**Comment by madcowfred** [comment]
There's another issue (GH-105) about inconsistent monster icon display - I may make the Monsters list display total +eggs as part of that in future. Thanks for contributing, it's just a constant struggle to deal with displaying data in a reasonable way :)

**Comment by madcowfred** [comment]
Added this.
