### ISSUE TITLE
Request: Custom groups/priorities

### ISSUE THREAD

**Issue by Tygre** [madcowfred/padherder-issues#153]
Is it maybe possible to have user defined priority groups?  It could be a setting in Account like the linking thing, where you set up priorities and rank them (like the teams are), and select whether they show in Sets or not.  When you start your account it could have the default priorities, but be fully customizable. That might solve alot of the priority issues I'm reading about here. I have alot of stuff going on in my monster box and I'm finding the default priorities a bit limiting...

Also groups/priorities for teams would be awesome instead of just a big list, I use teams to organize alot of stuff and its getting a bit cluttered there xD, and that would allow those who want to experiment on their main account a place to put those teams.

**Comment by madcowfred** [comment]
Going to go with "no" on this one for now, it's a lot of effort for what seems like a niche use case.
