### ISSUE TITLE
Open at puzzledragonx missing id

### ISSUE THREAD

**Issue by jrobber** [madcowfred/padherder-issues#154]
When clicking on any monster icon to open a monster at puzzledragonx.com the id has been lost and now every monster reads as undefined.

IE - Should be : www.puzzledragonx.com/en/monster.asp?n=71
ID Is: www.puzzledragonx.com/en/monster.asp?n=undefined

**Comment by madcowfred** [comment]
Fixed a few minutes ago, reload the page.

**Comment by jrobber** [comment]
You are fast!
