### ISSUE TITLE
"PDX Simulator" button using wrong #id's for Batman collab monsters.

### ISSUE THREAD

**Issue by Kelbesq** [madcowfred/padherder-issues#155]
Follow up to issue #140:   All of the normal links were fixed when clicking on a monster directly, but the "PDX Simulator" button on the "My Teams" page is still using the old links.

I deleted some of my old teams and made a few new ones to test it out just to make sure it was wasn't something being cached.  I also logged out etc.

**Comment by madcowfred** [comment]
Fixed.

**Comment by Kelbesq** [comment]
The dungeon drops now work (bane, copperhead, etc) but the Bat REM monsters have an extra twos zero added.  (i.e  BAO Batman+Batarang should be 9320 but the link is using 932000).  This applies to the normal links as well as the PDX Simulator.

Look at this team as an example:
http://www.padherder.com/user/Kelbesq/teams/#13234

**Comment by madcowfred** [comment]
Yeahhhhh really fixed now, don't ask :dog:

**Comment by Kelbesq** [comment]
Wow that was fast =).  Thanks!
