### ISSUE TITLE
Suggestion: browser tab names

### ISSUE THREAD

**Issue by Tygre** [madcowfred/padherder-issues#157]
Have the page name on the browser tabs be the Acct name instead of Padherder, will make it easier to distinguish what account you're looking at if you have friends you're looking at as well as your own account/s.  So it would say Verity: My Monsters instead of PADherder: My Monsters on the browser tab.

**Comment by madcowfred** [comment]
Implemented this, page titles are now "My Monsters | PADherder" or "freddie - Monsters | PADherder".
