### ISSUE TITLE
Bug: Team reordering

### ISSUE THREAD

**Issue by Tygre** [madcowfred/padherder-issues#158]
drag and drop to reorder teams doesn't seem to be working anymore

**Comment by madcowfred** [comment]
Definitely working here in both Firefox and Chrome for me. Browser/OS?

**Comment by Tygre** [comment]
windows 7 64 bit and firefox.  And idk, it worked for a few days and then stopped.  Aaaaand, now its working again, lol.  Go figure, gotta love those TiP errors =P
