### ISSUE TITLE
Suggestion: Monster number in popups

### ISSUE THREAD

**Issue by Tygre** [madcowfred/padherder-issues#159]
Except when adding a monster, I can't find anywhere their number is displayed, would be nice to have it as part of the popup description in the box and sets

PS, if you want me to stop spamming suggestions, just let me know!  xD

**Comment by madcowfred** [comment]
I think it was originally in the monster popover titlebar, then got removed because of width concerns... then the popover got made wider without re-adding it. Oops. Added again.
