### ISSUE TITLE
Bug: Mobile minibar issue

### ISSUE THREAD

**Issue by Tygre** [madcowfred/padherder-issues#161]
The minibar on my mobile doesn't show the option to switch accounts or even log out. Tried to attach screen shot from phone, dunno if it will work :) 
![screenshot_2014-01-09-00-55-37](https://f.cloud.github.com/assets/6262708/1875794/8cdfdf28-7900-11e3-816b-aeb775e88f14.png)

**Comment by Tygre** [comment]
Oops had my night time dimmer on, hope you can see it Ok!

**Comment by madcowfred** [comment]
It looks like it has a wee scrollbar on the side, is it possible to scroll down? It does that on the desktop version also if you make the window small enough.

**Comment by Tygre** [comment]
Ahh, yes. I can scroll down.  I wasnt expecting that cause it is a drop down arrow and it used to drop down and give me the options without scrolling :)  Thanks again!
