### ISSUE TITLE
Bug: Dungeon reminder not showing for European player

### ISSUE THREAD

**Issue by laurent** [madcowfred/padherder-issues#164]
When I set my country to European Union in the My Account section the Dungeon reminder bar no longer displays.

Thanks.
L

**Comment by madcowfred** [comment]
Ah, I need to know what timezone the PAD 'day' is based on for the EU version (US = PST, JP = Tokyo obviously).

**Comment by laurent** [comment]
EU version uses UTC

Many thanks :)

**Comment by madcowfred** [comment]
Cool, added.
