### ISSUE TITLE
Suggestion: Friend Finder text clarification

### ISSUE THREAD

**Issue by nevets1219** [madcowfred/padherder-issues#166]
On the "Friend Finder" page, we have the "Search All" checkbox which states "Search all monsters instead of just favourite team leaders?". However, I don't see where to set favorites so I'm assuming it means the favorites in "My Team", if so can the wording be clarified.

**Comment by madcowfred** [comment]
PADherder has some issues with UI discoverability. It was intended that you set favourites by clicking the little star next to the up/down arrows, unfortunately nobody notices them. I've added a simple 'Favourite' checkbox to the add/edit team form.
