### ISSUE TITLE
Private profile in Friend Finder leads to 404

### ISSUE THREAD

**Issue by nevets1219** [madcowfred/padherder-issues#167]
1. Perform a search for 643 (e.g. http://www.padherder.com/find_friends/?monster_id=643&min_awakening=0&min_skill=1&search_all=on)
2. Look at the entry for user "maleran" and click his name
3. Get a 404 (e.g. http://www.padherder.com/user/maleran/)

I'm guessing it's because of private profiles?

**Comment by nevets1219** [comment]
Further confirmed by making my profile private and viewing it while logged out. I get the 404.

**Comment by madcowfred** [comment]
Oops. Fixed.
