### ISSUE TITLE
Suggestion: Friend searching by ID?

### ISSUE THREAD

**Issue by sunglassesmichael** [madcowfred/padherder-issues#169]
Could you add searching by ID so that we can see if our current friends have PADherder accounts?

**Comment by sunglassesmichael** [comment]
By the way, this tool is so awesome and getting more awesome all the time! 100,000 thanks!

**Comment by w1drose** [comment]
This is our next request that we will bug you with :)

Again, thank you so much for doing this freddie!!

**Comment by mezmerie** [comment]
I would like to second the motion!

**Comment by madcowfred** [comment]
Added.
