### ISSUE TITLE
Satan's Need XP is 0 at level 1 and negative at higher levels

### ISSUE THREAD

**Issue by pratch** [madcowfred/padherder-issues#170]
![satan](https://f.cloud.github.com/assets/3832597/1897111/8fe249ee-7bcc-11e3-8561-17ac2426c3fe.png)

**Comment by madcowfred** [comment]
Ah, this would be because of some other bugs I introduced in the 'Add monster' form. Your "Target" column is set to 1 so it is using level 1 XP as the max XP. I've manually fixed the broken Satans, any other monsters added since yesterday are probably screwy also.
