### ISSUE TITLE
BUG? Teams won't stay in order (-edit: when using arrows)

### ISSUE THREAD

**Issue by mezmerie** [madcowfred/padherder-issues#171]
Pretty much this. I use the up/down arrows to arrange my teams, but when I return to the screen later, the arrangement didn't stick. I use Firefox, if that matters at all. Thank you for all your hard work!

**Comment by mezmerie** [comment]
Oh, but I just noticed if you use the drag and drop ordering method it DOES work. (Although last night, weirdly, it wouldn't let me drag any team higher, only lower, so I was using the arrows instead.)

**Comment by madcowfred** [comment]
Should be fixed.
