### ISSUE TITLE
BUG?  "Done Position" option in My Account section not working?

### ISSUE THREAD

**Issue by mezmerie** [madcowfred/padherder-issues#172]
I like my Maxed monsters to appear at the top when my profile is viewed by another person (like they used to be). I assume that's what the new "Done Position" option is for? Anyway, it doesn't appear to be working at the moment. Thanks!

**Comment by madcowfred** [comment]
"Done position" is meant to control where you see the 'Done' monsters, not what anyone else sees. Not sure about forcing other people to view them how you like to view them.
