### ISSUE TITLE
My Materials page inaccurate

### ISSUE THREAD

**Issue by bob-asaur** [madcowfred/padherder-issues#173]
Logged on today and saw that the My Materials page showing multiple errors. It looks like it's only taking into account a few monsters from the other page when populating what materials are needed.

**Comment by madcowfred** [comment]
Can you reload the page and see if it's better? I have been breaking javascript all day.

**Comment by bob-asaur** [comment]
Tried multiple things. Cleared cache, reloaded page, relogged, etc. Still same issue. The only pattern I notice with which materials is showing up is that it's either an ultimate evolution or regular evolution to a dual colored monster or a dual colored monster evolving.

**Comment by theinfra** [comment]
Having problems also, I got a Yomi that's supposed to be missing 2x Mythlits but they rent't showimg up as needed in the Materials section

**Comment by madcowfred** [comment]
Should be fixed now, stupid complicated evolution code.

**Comment by bob-asaur** [comment]
Yup just checked. Looks correct now. Thanks a lot for providing this service. It's very useful. Have you considered putting a donate link? Paypal/Bitcoin/Litecoin/Dogecoin
