### ISSUE TITLE
Possible caching issue

### ISSUE THREAD

**Issue by wparks** [madcowfred/padherder-issues#175]
It seems there might be issues with caching (local storage?) related to the latest release.
- When I add monsters via bulk add, they don't show up in the view, but they do with individual add.
- When logging in one account, then logging out, then logging in with another account, the previous account's information is displayed.
- Today a new issue arises when logging into my account, the "Loading monsters..." text continues to display and doesn't load my monsters.  (likewise with "Loading materials..."

**Comment by madcowfred** [comment]
- See GH-174
- Should be fixed now.
- No idea, load the JS console (ctrl-shift-J in Firefox/Chrome) and see if any errors popped up?

**Comment by wparks** [comment]
- I reloaded and it didn't seem to load in my case. I'll check when I can get in again.
- Cool Thanks.
- Chrome JS Console:
  Uncaught TypeError: Cannot read property 'name' of undefined padherder.min.55ca95e106d1.js:6
  Resource interpreted as Font but transferred with MIME type text/plain: "chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/fonts/GothamSSm-Medium.otf". filing_tools.html:1
  Resource interpreted as Font but transferred with MIME type text/plain: "chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/fonts/GothamSSm-Bold.otf". email_sharing.html:1
  Resource interpreted as Font but transferred with MIME type text/plain: "chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/fonts/GothamSSm-Book.otf". global_tools.html:1
  event.returnValue is deprecated. Please use the standard event.preventDefault() instead. jquery-1.8.0.min.js:2

**Comment by madcowfred** [comment]
It will show up after ~5 mins or so. What's your username so I can look into the other issue?

**Comment by wparks** [comment]
Cool, I'll check it out. Thanks! My two accounts are: YamoskraP and YamoskraP_JP

**Comment by heartsofruin** [comment]
Not sure if related, I'm getting undefined name property JS errors too, monsters and materials wont load (username swansong). Same result if I have chrome do an empty cache and hard reload 

Uncaught TypeError: Cannot read property 'name' of undefined padherder.min.ab7da1e6a277.js:6
_box padherder.min.ab7da1e6a277.js:6
PADherder.reminders.check padherder.min.ab7da1e6a277.js:6
common padherder.min.ab7da1e6a277.js:1

**Comment by madcowfred** [comment]
Yup, probably same issue. I have borrowed wparks' account temporarily to debug :space_invader:

**Comment by madcowfred** [comment]
Bug found, fixed, deployed. Closing this bug to leave 174 for the bulk add monsters issue.
