### ISSUE TITLE
Bug: Monster Card Mouseover Persists

### ISSUE THREAD

**Issue by wpnewborn** [madcowfred/padherder-issues#176]
If you double click on a field to edit it and then mouseover the thumbnail the monster card info will appear.  If you press enter to confirm the edit while the card info is up the monster card will stay up and can't be closed.  This obscures the monster info and you have to refresh the page to clear it.

**Comment by nevets1219** [comment]
Just confirming I can reproduce this in Cyberfox 25 (Firefox).

**Comment by madcowfred** [comment]
Should be fixed now.
