### ISSUE TITLE
Materials page calculating off of final evolutions rather than evolutions I selected

### ISSUE THREAD

**Issue by xtop** [madcowfred/padherder-issues#178]
For example, I am leveling 3 Verche to get to Verche, Knight of the Sky in order to use them for awakenings.  I don't plan on giving them a ultimate evolution and have marked them on the Monsters page as evolving them just to the V, KotS level.  However, on the Materials page, my # of light keepers needed shows 1 for KotS evolution and 1 for the ultimate evolution.

It would be nice if the Materials page took into account the evolution I have selected, rather than assuming I want to do an ultimate evolution on each monster, but perhaps people prefer the current calculation method in the case where they aren't aware that a new ultimate evolution is available.

**Comment by TyrAlduin** [comment]
Then set the final evo of your feeder verche to none?

Eidit 1.
Oh wait are u saying you set it to none and it still says you need materials?

Edit 2
Cause if I set my 2nd vamp to none it no longer says I need materials for it....

**Comment by xtop** [comment]
No.  Here's how I have them set.  All 3 are set to V, KotS:

![verche1](https://f.cloud.github.com/assets/4333274/1916991/3af0c3f4-7d87-11e3-8eee-ae30d39d08a2.jpg)

I still need the materials to evolve them to KotS.  However, if I look at the materials calculation, I get this:

![verche2](https://f.cloud.github.com/assets/4333274/1917022/e77af34c-7d87-11e3-930e-2da657b34416.jpg)

See how it includes the materials for evolving them to GKotSV?  If I have the evolution level set below that, I don't want the calculations to include the materials for a higher level.  The items crossed out shouldn't be included.

**Comment by TyrAlduin** [comment]
You are correct Sir! This is indeed in need of fixing!
(just tried it again and I see it on Materials page)

**Comment by madcowfred** [comment]
This should be fixed now.

**Comment by xtop** [comment]
Nailed it - thank you very much.
