### ISSUE TITLE
Evo mats not counted in Evo column

### ISSUE THREAD

**Issue by deucester** [madcowfred/padherder-issues#179]
I have the evo materials in my monster box but in the evo column there's a red x on the material and when I mouse over the icon, it says 0x of the material.
![bug](https://f.cloud.github.com/assets/6406885/1918090/b8cbab56-7db2-11e3-9640-ec0036be3122.jpg)

**Comment by Tygre** [comment]
Lots of evo materials are useful as team members.  You have to add the materials you want to use for evo to your materials box, not your monster box

**Comment by deucester** [comment]
No, you don't get what I'm saying.  Look at my screen shot above.  I have one Keeper of the dark in my monster box on the left.  If you look at Hera and the evo mats for her, where my mouse pointer is, it should say that I have 1 keeper instead of 0x.

**Comment by madcowfred** [comment]
Don't add evo materials to your monster box, they go in My Materials.

**Comment by deucester** [comment]
Oh, sorry got it!  New to this.
