### ISSUE TITLE
Mobile site: broken layout 

### ISSUE THREAD

**Issue by Lutha** [madcowfred/padherder-issues#183]
There are some weird layout behaviors when I try and use the site on my phone. I'm using a Nexus 4 with its latest Android and Chrome (v4.4.2 and v32.0.1700.99). I've uploaded some images to show this off, but they are in reverse order and I can't figure out how to reorder them on my phone, so follow along beginning at the bottom image going up:

http://imgur.com/a/1je2a

The first image shows the login screen. This one is pretty self-explanatory.

The next 3 images show the column header on the monster page not being locked in place to stay aligned with the columns it is trying to explain. The first image shows the page as Chrome loads it fresh. The second image shows how it looks when I scroll down (this appears to still be correct). The third image shows the bug, where, if I scroll to the right from where I was in the second image, the column headers no longer stay aligned with the columns.

The last three images show how the nav bar at the top of the page acts strangely as I zoom in on the page. The first image again shows a fresh load of the page, and the second and third images show successive zooms in.

**Comment by madcowfred** [comment]
All known issues. PADherder isn't really designed for use on a mobile device - task switching is slow and annoying, and the Android version of PAD will close if you do pretty much anything (screen off? 50% chance PAD will close when you turn it on again).

Refer to GH-184 for future efforts.
