### ISSUE TITLE
Bug: popup on materials page

### ISSUE THREAD

**Issue by Tygre** [madcowfred/padherder-issues#185]
When I go to the my materials page to see which materials I need for what, I've noticed that if the pop up lists are too big, they won't stay activated.  It seems to happen when they activate and my mouse ends up superimposed on the list instead of underneath it on the screen.  I've also seen scroll bars on my browser popping in and out if the list is big enough.  I don't have a screenshot of it, because its a very fleeting thing.  Makes it really hard for me to read the list when its flickering in and out because I'm wiggling my mouse slightly trying to keep it activated.

**Comment by madcowfred** [comment]
Fixed, they should now show on the left/right based on page position.
