### ISSUE TITLE
Draggie on the "My Sets" page?

### ISSUE THREAD

**Issue by Hansekins** [madcowfred/padherder-issues#187]
I was looking at the Descended categories on the My Sets page to see which ones I still need to collect and it occurred to me that Draggie/Ancient Draggie Knight isn't listed anywhere on the Sets page.  Since Tengu is listed along with the other Descended monsters, it seems like Draggie belongs there as well, though the "Misc Dragons" category would work too probably.

(Unless I'm totally blind and I totally missed it there somewhere.)

**Comment by madcowfred** [comment]
Oops, completely forgot about Draggie. Added.
