### ISSUE TITLE
recently linked accounts not showing up in user popup menu

### ISSUE THREAD

**Issue by heartsofruin** [madcowfred/padherder-issues#188]
accounts: swansong, frenetic, amnesia

The accounts show as linked and verified under My Account (from all 3 accts), but from the frenetic and amnesia accts, none of the linked accounts appear in the user popup/switching menu at the top right of the window. When logged in as swansong then the other two accts do show up in switching menu.

**Comment by heartsofruin** [comment]
hm, appears to be fixed now, closing

**Comment by madcowfred** [comment]
This is actually a caching bug, reopening so I remember to fix it.

**Comment by madcowfred** [comment]
Fixed.
