### ISSUE TITLE
Priority, not granular enough.

### ISSUE THREAD

**Issue by necrillain** [madcowfred/padherder-issues#189]
The zero, low, med, high, done isn't granular enough.  Can that be changed to a 0-100 system or 0-10?

Also just because a monster is fully leveled doesn't mean it is done.  It isn't done until fully skilled, awoken and +297.

**Comment by keht191** [comment]
Max level is good enough to be considered done for all intents and purposes; the skills, awakenings are icing on the cake. Besides, the "sets" page shows the status of skill, awakenings and +s already as well as a more complete overview. No need to change it on the "monsters" page.

**Comment by necrillain** [comment]
The "sets" page doesn't have all sets.  So for people who play more as collectors that becomes somewhat limited.  I tried adding this ticket as a feature request not a bug, but couldn't figure out how to add that as a label.

Really was just trying to find a way to keep my focus team at the top of the list while still having a lot of high priority monsters for evolutions.  Basically I've made my top team all high priority and then moved everyone else to medium, even though If the sort order could be adjusted they'd be high as well.

**Comment by nevets1219** [comment]
To push your case along, I would recommend some use cases for more granular priority. As it is right now, I think it's more than capable. When something is maxed, it's highlighted in a light-green color so it's very noticeable. In the case your presented, your setup seems to be working well enough, what isn't it accomplishing that you need even more granularity?

I think most people just put "BUG" or "Suggestion" in the title of their issue, I believe only the owner can set labels.

**Comment by madcowfred** [comment]
Going with "no" on this one also - messing with the priority setup is a lot of work for very little gain.
