### ISSUE TITLE
Pengdra

### ISSUE THREAD

**Issue by Dakiton** [madcowfred/padherder-issues#193]
It would be nice to track pengdra and there corresponding dragons in the my material tab.  That way we can enter how many pengdra we have or dragons and such to keep track of them in total monster counts.  Tying this into the resources needed panel would be awesome also for thursday dungeons.

**Comment by Jinko78** [comment]
Yes please, this would be handy to have as a separate tab similar to materials but just for pendra's and possible other XP fodder / skill up fodder.

**Comment by madcowfred** [comment]
Added (finally), check out 'My Food' on the nav bar.
