### ISSUE TITLE
My 99 Awoken Hera

### ISSUE THREAD

**Issue by wpnewborn** [madcowfred/padherder-issues#194]
Isn't listed as DONE

I wish it was grouped up top with the rest of my max level monsters.

This _could_ be because she isn't ultimate evo'd but my Horus is grouped on top with the other finished monsters even though he has an ultimate evo too.

**Comment by madcowfred** [comment]
Yup, it's because she isn't ultimate evo'd. Assuming you're a US player, Flame Deity Falcon Horus will be listed as Done right now because his ultimate evos are still marked 'JP only'. Once they go live (whenever that happens :dog:) he'll also not count.
