### ISSUE TITLE
[Enhancement] Add XP for ultimate evolutions

### ISSUE THREAD

**Issue by dr-ishmael** [madcowfred/padherder-issues#197]
Basically as title: when you click to evolve a monster through an ultimate evolution, it should automatically add the experience gained from the evolution materials.  Obviously, if I get a Great/Super proc I'd have to edit the XP field anyway, but this feature would still be very convenient.

**Comment by keht191** [comment]
It's a negligible amount compared to what you would get from using pengdras or kings. Not really worth it to spend time developing.

**Comment by dr-ishmael** [comment]
Negligible?  Hardly.  I'm about to evolve Chaos Dragon Knight -> Chaos Dragon Knight Voice, and the XP gain is 38,563 - only a little less than a pengdra at 45k.

**Comment by madcowfred** [comment]
Added, evolving a monster will now automatically add the feed XP.
