### ISSUE TITLE
Request: Skill Ups

### ISSUE THREAD

**Issue by Inceptagon** [madcowfred/padherder-issues#199]
In the My Monsters list, I would like to have an at-a-glance list of the monsters required to skill up each monster, maybe in an additional column that can be toggled on and off, or maybe in a separate tab page.

This list could also be filtered by rarity, so you could see at a glance which common farmable monsters you still need while hiding gods.

**Comment by madcowfred** [comment]
I'm open to adding this, I just don't know where to put it - the My Monsters page is already pretty huge.

**Comment by madcowfred** [comment]
Closing in favour of GH-286 which will be implemented Soon(tm).
