### ISSUE TITLE
Request: Level dropdown starts at current level

### ISSUE THREAD

**Issue by Corbalt** [madcowfred/padherder-issues#200]
When you're changing the level of a monster, you're (almost?) always increasing its level, but currently when you open the dropdown the current level is at the very bottom of the selection box. It'd be nice if the current level was at the top of the box which would avoid scrolling in many cases.

Pretty small change, but convenience is nice. =]

**Comment by madcowfred** [comment]
The way selects are drawn is entirely up to the browser, I can't do anthing about where it's started. It would probably work if the list was in reverse order I guess?

**Comment by Corbalt** [comment]
Ah, not a front-end guy myself. I just assume you can do magic. =]

I personally would prefer that, but don't know if most people would find it odd. Either way, thanks for the great work on the app.

**Comment by madcowfred** [comment]
Finally getting around to changing this, oops.
