### ISSUE TITLE
Request: Current Rank in My Account

### ISSUE THREAD

**Issue by wpnewborn** [madcowfred/padherder-issues#201]
I love utilizing the new Friend Finder feature but I wish I could see player ranks (perhaps in a column between User and Friend ID?).  I don't like adding people with a high rank disparity because it means a tiny window of availability.

Perhaps users can keep their rank updated in a new field under My Account -> PAD Account.

Also, this would definitely help players get feedback in team build threads.  Often the first question after someone links their padherder is "What rank are you?" because that effects maximum team cost.

If you decide to implement Rank info, maybe this could be displayed on the main user page next to Friend ID (perhaps also along with maximum team cost?).

**Comment by madcowfred** [comment]
Added, displays on the public info header thing too.
