### ISSUE TITLE
Skill up tab

### ISSUE THREAD

**Issue by SingedKitty** [madcowfred/padherder-issues#203]
Just entered this in the PAD forum thread asking for PadHerder ideas, so thought I'd put it here as well where it actually belongs. :)

A way to manage mobs you have just for skill-ups would be fantastic. Hate having individual lines for babies i need to evolve to skill something up just so the mat requirements will go on the materials tab. Would also clean up my mess of a monster list as I could put dups here instead of on the monster tab unless I intend to use them both. 

Maybe something like:

Freyr
__ Freyr (# of those you have for skill ups)
__ CoC flame archer (# of those you have)
__ Coc archer (# of those you have + it adds required evo mats to your materials list)

Ideally, you'd pick the mob you are saving skill ups for and it would pull in the options for skillups, evolved and unevolved.

**Comment by madcowfred** [comment]
This is mostly related to GH-143 so I'm going to close it. Discuss there!
