### ISSUE TITLE
Unable to sort monsters by "Box (FAV)"

### ISSUE THREAD

**Issue by MezzanineMK2** [madcowfred/padherder-issues#204]
When I first opened PADHerder after the "Box (FAV)" sort was added, it worked fine. After logging in again several hours later, the sort has stopped working correctly, and instead sorts in the same order as "Default".
This may or may not be related to the fact that, after trying the "Box (FAV)" sort, I set my account preferences to use "Box (FAV)" as the default sorting method.

**Comment by madcowfred** [comment]
Fixed.

**Comment by MezzanineMK2** [comment]
Wow, thanks for the quick response! :+1: 
(I know, you were probably fixing it anyway)
