### ISSUE TITLE
Change email address?

### ISSUE THREAD

**Issue by SingedKitty** [madcowfred/padherder-issues#206]
Been trying to figure out why Gravatar isn't working for me on PADherder and the only thing I can think is I used my business email address when I signed up. Is there a way to change the email address associated with my account?

**Comment by madcowfred** [comment]
Apparently not, I'll add it to the list.

**Comment by madcowfred** [comment]
You can now change your email address in My Account. Some features are disabled until the new one is validated (Gravatars and automatic Disqus sign-on atm).
