### ISSUE TITLE
Stamina tracker

### ISSUE THREAD

**Issue by Ophiuchu** [madcowfred/padherder-issues#207]
I like the reminders and timer for upcoming urgent dungeons. Think it would be possible to take that a step further including a stamina manager to help plan stamina use through out the day for things like this too?

**Comment by madcowfred** [comment]
Having never used a stamina tracker/manager thing, what would it do?

**Comment by TheMidgardWatcher** [comment]
This is must be a sort of timer, where user must specify current stamina, max/needed stamina and launch timer, that adding +1 to current stamina and sends notification when reaching needed/max quantity

**Comment by Ophiuchu** [comment]
Example: http://www.puzzledragonx.com/en/calculator2.asp

You type in either how much stamina you want to gain or a time frame to figure out exactly how much you get over a certain period of time. It's useful to calculate if you have X amount of stamina and need Y stamina at an exact time to do urgent dungeons when they happen. That way you don't spend too much and can start storing stamina when needed. Basically, it would be there to help plan out your total stamina use for effecient running through the day!

**Comment by sg58** [comment]
This would be great to have... even just modify the current timer.  Something like:

Alert! Dungeon in 5h30m  (33stm)  
Alert! Dungeon in 2h45m  (16stm)  
etc

Would help in figuring out if you have time to run another dungeon and still have enough stamina for the special dungeon on the way. 

Otherwise, fantastic site... great job!

**Comment by TheMidgardWatcher** [comment]
Hey, sg58 - such alert are live on padherder!

**Comment by TyrAlduin** [comment]
FYI
I am going to assume that everyone has a Smart Phone or Tablet that they play P&D on? I know for Android Users on the Play Store there is an App called PadGuide(Maybe Apple has it as well?). It will sync with your account # along with you starter color and tell you when daily dungeons for you are, give you basic info on those dungeons, and how much stam you will have if you wait to do it from your current time. Also, If you want you can set an alarm through the program to tell you when your daily timed dungeons are available. That being said it also has a Stam Calculator along with player rank xp/dungeon ranking/xp calculator/friend tracker and link to offical PAD twitter. It does have a collection list but it's functionality isn't as good as PADherder and Freddie does such an amazing job updating I will always use Padherder for tracking of my monsters. 

No need for him to bust his balls to add a stam calc, but maybe that's just me o. O

**Comment by TheMidgardWatcher** [comment]
Agreed with TyrAlduin, i'm using padguide too. And hey, i've communicated with developer of PADGuide and he says that team management will be preferred feature for next version. But such functionality (stamina timer) wouldn't be unnecessary in PadHerder

**Comment by madcowfred** [comment]
I could add something simple like the suggested stamina amount to the events dropdown, possibly not to the navbar itself due to width concerns:
![padherder86](https://f.cloud.github.com/assets/99630/2157373/60a5f606-9479-11e3-8bb0-7e898f0674ad.png)

**Comment by madcowfred** [comment]
Implemented stam on the dropdown a la above screenshot, beyond that I don't really see a use for a stamina calculator or anywhere to put it :dog:
