### ISSUE TITLE
Add API for modifying my monsters

### ISSUE THREAD

**Issue by fullerth** [madcowfred/padherder-issues#208]
I'd like to use an API to modify my monster attributes.

**Comment by wmedlar** [comment]
Likewise, I'd love an API to pull user-specific monster stats/teams with my IRC bot.

**Comment by madcowfred** [comment]
I could provide some sort of basic REST API with the usual create/read/update/delete things. What data formats?

necromanteion:
- How would you be looking up the monsters? Internally, user monsters have a unique ID which isn't really obviously available to people.
- What kind of data do you want?

**Comment by wmedlar** [comment]
Is a unique JSON array of a user's box possible? As for the data, that's up to you. Monster name/ID, level, skill level, awakenings, and +eggs would be pretty rad, but I don't know how much of a task that is for you.

Sounds pretty complicated for both of us, so I wouldn't worry about it.

**Comment by madcowfred** [comment]
It's pretty easy on my end, I'll throw something together.

**Comment by wmedlar** [comment]
Thanks! I really appreciate it.

**Comment by fullerth** [comment]
First off apologies as I'm still figuring all this stuff out and I'm not very clear on the terminology. 

I suppose if I could request a JSON array with my box then modify it and send it back to modify attributes based on the PAD herder unique id, would that work? 

If it matches the JSON the game sends, even better!

**Comment by madcowfred** [comment]
I've just deployed an initial version of this, it uses the same authentication details as the rest of the website for now. API endpoints honour the 'public' setting. Note that the 'target_evolution' field needs an evolution ID from http://www.padherder.com/api/evolutions/ if you're changing it.

I'll document it properly at some point, but for now:

GET /user-api/username/monsters/ will retrieve a giant list of monster data for that user.

POST /user-api/username/monsters/ with some JSON data will create a monster. Something as simple as '{ "monster": 490 }' will work, or you can fill in the various other fields. Converting from the game JSON shouldn't be too hard, if you run into any issues let me know.

GET /user-api/username/monsters/id/ will retrieve a specific monster's details.

PUT /user-api/username/monsters/id/ with some JSON data will update a monster. 'id' and 'monster' are read-only, the rest are modifiable.

DELETE /user-api/username/monsters/id/ will delete a specific monster.

**Comment by madcowfred** [comment]
Ended up rewriting this to fix a bunch of issues :|

GET /user-api/user/freddie/ will return some basic user info and their monsters

POST /user-api/monster/ with some data will create a monster. The field names have to match what it returns in the above URL, though the only required field is 'monster'.

GET /user-api/monster/1234/ will return a specific monster

PATCH /user-api/monster/1234/ with some data will update a specific monster. The field names have to match and 'monster' is required.

DELETE /user-api/monster/1234/ will delete a specific monster

**Comment by wmedlar** [comment]
The first version worked perfectly for me, but for whatever reason I can't get my JSON parser to return any data after the revision, nor can I view any other user's box JSON. Any advice?

**Comment by madcowfred** [comment]
The first version had a bunch of internal issues, that's the main reason for the change. Things not working is actually... because I broke the permissions check and my tests were lacking :dog: It now correctly returns a 403 error with the body being {"detail": "Authentication credentials were not provided."}.

**Comment by madcowfred** [comment]
Some more updates:
- Re-enabled the browsable API stuff. Point a browser at http://www.padherder.com/user-api/user/freddie/ for instance.
- Added 'url' fields to the /user/foo/ API, link directly to the details for that item (also the URL you use to PUT/PATCH).
- Added materials. You can't create new materials or change the monster ID, pretty much all you can do is post '{ "count": 6 }' to the relevant URL.

**Comment by fullerth** [comment]
The authentication works for me in the browser, but urllib.urlopen in python3.3 allows me to get any monster ID with impunity. I haven't figured out how to do a patch yet, so I'm not sure if I can modify monsters.

**Comment by madcowfred** [comment]
The authentication check goes in this order:
- Is the user authenticated AND the owner of this item? Full access.
- Is it a read only call (GET, OPTIONS, HEAD) and the object is owned by someone with profile.public set? Read access.
- No access.

**Comment by madcowfred** [comment]
Also I threw together a working example: https://github.com/madcowfred/padherder-sync . Please heed the warning, it seems to work but who knows :bomb:

**Comment by fullerth** [comment]
Thanks for putting that together, it works great for me and is going to be good learning for me to poke through and figure out how it works.

**Comment by madcowfred** [comment]
Seems to work reasonably well, closing this issue.
