### ISSUE TITLE
Add Tamadras to My Materials

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#209]
It would be nice to have a Tamadra count, as well as a "missing awakenings" tied to each priority, in the same way that necessary evo mats are currently tabulated.

**Comment by madcowfred** [comment]
Not sure that this would work very well - I have 146 monsters between Low/Medium/High, most of which (being a US player) are not awakened. My lists would be huuuge :(

**Comment by madcowfred** [comment]
Gave this some more thought, still don't want to add it. I may add some sort of 'Needs awakening' filter to My Monsters instead.
