### ISSUE TITLE
Top bar covering up Add/Bulk Monsters and filters

### ISSUE THREAD

**Issue by TyrAlduin** [madcowfred/padherder-issues#212]
Freddie, not a big issue for me but please see PF link:
http://puzzleanddragonsforum.com/showthread.php?tid=36765&pid=346991#pid346991

Seems some iPad users are unable to see the Filters and Add/Bulk add due to the top bar re-sizing and covering it up which I have noticed happens to me when my browser is not long enough.

**Comment by madcowfred** [comment]
Should be fixed now, the navbar will adjust itself slightly more intelligently as screen width reduces.

**Comment by TyrAlduin** [comment]
Awesome Thanks!
