### ISSUE TITLE
Bug/Suggestion Can't delete monster in a team

### ISSUE THREAD

**Issue by Tygre** [madcowfred/padherder-issues#215]
I accidentally deleted a monster that was in one of my team builds and now I can't look at that team anymore.  Make it so you can't delete a monster in a team, kinda like ingame where you can't eat or sell a monster in use.

**Comment by madcowfred** [comment]
Was it a leader or sub of the team? It's supposed to just set the slot empty if you delete a sub :|

**Comment by Tygre** [comment]
it was a sub

**Comment by Tygre** [comment]
oh, I reloaded that account and now its a blank, so working as intended I suppose!

**Comment by madcowfred** [comment]
Well that will be a fun caching bug, I'll fix that and add a warning about deleting team leaders to the confirm dialog.

**Comment by madcowfred** [comment]
This is partially fixed, in the sense that I've completely disabled local caching of monster data due to the sheer number of corner cases involved. I still need to add a warning when deleting a monster that is a team leader.

**Comment by madcowfred** [comment]
Added a warning when deleting a team leader.
