### ISSUE TITLE
Request: Change Name

### ISSUE THREAD

**Issue by xirtpad** [madcowfred/padherder-issues#216]
Hello. I wonder if there is a way to change my name on padherder. Thanks.

**Comment by madcowfred** [comment]
There's no automated way to do so right now, I'll look in to adding one.

**Comment by madcowfred** [comment]
Would GH-299 work? Having a field to change the name that displays is a lot easier than dealing with changing actual account names.

**Comment by madcowfred** [comment]
You can now change your display name, see GH-299. Changing account names probably won't happen without my direct intervention for now.
