### ISSUE TITLE
Bug/Suggestion: Can't move teams in list up in list

### ISSUE THREAD

**Issue by kousaka** [madcowfred/padherder-issues#217]
Can't move teams in teamlist up in the list. Can only move them down. The list says it saves although a page refresh shows no changes.

**Comment by madcowfred** [comment]
Are you using the arrows or drag/drop?

**Comment by kousaka** [comment]
Drag drop.

I didn't realize the arrows were even click to use until now. That helps me work around it.

**Comment by madcowfred** [comment]
They do have tooltips, though nobody seems to look at them. The drag and drop thing has been a constant source of pain, I can't get it to work at all right now in either Chrome or Firefox. Adding it to the list of things to investigate.

**Comment by madcowfred** [comment]
Alright, I've replaced the broken library with a different one and everything seems to work properly for me. Can you test drag/drop and let me know if it works?

**Comment by kousaka** [comment]
Works great! Thanks for the quick response. Good job on the site
