### ISSUE TITLE
User notepad?

### ISSUE THREAD

**Issue by Hansekins** [madcowfred/padherder-issues#22]
Just started using PadHerder.. love it. Was wondering whether a notepad type function could be implemented, so users can make certain notes of their own. Example: I was thinking about how the PAD friends list doesn't show you other monsters that your friends have used as leads in the past, and that it might be nice to keep notes on some of them (because I certainly can't remember who has a War Deity Ares or Seraphim of Dawn Lucifer at any given moment).

Not sure whether such a thing would be too resource intensive or not.  Thanks!

**Comment by madcowfred** [comment]
This is really outside the scope of PADherder, use a notepad app on your phone or something to keep track.
