### ISSUE TITLE
When a monster is considered "done".

### ISSUE THREAD

**Issue by Kinglink** [madcowfred/padherder-issues#221]
Either let me select done (for instance a D/D Batman is done even though there is an evolve, because I want him for Draggie.)

Also Monsters that can't be skilled up are done.  Super Shimota Leek for instance can never be skilled up, so they are "done".    I'm unable to improve on them.  

In addition "Max evolved" and "ultimate evolved" are different things.  Hera versus her ultimate evolution for instance. is 200 extra stats.  She's maxed evolved.    There are those Ultimate evolves that people won't do due to losing stats Horus and Isis have one of the two that just isn't needed.

**Comment by madcowfred** [comment]
Selecting done is a decent option, the problem on my end is finding space to put the toggle when editing a monster :v

Super Shimota Leek is an Evo Material, right now those are excluded from being 'Done' to not clutter up the place (and the fact that they don't really require any effort).

'Max evolved' in PADherder's sense is "there are no future evolutions available for this monster". Hera's ultime is kind of useless, sure, but I don't want to have to go through and special case monsters for a "good" ultimate vs a "bad" ultimate counting as done.
