### ISSUE TITLE
Some existing teams are missing monsters

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#222]
I noticed today that several of my teams are now missing members. 

Examples:
http://www.padherder.com/user/scrllock/teams/#7358
http://www.padherder.com/user/scrllock/teams/#4590
http://www.padherder.com/user/scrllock/teams/#8504

**Comment by madcowfred** [comment]
There's only 2 ways this can happen:
- You deleted the monster that lived in that position
- You edited the teams and set the subs to -NONE-

I would assume the former, and since a team only stores references to your monsters, once it deletes them they are set to blank spots.

**Comment by ngamber** [comment]
I accidentally deleted an echidna earlier, which might explain some of the missing ones, but I know for sure that I haven't deleted my valk, verche, or orochi, which were the other subs in this team (and definitely didn't edit any of the teams): 

http://www.padherder.com/user/scrllock/teams/#9344

Not a big deal, I can fix mine, just wanted to make sure you were aware. So far it looks like the ones missing multiple subs are ones that my echidna _was_ in, so I'd guess that if there is a bug, it's just that deleting one sub in a team may cause others to disappear?

**Comment by madcowfred** [comment]
Well that's a bit more interesting, I shall investigate.

**Comment by madcowfred** [comment]
Can't seem to reproduce this, reopen if you can work out what sequence of events leads to weirdness.
