### ISSUE TITLE
Enhancement: Find Friends shows time since last action

### ISSUE THREAD

**Issue by wshsu314159** [madcowfred/padherder-issues#223]
It would be nice to know which potential Friend Leaders are still active, rather than find a list of awesome +297 leaders that have moved on.  If last activity date is too stalkerish, it can just warn about people who haven't done anything in the past 1-2 weeks.

No, not everyone will religiously maintain their Padherder account relative to their monster box, but at least it's a rough indicator of activity for a game that encourages frequent logins.

**Comment by madcowfred** [comment]
PADherder currently doesn't track anything beyond 'last login', which can be several weeks ago even for active users. I could add something to track last action and then display "today", "yesterday", "2 days ago" along to "more than a week ago" or something?

**Comment by madcowfred** [comment]
Added as a new column on 'By Monster' results table.
