### ISSUE TITLE
Materials not showing

### ISSUE THREAD

**Issue by Ashara** [madcowfred/padherder-issues#224]
I have "Show reminders about needed materials from daily dungeons" selected in my account settings, but they aren't showing up. I've tried deselecting/reselecting and logging in/out, but no luck. Help! :)

**Comment by madcowfred** [comment]
Do you need materials? If you actually do, you probably shouldn't press "Hide for today" unless you actually want to hide it. Ctrl-shift-J, 'localStorage.clear()'.

**Comment by Ashara** [comment]
Thank you.
But I didn't press that for today, I did it a few days ago and it never
defaulted back to showing them.
I just won't hide them again. :)

**Comment by madcowfred** [comment]
Well that's weird - I've definitely used it a few times and it works again the next day. It saves the hide status as "hide for this date", I'm not sure how it could get confused :(

**Comment by madcowfred** [comment]
Apparently this was an amusing bug where pressing 'Hide for today' on a Tuesday would actually hide all Tuesday reminders for the current month. Oops. Fixed.

**Comment by Ashara** [comment]
Ahhh, thank you! I was SURE that I only 'hid for today' once and then...
wonkiness. :)

You're the best.
