### ISSUE TITLE
[Bug] Negative stamina after urgent dungeon opens

### ISSUE THREAD

**Issue by dr-ishmael** [madcowfred/padherder-issues#227]
Related to #207 - when an urgent dungeon is currently active, it shows negative stamina gain.  Should probably turn this off for the active dungeon.
![padherder_neg_stamina_urgent_dungeon](https://f.cloud.github.com/assets/1929447/2178050/449b2ef4-9654-11e3-8636-9ad97b975f32.png)

**Comment by madcowfred** [comment]
Fixed.

**Comment by dr-ishmael** [comment]
Awesome!
