### ISSUE TITLE
Sort Teams (Suggestion)

### ISSUE THREAD

**Issue by Twyst** [madcowfred/padherder-issues#228]
I use teams a lot, and it would be helpful to be able to create folders of teams, or groups of teams in order to reduce the default list-size and better organize most effective/upcoming dungeon teams.

**Comment by keht191** [comment]
Sounds like the experimental teams request from before - just manage the numbers of teams on your own.

**Comment by Twyst** [comment]
I know I can manage the teams on my own, that is why it's a suggestion.

**Comment by madcowfred** [comment]
I kind of like the idea - I have 21 teams with more than half of them being dungeon specific stuff. Will have to think on a sane way to organise some sort of UI for this (open to ideas).

**Comment by Twyst** [comment]
I think you could do it very similarly to how the teams are handled now, 
but create folders that expand : 
https://www.dropbox.com/s/n4vrnidrdu5lfc3/mockup.jpg  this is my 
early-morning only using paint mockup.

**Comment by madcowfred** [comment]
The JS library I'm using (http://johnny.github.io/jquery-sortable/) actually has a few examples of such things, I'll see how I go with implementing something.

**Comment by madcowfred** [comment]
Implemented this, go drag and drop between groups to your heart's content. You can rename the groups in My Account.

**Comment by Twyst** [comment]
Awesome!
