### ISSUE TITLE
Bug: After editting a monster the tooltip stays and covers up editting/saving option

### ISSUE THREAD

**Issue by Jakeywakey** [madcowfred/padherder-issues#229]
![issue with edit this monster](https://f.cloud.github.com/assets/6562997/2178292/ae8d11ac-9662-11e3-84ea-c2ca83d1c5a1.PNG)

As you can see the edit tooltip doesn't go away and stays there unless you refresh the page

**Comment by madcowfred** [comment]
Fixed. Hopefully that's the last of the damn tooltip bugs :cactus:
