### ISSUE TITLE
Any ETA on new Awoken skills for REM cards?

### ISSUE THREAD

**Issue by sunglassesmichael** [madcowfred/padherder-issues#230]
Not a huge deal, just curious since I think it's been a couple weeks at this point since they came to the JP version.

**Comment by madcowfred** [comment]
Probably when they show up in the US version - since a lot of them are changes to old monsters, I don't really want data to be 'wrong' for the majority of users (144 JP vs 9,390 non-JP).

**Comment by sunglassesmichael** [comment]
Ah! I guess that does make sense. Thanks.

Also, wow! Didn't realize the number of people using the JP version was that small. Not surprising, on the one hand, but I thought more US users might have JP alts than that.

**Comment by madcowfred** [comment]
Updated for 6.4
