### ISSUE TITLE
Sort by Ready to Evolve

### ISSUE THREAD

**Issue by mindreave** [madcowfred/padherder-issues#232]
Can there be a sort option that puts monsters that are ready to evolve at the top?
Max level and materials available for regular evolutions.
Materials available for busty evolutions.

**Comment by madcowfred** [comment]
I'd probably rather make this a filter than a sort - filter by 'Ready to evolve' or something.

**Comment by RabidDuckie** [comment]
I can get behind this. +1

**Comment by madcowfred** [comment]
Added a 'Ready to evolve' filter.
