### ISSUE TITLE
Request: to next level field if you enter level in add monster

### ISSUE THREAD

**Issue by Mateopato** [madcowfred/padherder-issues#233]
Unless I'm missing an easy way to determine how much experience one of your monsters has in the game without having to go to Power Up Fusion and then select the monster as a base monster, would it be possible to add a field next to the Level field in the Add Monster drop-down that lets you enter how much experience to the next level? Then, you could calculate how much experience the monster has using experience(level + 1) - toNextLevel. That way all the information you would need for a monster would be on the monster info screen in the game without having to go through Power Up Fusion. If you do implement calculating a monster's current experience this way, if you could find a way to add that in the edit monster row in the monster list that would be cool, too. 

You're doing an amazing job by the way.

**Comment by madcowfred** [comment]
I'm not against adding it, the probalm is that I'm not really sure where to add it. I'm actually curious though - do you update your XP exactly for every monster? I find that it's largely irrelevant what their exact XP is until they are close to being capped so I just change the level and that's good enough.

**Comment by Mateopato** [comment]
As someone still relatively new to the game, a lot of my monsters are still in their lower evolutions that don't require a ton of experience, so a lot of mine are pretty near the king dragon/pengdra or less range. I do batch update mine every once in a while. If I'm sitting at my computer as I play on the weekends I'll update them as I do power up fusions occasionally. I do like the pengdra remaining count to be mostly accurate so I know where to distribute my big experience monsters to get the best value.

**Comment by madcowfred** [comment]
Ah, ok. I still need to work out where to put the evil thing, or maybe... replace the Pengdra column with Cur/Next toggles for current or 'to next level' XP.

**Comment by Mateopato** [comment]
Hmmm... In the Add Monster pop-up menu, could you have an XP To Next Level box appear to the right of the level select drop-down if a level is chosen from the level drop-down? Then, you could have it go away after you click the Add Monster or Reset buttons from that menu. Or it could always be there, either way. 

As far as the monster list itself, I definitely wouldn't get rid of the pengdra column, that's an incredibly useful gauge of how much experience remains to be farmed. Unless you mean just replacing the pengdra column when you're editing a row in the monster list; that could be pretty nice. Maybe add a notice like the "Current XP, not needed XP!" notice currently beneath the Need XP column when editing that lets people know what the new field is for.

**Comment by madcowfred** [comment]
Implemented (finally) as part of the new add/edit dialog
