### ISSUE TITLE
My Monsters list does not claim I have the monsters.

### ISSUE THREAD

**Issue by thinkyt** [madcowfred/padherder-issues#236]
I run Chrome, and not only does the hover text claim that I have "no monsters" of when I do of that monster (image 1), but the 'Dungeon Reminder' ticker tells me that I have "one undefined x and need 1 x" (image 2).

I've tried clearing cache, refreshing, and relogging.
# No. 1:

![image](https://f.cloud.github.com/assets/6724810/2204672/2620026a-9942-11e3-802c-bf7a74d66eff.png)
# No. 2.

![image](https://f.cloud.github.com/assets/6724810/2204675/354b57da-9942-11e3-988d-5d1155d503ef.png)

**Comment by madcowfred** [comment]
The monster list isn't really for evolve materials - I need to add a warning when you try to add one explaining where to go. Try going to 'My Materials', filling in things there and hitting save.

**Comment by madcowfred** [comment]
Finally added a warning message when adding an Evolution Material type monster.
