### ISSUE TITLE
Option to Un-hide Daily reminders (similar to #196)

### ISSUE THREAD

**Issue by TyrAlduin** [madcowfred/padherder-issues#237]
Issue 196 was closed and dismissed as the person was asking on the weekend...
~~"I accidentally closed the reminder for dungeons with the new x feature #196"~~~
My Issue:
Yesterday (2/18/14), Tuesday, I got all of the keepers I could and then proceeded to hit "Hide For Today". I left the page open on a tab. This morning (2/19/14), Wednesday, I checked Padherder on my phone first and I saw the dungeon reminders for the masks I need. 
Upon returning to my browser and refreshing the page the reminders were no longer there. (I can still see them on my phone??). 
I am using Chrome if that means anything...I have tried logging out... I have switched accounts and see the reminders on the other accounts... I am assuming it thinks I hid the reminders for today as that was the last action I took on the page from the day before?

**Comment by madcowfred** [comment]
Apparently there really was an amusing bug here - picking 'Hide for today' would hide that reminder box for that day of the week for the _whole month_. Oops. Fixed.
