### ISSUE TITLE
Link to Tuesday, Wednesday, Thursday, Friday dungeons on group by dungeon

### ISSUE THREAD

**Issue by Mateopato** [madcowfred/padherder-issues#240]
It would be cool if you made the section labels in the My Materials - Group by Dungeon link to the appropriate pages on puzzledragonx. Either that or add links beside the labels. If you do it that way, you could add links to all of the different dungeons for each day rather than just one.

Here are the links to the top-level battle pages for each day's dungeon:
Tuesday: http://www.puzzledragonx.com/en/mission.asp?m=60
Wednesday: http://www.puzzledragonx.com/en/mission.asp?m=62
Thursday: http://www.puzzledragonx.com/en/mission.asp?m=63
Friday: http://www.puzzledragonx.com/en/mission.asp?m=65

Or if you want the dungeon-wide page for each day's dungeon:
Tuesday: http://www.puzzledragonx.com/en/dungeon.asp?d=17
Wednesday: http://www.puzzledragonx.com/en/dungeon.asp?d=18
Thursday: http://www.puzzledragonx.com/en/dungeon.asp?d=19
Friday: http://www.puzzledragonx.com/en/dungeon.asp?d=20

**Comment by madcowfred** [comment]
Seems reasonable, added [PDX] and [Wiki] links to each title.
