### ISSUE TITLE
Cannot find my monsters and my sets

### ISSUE THREAD

**Issue by coolchan** [madcowfred/padherder-issues#241]
I cannot find my monsters and sets when I clicked on these two tabs today. They always show loading monsters ... or loading sets ... But my materials is fine.

**Comment by Kinglink** [comment]
Same here and with a friend, looks like there's a problem with the monster database. 

Materials is fine as well.

**Comment by madcowfred** [comment]
It appears fine here, what browser/OS?

**Comment by Kinglink** [comment]
Happens on Chrome on my computer (Windows 7) and my android phone (Nexus 4, newest version of android)   Apparently Firefox works on my computer.

**Comment by Kinglink** [comment]
Never mind when I logged in as myself on Firefox it happened again.   The userpage is http://www.padherder.com/user/Kinglink/monsters/.    I can use BOTH firefox and Chrome when logged out.  When logged in, it infinite loads.

**Comment by coolchan** [comment]
For me, it only works in IE, but not for Chrome and Firefox.

**Comment by coolchan** [comment]
I updated my firefox and chrome. But it still doesn't work. It was fine yesterday.

**Comment by madcowfred** [comment]
Hit Ctrl-Shift-J in Chrome / Ctrl-Shift-K in Firefox and let me know if there are any errors appearing in the 'Console' tab.

**Comment by Kinglink** [comment]
In the console I see one error. 

> Uncaught TypeError: Cannot set property 'innerHTML' of undefined

**Comment by madcowfred** [comment]
Ah, that helped, should be fixed now if you refresh.

**Comment by Kinglink** [comment]
This is now working for me.  Thank you Freddie.
