### ISSUE TITLE
BUG: Incorrect Leader Skill data for Purin

### ISSUE THREAD

**Issue by RabidDuckie** [madcowfred/padherder-issues#242]
The leader skill for cards 1162 (Pompompurin) and 1163 (TAMADRApurin) show up as "unknownCategory 105," preventing the ATK multiplier and RCV reductions from calculating.

![tamadrapurinbug](https://f.cloud.github.com/assets/6531450/2214899/c98256b2-99e0-11e3-9815-e24392bca12f.jpg)

**Comment by madcowfred** [comment]
This is actually 2 separate problems:
- the wiki has bad data for the skill so it has unknownblah text
- the monster leader skill data wasn't entered in the giant list

I've fixed the second part and bugged someone to work out what's up with the wiki.
