### ISSUE TITLE
Teams disappeared when team groups was added

### ISSUE THREAD

**Issue by ryanscott** [madcowfred/padherder-issues#243]
I just added a team, and when the page refreshed all my other teams were gone, and all that was left was 5 empty team groups, with the single team I just added was all that was left.  I had about 80 teams saved, and it was a huge resource for both myself and many people in the community.  Is there a way you can recover my teams?  (username zaisha)

**Comment by madcowfred** [comment]
They're all still there as far as I can see. Open the console (Ctrl-Shift-K in Firefox, Ctrl-Shift-J in Chrome), switch to the 'Console' tab, type in 'localStorage.clear()', then reload the page.

**Comment by ryanscott** [comment]
yeah, they just appeared, thanks for the quick reply!
