### ISSUE TITLE
Padherder_sync, not deleting monsters.

### ISSUE THREAD

**Issue by Jinko78** [madcowfred/padherder-issues#244]
This is no doubt work in progress but thought I would mention it anyway, the padherder_sync function doesn't remove monsters from the list after you have used them for skill ups or as XP fodder.

This means you end up with a lot of dead monsters in your padherder box which you have to manually remove.

**Comment by madcowfred** [comment]
padherder-sync was only really meant to be an example of using the API, the fact that it works at all is a wonder. The issue with deleting monsters is that it does interesting things to teams:
- any team with that monster as a leader is deleted
- any team with that monster as a sub suddenly has a blank spot
  I could make it a command line option or something?

**Comment by Jinko78** [comment]
Yea adding it as a command line or an option would be greatly appreciated.

It's super helpful either way :D

**Comment by kruegerb** [comment]
I think the vast majority of monsters being manually deleted by padherder users after a sync are probably not subs or leaders on their teams.  With that in mind, simply checking to make sure a monster is not on any of the user's teams before deleting would go a long way.  I was going to code this up, but the ids of the monsters I was seeing in the teams JSON object seem to be in a different namespace, so I'm not sure how to compare them to the user's existing monsters.

**Comment by madcowfred** [comment]
The leader/sub1/sub2/sub3/sub4 team fields reference monster 'id' fields, I'm not sure what you mean here.

**Comment by kruegerb** [comment]
Thanks, I got a handle on it now.  I have some changes ready to test, but I'm getting 500 errors from the user-api at the moment.

**Comment by madcowfred** [comment]
That would be because I am a bad person and skipped running slow tests. Fixed.

**Comment by kruegerb** [comment]
Thanks for fixing that, even good people have been known to skip running slow tests :)  I'm getting monsters back from the user-api, but I'm also getting 500 errors when trying to create new monsters now.  Got any more slow tests you can run?  Let me know if you'd like me to create a new issue for that.

**Comment by madcowfred** [comment]
Test coverage: :cry:%. This really works now I just tested it honest. Also I merged your thing so closing this bug.

**Comment by kruegerb** [comment]
Awesome, thanks!
