### ISSUE TITLE
Awakenings reversed

### ISSUE THREAD

**Issue by uruloki** [madcowfred/padherder-issues#245]
When I mouse over the awakenings, the descriptions for +Orbs and row enhancements are backwards. For example, BAO Batman+BW Attack has the row enhancement text show up for the water and dark orb awakenings. Loki has the Orb enhancement text for both his row awakenings.

I'm using the Dark Theme.

**Comment by keht191** [comment]
Weird, I'm also using Dark and the awakenings have the correct text; I'm using Chrome FYI.

**Comment by madcowfred** [comment]
Oops, apparently they were swapped. Fixed.
