### ISSUE TITLE
Hover windows stay open

### ISSUE THREAD

**Issue by Mateopato** [madcowfred/padherder-issues#248]
In the monster list, if you're editing a monster row and your mouse hovers over something with a pop-up info window (e.g., the Pengdra column's experience conversion list or hovering over another row's evolution materials) and you hit enter to save the row that you're editing while the information window is up, whatever info window that was up when you hit enter to save stays up until you navigate to a different page. It persists through scrolling and it's repeatable. Here's a picture of several stuck open:

![image](https://f.cloud.github.com/assets/3789235/2232524/451695d0-9b1d-11e3-9226-e50f97f8d491.png)

While testing this, I noticed another strange bit of behavior. If, instead of the examples I gave above, you hover over the monsters to-be-evolved rather than the evolution materials in the Evolution column while you edit a row and hit enter to save, instead of the info window staying open, you can no longer view the monster info windows (they don't pop up anymore) for several monsters surrounding the one you were hovering over until you refresh the page or go to another page and come back. This also persists through scrolling. The mouse here is hovering over the Emerald Pengdra in the dark, highlighted row, so it should be showing the monster information for an Emerald Pengdra; instead, it shows nothing:

![image](https://f.cloud.github.com/assets/3789235/2232717/09acf2f2-9b20-11e3-9b91-421bcba5661d.png)

This is with Chrome Version 32.0.1700.107 m in Windows 7.

**Comment by madcowfred** [comment]
Argh, I really hate the popover/tooltip fun times. I have some idea what causes the second error, and the first is just making sure I find every possible case for closing active things.

**Comment by madcowfred** [comment]
This is hopefully finally fixed now.
