### ISSUE TITLE
Team view broken

### ISSUE THREAD

**Issue by pantsmessiah** [madcowfred/padherder-issues#249]
I want to say I noticed this this morning, maybe yesterday. I didn't see this already submitted so I'm sorry if it is a duplicate issue. 

When I go to my team list the view is totally messed up. It is fine if I am not logged in, but once I log in the view messes up as indicated in the picture. 

Using Chrome Version 32.0.1700.107 m and 33.0.1750.117 m

![capture](https://f.cloud.github.com/assets/5154613/2235130/b0ebf860-9b43-11e3-9921-37d4e86f582c.PNG)

**Comment by madcowfred** [comment]
Hrm, I can't reproduce this but I've taken a guess at what the issue is - try reloading the page and let me know if it's fixed.

**Comment by pantsmessiah** [comment]
I tried it on three different computers, but all were using Chrome. I tried to determine if it was any addon I had installed, but couldn't seem to make any change. 

Either way it is working now, so thanks for the quick response.
