### ISSUE TITLE
Mouseover text - Enhanced Dark Orb 

### ISSUE THREAD

**Issue by pdxmarcos** [madcowfred/padherder-issues#250]
The mouseover text for Enhanced Dark Orb for Awoken Hera reads: Enhanced Dark orbs - Gives a 20% chance for dropped _light_ orbs to spawn as enhanced orbs.

Should read as _Dark_ orbs.

![enhanced dark orbs](https://f.cloud.github.com/assets/6752419/2235529/f3d8dd7c-9b49-11e3-8940-729599b30431.PNG)

**Comment by madcowfred** [comment]
Fixed.
