### ISSUE TITLE
hover window getting squished

### ISSUE THREAD

**Issue by Tygre** [madcowfred/padherder-issues#251]
when I hover over my materials count, and it's close to the right side of the browser window, the popup squishes instead of flipping sides so it has room to display the text instead of having 1 word per line :-P

**Comment by madcowfred** [comment]
Uhh definitely can't reproduce in either Firefox or Chrome, assuming you mean on My Materials.

**Comment by Tygre** [comment]
I'm using firefox, this just started. Cleaned the local storage and reloaded page just before this screenshot.
![screenshot307](https://f.cloud.github.com/assets/6262708/2237063/8de3069c-9b84-11e3-9b3b-bd1324419cb2.jpg)

**Comment by madcowfred** [comment]
I have no idea, absolutely can't reproduce with current Firefox on Win7 :(

**Comment by Tygre** [comment]
I have no idea either, it was still doing it even after I restarted my comp.  But now its back to normal, lol.  Computer bugs ftw? xD

**Comment by madcowfred** [comment]
If you work out how to reproduce it, feel free to reopen this. Until then I am blaming ghosts.
