### ISSUE TITLE
New Batman Mobs

### ISSUE THREAD

**Issue by Gannonball09** [madcowfred/padherder-issues#252]
Not able to put the new Batman collab monsters.

**Comment by madcowfred** [comment]
Um you'll need to be a little less vague - what exactly is the problem?

**Comment by Gannonball09** [comment]
Nevermind. I was bulk adding the newer Batman Collab monsters and the numbers do not correspond with the game. I just did a regular add and it worked. Thanks!

**Comment by madcowfred** [comment]
Fixed.
