### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by Lapan** [madcowfred/padherder-issues#253]
The timezone for Vienna seems off by more than hour, i assume you used another timezone instead of GMT+1. Events are shown starting early in PADherder

**Comment by Lapan** [comment]
Seems to be 2 hours actually, started just now

**Comment by madcowfred** [comment]
The times are sent to your browser as UTC - my timezone is set to Australia/Adelaide but I get:

[{"starts_at":"2014-02-24T03:00:00Z","country":2,"group_name":"C","title":"Alert! Metal Dragons!"}]

... and I live in a weird :30 timezone. The timezone account setting only really affects the time that news items were posted afaik.

**Comment by Lapan** [comment]
Ah, i see.

Might be a nice future feature to add then? :P

**Comment by madcowfred** [comment]
Er, I'm not doing a good job explaining here. Your browser does the conversion to local time - if it's coming up with the wrong time for everything it's possible that your OS is set to the wrong timezone.

**Comment by Lapan** [comment]
My OS's timezone is set fine. But if the timer is not affecting the event ticker, but only the news it explains why they were off by a few hours
