### ISSUE TITLE
The PDX Simulator button doesn't use friend stats

### ISSUE THREAD

**Issue by wesdotcool** [madcowfred/padherder-issues#254]
My monster +'s and awakenings are shown on PDX, but not my friend's.

Here's my team:
http://www.padherder.com/user/wesdotcool/teams/#23760

Here's the generated PDX link:
http://www.puzzledragonx.com/en/simulator.asp?q=890.99.1.99.99.99.3..202.99.7.10.1.24.0..692.99.7.0.0.1.0..365.99.1.0.0.0.0..986.99.2.0.0.0.0..653.99.1.0.0.0.0..

It should have generated this link:
http://www.puzzledragonx.com/en/simulator.asp?q=890.99.1.99.99.99.3..202.99.7.10.1.24.0..692.99.7.0.0.1.0..365.99.1.0.0.0.0..986.99.2.0.0.0.0..653.99.1.99.99.99.3..

**Comment by madcowfred** [comment]
Fixed.
