### ISSUE TITLE
Change status to "Done" when no further evolution is selected and max level.

### ISSUE THREAD

**Issue by xeroten** [madcowfred/padherder-issues#255]
I would like to have a done status for monsters I am intentionally keeping at a lower evolution for cost-restricted dungeons.

**Comment by sunglassesmichael** [comment]
Can't you just use zero for that?

I would like to have a "Highest" or "Top" priority, though.

**Comment by xeroten** [comment]
To me, zero mean it's an unimportant monster you don't care about. Done means something you've maxed out for a purpose.

**Comment by madcowfred** [comment]
I appear to have accidentally completed this today when I updated how 'Done' works - see http://www.padherder.com/news/53/ for details.
