### ISSUE TITLE
Request: Add CORS support to API

### ISSUE THREAD

**Issue by Spiridios** [madcowfred/padherder-issues#256]
I'm working on a tool that computes some stats based on a user's monster data. The app is 100% client-side javascript, save one part - the part that fetches the Padherder data. Due to the same origin security policy in browsers, I'm not able to make the request to the padherder API unless I bounce the request through a proxy on my server.

I'm not very familiar with Django, would it be possible to enable CORS support in it? On the surface it seems relatively easy: https://github.com/OttoYiu/django-cors-headers

Alternatively, is there support for json-p? A random stackoverflow suggests it's supported by default, but when I tried ?format=json-p, I got a "not found" response.

**Comment by madcowfred** [comment]
I've enabled CORS headers for /api/ and /user-api/ URLs. It will only allow GET and OPTIONS requests for now.

**Comment by Spiridios** [comment]
Thanks! I think if I wanted to anything more serious than read-only queries, then I'd probably be doing something more than just client-side only Javascript, so that's a good compromise.
