### ISSUE TITLE
Request: User API for teams

### ISSUE THREAD

**Issue by Spiridios** [madcowfred/padherder-issues#257]
I'm working on a tool that computes monster stats, and it would be nice to be able to limit it to specific teams. I don't see anything in the current API that allows you to see a user's teams.

**Comment by madcowfred** [comment]
Added a 'teams' field to the /user/[username]/ API and a /team/[id]/ call for specific teams. This is read only for now, not sure I want to add write support to it.

**Comment by Spiridios** [comment]
Thanks! Read-only is just fine, padherder has a perfectly good team manager as is.
