### ISSUE TITLE
Bug: Tuesday Dungeon Reminder

### ISSUE THREAD

**Issue by Jakeywakey** [madcowfred/padherder-issues#259]
I've only noticed it for the Tuesday dungeon, but if I have a monster I don't want to evolve and I change the option for the monster to where I specify that I don't want to evolve it, the dungeon reminder is still telling me to do the dungeon in order to farm the materials for it. I know that with other dungeons and in the past the reminder will skip over those monsters that you specify that you are not evolving. If thats confusing I can snap some screenshots no problemo

**Comment by madcowfred** [comment]
Fixed.
