### ISSUE TITLE
Skill Description "Grudge Strike"

### ISSUE THREAD

**Issue by TheMidgardWatcher** [madcowfred/padherder-issues#262]
Just cleared Dragon zombie dongeon and saw that Skill Description for 
Devil Fish active skill (Same as Vritra) doesn't correspond to PDX description:
1. Desc from PadHerder: http://clip2net.com/s/6V5rs0
2. Desc from PDX: http://www.puzzledragonx.com/en/monster.asp?n=1064

As we see - descriptions doesn't same.

**Comment by madcowfred** [comment]
PADherder doesn't get monster data from PDX, bug someone at the wiki to fix it if it's wrong: http://pad.wikia.com/wiki/Grudge_Strike
