### ISSUE TITLE
Option to switch between evolutions

### ISSUE THREAD

**Issue by wshsu314159** [madcowfred/padherder-issues#263]
I saw this in a news comment, but didn't see a formal ticket for it.

In-game it's possible to undo and redo ultimate evolutions, but in padherder the only way to do this is delete and recreate the monster.  As a non-angelit-haver who just acquired a Parvati, I see this happening in the future.

Maybe add an option in the evolution interface to pick a different evolution beyond the next step up?

**Comment by madcowfred** [comment]
My current plan is that when you edit an ultimate evolved monster, you are able to pick the evolution as though it was the previous step - choices would be:
- Previous
  - Current evo
  - Some other evo

From there the 'evolution chain' works as normally, you just have the de-evolve step as a normal evolution (1 of each lit) and the other ultimate as the second part of the chain. Now to actually implement that...

**Comment by madcowfred** [comment]
This was a lot more work than expected but it should be done now, go forth and change to alternate ultimate evolutions as much as you want.
