### ISSUE TITLE
Add new evolution for Alaurune

### ISSUE THREAD

**Issue by loydb** [madcowfred/padherder-issues#264]
It would be nice to get Alaurane's second evo available. Thanks!
(http://www.puzzledragonx.com/en/monster.asp?n=1101)

**Comment by madcowfred** [comment]
Um, it seems to be there - I can certainly pick from the two as an evolution choice, and all 3 'Blah de blah, Alraune' monsters are in the Add Monster list.

**Comment by loydb** [comment]
Strange, the only evo it shows available for me is the Creation one. I'll
try deleting her and manually entering her as a new monster with the World
evo version. Thanks for the prompt attention, you've made a great resource.

Loyd

On Mon, Mar 3, 2014 at 2:49 AM, Freddie notifications@github.com wrote:

> Um, it seems to be there - I can certainly pick from the two as an
> evolution choice, and all 3 'Blah de blah, Alraune' monsters are in the Add
> Monster list.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/madcowfred/padherder-issues/issues/264#issuecomment-36487810
> .

## 

Public Key --
ssh-rsa
AAAAB3NzaC1yc2EAAAABJQAAAIBGbwvNjzH46bxe0vUqpj9UjXpVHNzxSAMvIi9D2CcrvBlYNyKL6wMWT0YsD2QqKM6DOjc58GojhFPkhrA3PNymM7cpOF7f9d0UaWMSS4KiN4vPj9Z+LDpIa9XbWi/W77ymg+ts2CNQu2UlZwPi/UGzmOt3ncA/7L+z4r/SGy4GVw==
rsa-key-20050419
