### ISSUE TITLE
Include max level for friend search?

### ISSUE THREAD

**Issue by benjaminswill** [madcowfred/padherder-issues#266]
It would be nice to either include a max level for friend searching or add more pages/display more results - since when I search, say, WR Valkyrie, I get mostly level 99, and all over level 80. Probably users who are at a much higher rank than me and not as compatible as friends. 

Thanks for all your hard work, this is an amazing tool!

**Comment by madcowfred** [comment]
It would probably make more sense to have the search be something like "within X ranks of me", defaulting to 50 or so. I'm sure there are plenty of low rank people with maxed monsters/high rank people with low level monsters around :dog:

**Comment by discomethod** [comment]
for the purposes of being able to use your friends' monsters, people who have lower rank than you will always be available to you 12 hours after their last activity (the maximum length). so assuming they're willing to accept your friend requests, there's not really a reason to not use a lower level user's leader (as long as it satisfies your level/skillup/awoken criterion).

what i'm getting at is that "within X ranks of me" would probably exclude some results for low level users that would be equally helpful, as long as their leader monster satisfies your search requirements.

**Comment by madcowfred** [comment]
Do you have a link to some investigation into how friend availability works? Mostly curious about how much less time you get from higher ranks.

**Comment by discomethod** [comment]
Copied and pasted from the P&D Facebook group, which seems to have held true in my experience:

_Puzzle & Dragons limits the timeframe during which you can use a friend’s character based on their rank relative to yours, and the last time they connected to the server through their game. Additionally, once you have used one of your friends they will not be available again until they reconnect to the server through their game (see ‘Relogging’). The time frame during which your friends’ characters are available to you is 12 hours -1 hour for every 5 ranks they have above your own, with a minimum of 1 (e.g. you 100 vs them 140 = 4 hours; you 100 vs them 200 = 1 hour). No timeframe penalty is applied to using friends ranked below yourself. This gameplay mechanic limits the the ability of low-rank players to benefit from highly ranked friends unless those friends ‘relog’ frequently to remain available._

Also notable is that whenever "A new day has begun!", the game treats all your friends as having just logged on. So, you can use the leaders of people on your friend's list who haven't logged on in months. If you are higher level than them, you have half a day to use their leader, even if the last time they played was two months ago :)

**Comment by madcowfred** [comment]
Hm, cool. Some sort of "at most [40] ranks above me" checkbox might be reasonable then.

**Comment by madcowfred** [comment]
Added.

**Comment by discomethod** [comment]
The checkbox you added doesn't remember its checked value after searching. Intended?

**Comment by madcowfred** [comment]
Nope. Fixed.
