### ISSUE TITLE
Make it possible to add a 'material' in the Team section (e.g. Rainbow Keeper)

### ISSUE THREAD

**Issue by loydb** [madcowfred/padherder-issues#267]
There are a lot of teams where, for point cost reasons, a Dub or a Keeper fit in well. Currently they can't be selected from the Team builder.

**Comment by madcowfred** [comment]
You can just go add the Dublit or Keeper to your monsters list, that's the supported method. I don't really want to have to hack up the way teams work to support "I want to use a monster that isn't on my owned monster list" as it's pretty nasty :( I could certainly document this a little better somewhere though.

**Comment by loydb** [comment]
Ah, I'd assumed it biased against type Evo, rather than promoting from my own Monsters list. Yes, that's an easy enough workaround, and should probably be mentioned somewhere on the team screen. Thanks.
