### ISSUE TITLE
Type in monster popups

### ISSUE THREAD

**Issue by kinonymous** [madcowfred/padherder-issues#269]
Unless I'm really missing something, it seems like everything but type (Dragon, God, Balanced, etc...) is listed in the popups when you hover over a monster.

**Comment by madcowfred** [comment]
Possibly because nobody ever asked for it, or if they did I forgot (this happens a lot). Not entirely sure where to put it on the popover though.

**Comment by kinonymous** [comment]
Hmmm... Perhaps you can put it under the monster portrait? I think there's a space between the numeral and star for the rarity; if you removed that I think two type icons could fit? (Then again I can't tell if the star is a character or an image with some padding...)

**Comment by madcowfred** [comment]
Added text+icon in the top right - I sure can't identify the types just by the icons.
