### ISSUE TITLE
Multiple Bugs

### ISSUE THREAD

**Issue by Gannonball09** [madcowfred/padherder-issues#273]
Meteor Volcano Dragon, Crystal Aurora Dragon, Tiamat, and Fuma Kotaro do not have the Ultimate Evolutions listed.

Bonefish is still in Japanese even though it has English text now and is listed under Done, even though it still has another evolution to go. 

Hera, when max level, is still showing up under my High priority instead of Done priority even though all I left is the Ultimate Evolution. Siren, Lucifer, and Lilith (for me) are correct, just not Hera.

**Comment by madcowfred** [comment]
Fixed the monster stuff. Hera doesn't show up as Done because she's not ultimate evolved.
