### ISSUE TITLE
Suggestion: Save default filters

### ISSUE THREAD

**Issue by dumdummuoi** [madcowfred/padherder-issues#276]
Would be nice to have the option to make a certain filter persistent when logged in (e.g., maybe I have monsters in the list for team building purposes only, but don't need to see them when I'm viewing the main My Monsters list, so I'd set the default filter to show monsters that are High/Medium/Low priority only).

**Comment by madcowfred** [comment]
Seems reasonable enough, though it will probably be a per-browser setting like the My Sets configuration.

**Comment by madcowfred** [comment]
Added.
