### ISSUE TITLE
Robin still shows up as Copperhead in PADx

### ISSUE THREAD

**Issue by nocutename** [madcowfred/padherder-issues#279]
I am using the PDX Simulator to check out the damage on a Robin team but PADx is still showing Copperhead in the team.  I understand it is a separate website but is it possible for you to sync up the data?

**Comment by madcowfred** [comment]
I hate the BAO collab ID mess so much. Fixed.

**Comment by nocutename** [comment]
Thank you so much!  I love padherder and all your effort is much appreciated.
