### ISSUE TITLE
Pretend teams were max evolved and leveled

### ISSUE THREAD

**Issue by wesdotcool** [madcowfred/padherder-issues#280]
It would be useful if you could look at the stats for a team if the team was max leveled (and maybe evolved). That way I could create teams with my shitty monsters to look at their stats and then decide which monster to level next.

**Comment by kidoblivious** [comment]
I've been thinking about this too, as an easy step I was thinking perhaps you could implement a 2nd PDX Simulator button, with levels set to L Max (I was going to say L99, but people use max L70 things in serious team for serious purposes) please?

**Comment by madcowfred** [comment]
Added a 'Show maxed' button, switches team to max level/evolved (using your chosen evolution) versions. PDX Simulator link is also updated.
