### ISSUE TITLE
Importing Monsters

### ISSUE THREAD

**Issue by PandaNomNoms** [madcowfred/padherder-issues#281]
Would be nice to be able to import monsters using a txtfile containing the JSON data of the monster box directly to the site.

**Comment by madcowfred** [comment]
You can do it using https://github.com/madcowfred/padherder-sync right now, but I do plan on adding support directly into the site at some point.

**Comment by madcowfred** [comment]
Added the ability to import directly on the website, it will also update your Rank/Display name since why not. See 'Import JSON' on the username dropdown.
