### ISSUE TITLE
Suggestion: Rarity in team builder

### ISSUE THREAD

**Issue by dumdummuoi** [madcowfred/padherder-issues#283]
With the scoring feature on legend+ dungeons now taking team rarity into account, it would be nice if we could have monster rarity listed in the team builder, along with either a total rarity or average rarity on the right. This would be useful for those trying to build ghetto teams to earn Tamadra from those S scores..

**Comment by madcowfred** [comment]
I can certainly add the total/average rarity to the totals on the right, not sure where I could put monster rarity with the current layout though - maybe change 'Cost: 35' to '$ 35 | :star: 5' would work?

**Comment by dumdummuoi** [comment]
Yeah, that sounds like a good solution.

**Comment by madcowfred** [comment]
Added.
