### ISSUE TITLE
Incorrect HP Values After Multipliers in Team Simulator

### ISSUE THREAD

**Issue by drob0009** [madcowfred/padherder-issues#284]
The team simulator doesn't appear to give the correct HP values for teams after applying more than one multiplier. For example: http://www.padherder.com/user/marco0009/teams/#30205 displays an HP total of ~13k after multipliers. However if this same team is loaded into PDX the correct HP totals (~23k) after multipliers are displayed.

**Comment by madcowfred** [comment]
Well it would help if you hadn't deleted the team...

**Comment by wshsu314159** [comment]
Do we need sample busted teams?  http://www.padherder.com/user/wishiful/teams/#7151 All of my 4x monogreen teams have their multipliers busted, except for the 9x CuChu and Anubis teams (yay?).

**Comment by drob0009** [comment]
http://www.padherder.com/user/marco0009/teams/#30406
Apologies, was exploring a different bug I have yet to be able to reproduce regarding team creation/editing/deletion.

Here's the original team I posted.

**Comment by madcowfred** [comment]
Should both be fixed.
