### ISSUE TITLE
Suggestion: Skillup Mons

### ISSUE THREAD

**Issue by jarch3r** [madcowfred/padherder-issues#286]
My materials and excess materials are great features, but they are missing one thing for me that would make them excellent. Over time, with all these collab dungeons, I have acquired many skillup mons in my boxes and it would be nice to have a way to track all of these with padherder. Mass entering them all as monsters doesn't really make sense (duplicates...) and there doesn't seem to be an effective way to track them. Perhaps another page similar to my materials for skillup mons, and this would also affect the "excess materials" numbers.

**Comment by kidoblivious** [comment]
I personally do add them, and treat them, as standard mons until the moment they're eaten, when they're deleted. They're tracked the same as any other monster, in the priority you put them... IMO mass entering them as dupes makes complete sense, it is an effective way to track them.

**Comment by jarch3r** [comment]
Thank you for the feedback and mentioning your tracking method. While that may work for you and in small amounts, I disagree that it is an effective method of tracking skillup mons. I have hundreds of skillup mons in my box and entering them all as duplicates just seems sloppy -- it clutters and removes usefulness from listing your own monsters that you actually use.

Imagine a page similar to My Materials that has all the skillup mons instead, and you simply enter a quantity. This method, and yours, would allow the needed evo mats for the skillup mons to be tracked with My Materials and return usefulness to the wonderful Excess Materials feature.

**Comment by keht191** [comment]
I also agree that this would be pretty nice to have since it's too hard to see what skillup dupes you have cluttering up your box quickly without having to trawl through your monster list page.

**Comment by madcowfred** [comment]
I can see the use for this - I currently have a huge pile of weird Evangelion pyramid things and CoC Archers littering my box. There's a few issues that I can see:
- How do I identify skillup mons? It would probably need to be a manual process due to the sheer variety of monsters.
- Continuing from that, what gets included? I have an Isis but I probably don't want to have her (and her evolutions) on my skillups page.

If we can come up with a reasonable way to deal with that I'll implement this.

**Comment by jarch3r** [comment]
Here are my thoughts on the proposed problems. I am happy to go through the database and create a list of IDs for all skillup mons.
1. All the mons IDs would have images/textboxes on the My Skillups page (similar to My Mats). A person could still add a skillup mon to My Monsters for use on a team; that's a seperate feature and would be independent of the mons on the Skillup page.
2. I think (1) mostly addresses this, but nothing would be included automatically. The list of IDs would all need images/counts on the Skillup page. Isis would not be included in the list of IDs but archangelings and fifth angels would.

**Comment by madcowfred** [comment]
Seems reasonable. Next problem: displaying the damn things. It's easy enough to only show boxes for monsters you own, just wondering how to actually display it. My Materials is just a heading with a bunch of monster boxes underneath, this one... well. Some things have several skillup options, I feel that they should be grouped together somehow :|

Box with monster name and icons would be too large for dumb cases like Persephone, Queen of the Really Long Name. Could do something like a horizontal box with your monster/current skill first, then a divider and each skillup mon with a quantity count underneath? These would fit as many as possible in the width of the screen and flow properly.

**Comment by jarch3r** [comment]
Good questions. I originally thought just listing them all, similar to the Materials page, which would be the simplest. Although your idea of seeing only monsters that you own (that aren't max skill) and the current skill level would be really nice (mon name could be on mouseover like my mats).

I like your idea. A left to right flow of "boxes". Each "box" contains the monster to be skilled image with a textbox under for current skill and then followed on the right by a divider and skillup mons with a textbox under for count. This would work with all resolutions and use the whole width. Although it may not look the best, it would provide a lot of space for the necessary content and minimize scrolling.

Edit: Maybe these horizontal boxes could be dragged around (to visually prioritize). This whole thing could also be a tab on the My Materials page rather than a whole new link littering the header bar.

**Comment by madcowfred** [comment]
As far as generating the list goes, I have a mostly working script that does stuff:
- It gets fed a list of monster IDs which needs to be manually generated.
- For each monster ID:
  1. Get all future evolutions of this monster.
  2. Find all monsters with the same Active Skill that aren't a future evolution.
     - Go backwards until the first evolution of this monster without that skill.
  3. Generate a mapping for each evolution to those monsters.

So 492 (Isis) gives the following output:

```
492: [594, 707], # Isis
493: [594, 707], # Water Deity, Holy Isis
996: [594, 707], # Blue Moon Sea Deity, Isis
997: [594, 707], # Shining Sea Deity, Isis
```

... alternately, just think of it as magic. I could probably even automate it entirely and find every possible skillup monster instead of requiring a hard-coded list, that seems like a fun project.

**Comment by madcowfred** [comment]
An early version of this has been added, see 'My Food' on the nav bar. It integrates with My Materials but not yet with dungeon reminders due to other work.

**Comment by madcowfred** [comment]
Now integrates with dungeon reminders too.

**Comment by timcoffman** [comment]
I started using this, and it's great so far!  My question is: is there a way for me to click "Evolve" for my Food monsters in order to consume their Evo materials?

**Comment by jarch3r** [comment]
That's a good question! (I'm assuming you read the news that it is still 'an early version of the feature'.)

**Comment by timcoffman** [comment]
Absolutely! I'm thinking of Pengdra especially- if it had an Evolve button (just like the main Monster list) that would consume the Dragons and Plants/Seeds for me, that would be super helpful.

**Comment by timcoffman** [comment]
Well, either I'm not very observant or you just implemented the feature I was hoping for: Click to Evolve food monsters.  Thanks, great feature!
