### ISSUE TITLE
Top droidragon shows multiple awakens

### ISSUE THREAD

**Issue by sickcat99** [madcowfred/padherder-issues#287]
1. Launch the page
2. Add Top droidragon
3. Observe

The list shows TD has 9 awakens. A lot of which are duplicates.

**Comment by kidoblivious** [comment]
This is the future for Top. (unfortunately for me, I fed one when I noticed it on herder, I should have checked it was out to US by looking at the card! happily i still have one spare to feed...).

**Comment by madcowfred** [comment]
Yeah, this is a random JP change that appears to have snuck in. It's getting to the point where I need separate monsters for JP/EN with the massive lag time on us getting minor updates, though I'll just leave it as is for now.
