### ISSUE TITLE
Dungeon reminder shows I have "undefined" number of evo mats

### ISSUE THREAD

**Issue by Spiridios** [madcowfred/padherder-issues#289]
Today is Tuesday, and I'm seeing the reminder to run keepers. I have never used the My Materials page to track my materials because I'm lazy. When I hover one of the needed keepers (for example, blue), it says "You have undefined Keeper of Water, you need 2 more:" Since I have never entered any materials, I would expect it to say "You have 0 Keepers of Water, you need 2 more". Not sure if it does this for any of the other evo mats.

**Comment by madcowfred** [comment]
Fixed.
