### ISSUE TITLE
[BUG] Top Droidragon has 9 awakenings?

### ISSUE THREAD

**Issue by dr-ishmael** [madcowfred/padherder-issues#291]
As title.  He should have none.

**Comment by nevets1219** [comment]
Top Droiddragon will have nine awakening at some point. See http://www.puzzleanddragonsnews.com/2014/03/01/droid-dragon-awakening-skills-revealed-return-android-collaboration-dungeon

**Comment by dr-ishmael** [comment]
I see, didn't know about that.

**Comment by madcowfred** [comment]
Yeah, I already closed GH-287 but I will leave this open for now and tag it WONTFIX. Hopefully we actually get this in the NA version at some point...

**Comment by madcowfred** [comment]
Ugh, this is taking forever to arrive in NA. I've added some code to override awakenings for these for now.
