### ISSUE TITLE
"done" monsters are no longer done

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#296]
prior to today, monsters that were at max level/evolution were marked as done and showed up at the bottom of my list (as is set in my preferences). today, they're intermingled with the rest of the monsters at the priority they were set at.

**Comment by madcowfred** [comment]
Looks like a side-effect of GH-263, along with some Sets issues. Hitting it with a hammer.

**Comment by ngamber** [comment]
https://i.chzbgr.com/maxW500/2579690752/hCA5AFA92/

**Comment by madcowfred** [comment]
Fixed.
