### ISSUE TITLE
Suggestion: donate button

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#297]
I don't really want to see ads, but I wouldn't mind tossing you a few REM pulls for all the work you've put into this. Any chance of getting a donation button?

**Comment by wpnewborn** [comment]
Just FYI you can turn off ads in the My Account options.

But yes, a donate button would be great to give back to Freddie.

**Comment by ngamber** [comment]
I mean I'm not willing to turn on ads (and disable adblocker) just to give him a few fractions of a cent. I know the option's there, but its presence is part of why I'd like to give back.

**Comment by madcowfred** [comment]
My issues with the donate thing are basically:
- I end up needing to use my real name, or deal with getting a company name/etc.
- I'm not sure I want to deal with people suddenly expecting me to work on their championed issues after a donation. Some (most) days I probably don't feel like working on X (or writing code at all).
- If using Paypal, a single person being a dick and reverseing a charge can cost _me_ $20+ :fire_engine:

**Comment by ngamber** [comment]
Accept bitcoin/dogecoin, ignore over-entitled donators. All problems
solved! ^_^

On Tue, Apr 15, 2014 at 12:25 PM, Freddie notifications@github.com wrote:

> My issues with the donate thing are basically:
> - I end up needing to use my real name, or deal with getting a company
>   name/etc.
> - I'm not sure I want to deal with people suddenly expecting me to
>   work on their championed issues after a donation. Some (most) days I
>   probably don't feel like working on X (or writing code at all).
> - If using Paypal, a single person being a dick and reverseing a
>   charge can cost _me_ $20+ [image: :fire_engine:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/madcowfred/padherder-issues/issues/297#issuecomment-40502809
> .

## 

## Nathan Gamber

231-480-1729
ngamber@gmail.com

**Comment by madcowfred** [comment]
Then I have to deal with the horrors of converting pretend internet currency into real currency instead - annoying! At some point I'll cave and just put a paypal donate button up :cry:
