### ISSUE TITLE
Suggestion: Tabbing to Login and Password

### ISSUE THREAD

**Issue by wpnewborn** [madcowfred/padherder-issues#298]
A very very small quality of life improvement idea.  When I navigate to padherder.com and try to tab to the Username and Password fields from the address bar it takes 9 tabs to get through the body links and top nav bar before I can enter my username and password.  Is there any way to have the first tab after the address bar go to the username field?

**Comment by madcowfred** [comment]
The username field will now be focused after the page loads.
