### ISSUE TITLE
'Show Max Stats' (in 'My Teams') bug

### ISSUE THREAD

**Issue by pknintendodude** [madcowfred/padherder-issues#302]
As I see it:
The feature is meant to max the creature's level based on the final form you specify. However, it erroneously shows the highest level form of the creature if: the creature is the lowest form and you specify it to stay at its lowest form.
Eg 
I have a Naga that I want to Evolve up to Echidna, but no more. Show Max Stats would accurately show the Max Level Echidna.
I also have an Asuka&Eva that I want to stay the same, but Show Max Stats will show the final form on the team builder.

It seems to only affect the first form of any monster, regardless of having an ultimate evo or not. Evolved Forms do not have this problem, they will be accurately displayed when "Show Max Stats" is pressed.
# 

I tested with Amaterasu (all three forms) and Flamie (to see if only ultimate evos were affected).

I tested using three Amaterasu with each point specified as the end result (one stay the same, one to next form, one to ultimate evo form). When I hit "Show Max Stats", the first form goal and ultimate evo goal showed the ultimate evo form, while the next form goal accurately showed next form. I also tested with Ama Ohkami: I had one stay the same and one ultimate evo: both showed accurately.

Similar results were shown with Flamie->King Flamie; Flamie set to evolve to final form and Flamie set to stay the same both show the final form maxed out.

**Comment by madcowfred** [comment]
Thanks for the comprehensive bug report, the maxed code was ignoring the case where target evolution = 0 ('-None-') and using a full evolution instead. Fixed and deployed.
