### ISSUE TITLE
lvl 99 Light Metatron (#641) no longer Done?

### ISSUE THREAD

**Issue by sunglassesmichael** [madcowfred/padherder-issues#303]
;_;

Is this intentional, or just a quirk?

**Comment by zably** [comment]
They released an ultimate evolution for it.

**Comment by sunglassesmichael** [comment]
It could be related to that, I guess, but that evolution has been listed in pad herder since before I hit lvl 99 and she was still shown as Done until shortly before I posted this.

**Comment by zably** [comment]
I meant the ult-evo was released last night.  For the NA version of padherder, "Done" is only for the currently released content in NA, so even though the evo's available in JP will show up, they don't effect the status until they patch the NA server also.  I don't use the JP version, so if that's where you are, ignore me.

**Comment by sunglassesmichael** [comment]
Ah. I see. Thanks. I've only recently maxed any monsters and never encountered this before. Now that you mention it, my JP Sakuya is not Done either for the same reason. 

I guess this can be closed, then.
