### ISSUE TITLE
Max Level Hearts not showing up in "My sets" for certain sets

### ISSUE THREAD

**Issue by zably** [madcowfred/padherder-issues#304]
Some sets do not show the heart icon in "My Sets" even with max levels, while some do.  Toy Dragons, Healer Girls, Heartbreakers, Late Bloomer dragons, and Evangelion REM 1 all show the level as 99 even with the ultimate evolution (instead of the star) and so won't show the heart.  In the Archangels set, Rebel Angel Lucifer (and the previous evo Seraph of Dawn Lucifer) both show 99 instead of a star as well, and effect the heart icon.  Possibly something to do with ultimate evolutions?

**Comment by madcowfred** [comment]
Almost certainly related to the 'alternate ultimate evolution' stuff that got added a few days ago. Looking now.

**Comment by madcowfred** [comment]
Should be fixed now.
