### ISSUE TITLE
[Status] Android app

### ISSUE THREAD

**Issue by madcowfred** [madcowfred/padherder-issues#306]
Hopefully this is slightly less of a drag than the aborted mobile website :disappointed_relieved:

PF thread: http://puzzleanddragonsforum.com/showthread.php?tid=44001
- [x] Start app project! :rocket:
- [ ] Pull monster data from PADherder API and store on device (sqlite?)
  - Manual updates
  - Automatic "you haven't checked the API for a week, do so now?" update reminders
- [ ] Pull image files from PADherder static files and store on device
  - Ask "there are 999.9MiB of images to grab, is that ok?"
  - Use the ? image for missing ones
- [ ] Pull event data from PADherder API regularly - configurable?
### Notifications:
- [ ] Urgent dungeon notifications
  - Filter out dungeons you don't care about?
  - Configurable notification times - 1h/15m/etc.
- [ ] Daily coin/drop/stam things? Option.
- [ ] Push notifications - all need to be optional/require signup
- [ ] Friend chat
- [ ] Friends want a specific leader
- [ ] Group chat
- [ ] Group members want a specific leader
### Materials:
- [ ] Daily dungeon stuff - you need 97 Keeper of Rainbow
- [ ] Update materials?
### Monsters:
- [ ] Retrieve user data from PADherder API
- [ ] Edit monster data
  - Store the new version in a separate database table
- [ ] Easy way to see 'XP to feed'
- [ ] 'Sync to website' button - manual only
  - Offer to merge/overwrite changes?
### Teams:
- [ ] Edit teams?
  - No CRUD API for teams yet
- [ ] Full stats display, including leader calculations
### PADherder website stuff:
- [x] Add image40/60 and image??_href to /api/monsters/
- [ ] Fix friend support so it's less awful
- [ ] Finish (rewrite?) groups so they actually work
- [ ] Add API keys to My Account somewhere
  - Include a QR code for easy adding to mobile?
- [ ] Switch /user-api/ auth over to API keys instead of using username/password
- [ ] Extend /user-api/ somehow to get linked accounts when authenticated
- [ ] Pull/parse dungeon data - drops mostly.
- [ ] Add skillup information to the API somewhere.

**Comment by madcowfred** [comment]
Status update: argjhgjrhgjh.

**Comment by yodamad** [comment]
I've started one on my own, maybe I can help you on this one rather doing it alone.

**Comment by madcowfred** [comment]
I haven't accomplished much yet - I don't really like Java (even after several years of it), and switching back and forth between Python/JS web dev and Java phone dev is painful. What sort of things did you have in mind for your app?

**Comment by yodamad** [comment]
Hi Fred,

thanks for answer. For my part, I planned to do quite the same as the todo
list you published : get account data on phone, access even if offline
(read & update). I'm also using PADGuide application, I was thinking about
contacting this team to see if we can share database (at least for
pictures). I have also read threads about guys who succeeded to update
padherder automatically by reading pad monster box, that can be a good
feature too.

I haven't accomplished much also as I started it 2 weeks ago, but I really
like Java so that can help you ;) but i do not like all JS, CSS and design
things.

2014-05-01 11:19 GMT+02:00 Freddie notifications@github.com:

**Comment by madcowfred** [comment]
I'd be happy to collaborate on something, assuming we can agree on tools (Eclipse-based ADT vs InteliJ-based Android Studio?), where to put the damn thing (github? bitbucket? something else?), and ad/money stuff (I don't want ads and don't particularly care about making money from it).

Reading the monster box on a phone involves weird VPN shenanigans - as far as I know you can't just read the saved PAD monster data due to a) encrypted storage format, and b) requiring root to read another app's data.

**Comment by yodamad** [comment]
Great.
On tools, I've tried both and I prefer Eclipse (but can adapt to Inteli-J),
github seems a good choice as we both already have an account.
On ads/money, i do agree with you !

If all is ok, maybe you can push on github your works and I'll incorporate
what have done after and then we can assign tasks ?

2014-05-06 10:05 GMT+02:00 Freddie notifications@github.com:

**Comment by madcowfred** [comment]
That's probably not a great plan - my thing doesn't do much except set up a database, and I was trying out Android Studio (which is very much beta) so there's all sorts of horrible crap involved. I'll grab a current ADT and start a new blank project of excitement.

**Comment by yodamad** [comment]
Ok for me. Let me know when you push it.
I'll integrate my little part (Webservice call on PADHerder API to retrieve
a user information)

2014-05-06 13:55 GMT+02:00 Freddie notifications@github.com:

**Comment by yodamad** [comment]
Hi Fred,

 finally got time to clone repo.
I see that you use android v7, doesn't a little bit too old and we have to
maintain many old versions for few users ?
http://www.frandroid.com/android/developpement/205889_repartition-versions-android-53-kitkat-fin-mars-2014

As you can see, maintain from 4.0 seems covering most of cases ?

Let me know if your are ok with this, I'll change configuration.

Mat

2014-05-06 13:59 GMT+02:00 Matthieu Vincent mvincent.it@gmail.com:

**Comment by madcowfred** [comment]
Yeah, go ahead and change it to 4.x

**Comment by madcowfred** [comment]
Status update: PADListener makes a large chunk of this irrelevant, yay. The scope of this app can probably be narrowed, and I can hopefully stop being sick and actually put some time into it soon :cow:

**Comment by madcowfred** [comment]
Going to close this for now, Android dev is not even close to an enjoyable hobby.
