### ISSUE TITLE
[Bug] Mobile website and "My Materials"

### ISSUE THREAD

**Issue by Ajhariel** [madcowfred/padherder-issues#308]
1. The "Materials" link at the top of the page on the mobile website takes me to "My Teams" rather than "My Materials".
2. When viewing the "My Materials" page on the mobile website, the materials have no pictures. Attached is a screenshot.
   ![snapshot1](https://cloud.githubusercontent.com/assets/7341023/2745469/b75ec51e-c736-11e3-8920-43afe6c41b9c.png)
3. Probably unimportant, but the URL for "My Materials" on the mobile website is
   http://m.padherder.com/materials/
   whereas the Teams, Monsters, Sets, etc all have "/user/usersnamehere/" between the ".com" and the page name (teams, monsters, sets).
4. Thank you for PaDherder, I use it many times a day!   :+1:

**Comment by madcowfred** [comment]
1. Fixed
2. Fixed.
3. This is by design - the /user/bob/blah/ URLs are shareable (assuming your account is set to public), while /materials/ is only ever for your use since it doesn't really make any sense to show people.
4. :sun_with_face:
