### ISSUE TITLE
Added Monsters to List, but they vanished; Materials unchanged

### ISSUE THREAD

**Issue by Zaeldren** [madcowfred/padherder-issues#31]
As the title says, I added several monsters when I first signed up. After adding them, then going back and changing the xp values on some, I checked the materials page. Upon returning to the monster list, all but Freyr were missing. However, her xp reflected the changes I made after adding all the monsters, and the materials page still show the needed materials to evolve the missing monsters. As an example, I currently have 3 showing monsters, yet the materials list 12 Rainbow Keepers needed for all evos.

**Comment by madcowfred** [comment]
Interesting bug, looks like a duplicate monster appeared in the database and broke some things. Fixed now.
