### ISSUE TITLE
[BUG] Sorting/information updating not working right (my monsters)

### ISSUE THREAD

**Issue by Brocknoth** [madcowfred/padherder-issues#310]
I think this might be a problem on my end since I'm using an older version of Firefox (9.0.1) but whenever I try to use the sorting options under the "my monsters" tab I'm greeted by either a string of undefinedundefinedunfined in the column listings or a "All monsters are hidden by your filter settings!". This same thing happens when I update monster information (level, skill level,+'s, etc).

The only thing that fixes it is to refresh my monster box. The "Filters" tab works just fine. Like I said I think it's something on my end since no one else seems to be having this problem.

**Comment by madcowfred** [comment]
Yeah, definitely works fine in current Firefox (28). Debugging would be extremely painful on such a relatively ancient version - I'm not sure it even had developer tools at that point :|

**Comment by Brocknoth** [comment]
That's what I thought ok I guess I need to update then thank ya Freddie. I forget why I was being stubborn about it. Something about stability...

EDIT - Yeah that fixed it. You can delete this topic now or close it. Sorry for bugging ya. ^_^;
