### ISSUE TITLE
[BUG] Water Courier Ruka has wrong picture.

### ISSUE THREAD

**Issue by Brocknoth** [madcowfred/padherder-issues#311]
Minor bug but ruka's second evo comes up as a red orb or series of red orbs.

**Comment by madcowfred** [comment]
It displays ok on my test version, and your PADherder looks fine too (assuming you are also Brocknoth there). Can you take a screenshot of the issue?

**Comment by Brocknoth** [comment]
Yes I'm Brocknoth on PADherder as well. Here's a collage of the problem. 

http://i5.photobucket.com/albums/y172/Brocknoth/Ruka_zpse873555f.jpg

**Comment by madcowfred** [comment]
Well that is truly bizarre and I definitely can't reproduce. Try forcing a refresh (Ctrl-F5), and if that doesn't work, clear your browser's cache?

**Comment by Brocknoth** [comment]
Wiping my cache fixed it. Sorry for the trouble Freddie.

**Comment by madcowfred** [comment]
It was certainly one of the stranger reported bugs :+1:
