### ISSUE TITLE
Adding Hrungnir to My Sets

### ISSUE THREAD

**Issue by wpnewborn** [madcowfred/padherder-issues#314]
Since this guy was from a cost restricted dungeon similar to Draggie / Gaia / Tengu I was wondering if he deserved to be added to sets either under Descended 4 or Collab Bosses 2?

The monster: http://puzzledragonx.com/en/monster.asp?n=819
The dungeon: http://puzzledragonx.com/en/mission.asp?m=534

**Comment by madcowfred** [comment]
Added to Collab Bosses 2.
