### ISSUE TITLE
Add Materials from the Dungeon Reminder Box

### ISSUE THREAD

**Issue by joehiatt** [madcowfred/padherder-issues#315]
First off, love the tool. Thanks for all your hard work. Im eagerly awaiting the android app and would be happy to beta.

I was hoping you could add the ability to increase the number of materials from the 'Dungeon Reminder' box where it tells you what you need from the daily dungeon. This Friday, for example, I need 2 dubmythlits and nothing else. I run the dungeon, get a dubmythlit and two other monsters. Rather than having to click into the My Materials section, add 1 to the number and save, it would be great if there was a "got one!" button to increment my needed monsters. I sell the rest so no need to increment that!

Thanks again!

**Comment by madcowfred** [comment]
Dupe GH-180. Some day it will be done, honest :(
