### ISSUE TITLE
Preview Monster Stats at Target Level

### ISSUE THREAD

**Issue by kraegar** [madcowfred/padherder-issues#316]
I'd like to see it so when you set a target level for a monster, when you hover over that level, it shows you the stats (including any existing + eggs) for that monster.

For instance, I have a level 60 haku.  I could set the target level to 80, when I hover over that, I could see the stats for my haku at level 80, including any awakenings and + eggs already on it.  This would greatly help in prioritizing where to put XP.

**Comment by madcowfred** [comment]
Seems reasonable enough.

**Comment by madcowfred** [comment]
Added.
