### ISSUE TITLE
Suggestion: Sorting order by rarity

### ISSUE THREAD

**Issue by tonyzha1** [madcowfred/padherder-issues#318]
I noticed this when going through my box to update things. PAD by default sorts in order of favorites (similar to priority), then some other criteria.

Can you make the monster listing sort in a way that mirrors in-game sorting of PAD? I don't know if this would entail layered sorting like PAD does, but it would definitely be nice to be able to change monsters in the same order PAD lists them.

**Comment by madcowfred** [comment]
1. Set PADherder to sort by Box (ATT) or Box (FAV)
2. Set PAD to sort by ATT or FAV
3. Profit

FAV may not match up exactly, it obviously relies on you having all of your favourited monsters in PADherder.
