### ISSUE TITLE
Import JSON function

### ISSUE THREAD

**Issue by Lapan** [madcowfred/padherder-issues#319]
Import JSON doesn't seem to sync awakenings. Just synced after awakening Gold Pirate Dragon twice and it didn't show up.

Also, including baby tamadras in the content it syncs would be nice, considering as they need evo materials

**Comment by madcowfred** [comment]
Fixed the awakenings thing. Baby Tamadra/other annoying evo stuff will be included once GH-286 / GH-193 stuff is done.
