### ISSUE TITLE
Consider none evolution

### ISSUE THREAD

**Issue by jacul** [madcowfred/padherder-issues#32]
Say Gigas, I'd like to max level or skill but rather stay in this form. So I don't want to take his evo materials into account.

And thank you for your great work!

**Comment by kidoblivious** [comment]
Another use case of this is that for one of my 9x balance teams, I like my Dragon Knight, and am never going to evolve him to Ancient Dragon Knight (I got a Mystic Stoner Knight who will be going there though!), so having his evo mats listed hinders me.

**Comment by madcowfred** [comment]
Added, you can now set a monster to '-None-' evolution.
