### ISSUE TITLE
Bug Says I have evo material that's not in inventory

### ISSUE THREAD

**Issue by jayjaybones** [madcowfred/padherder-issues#322]
I went on My Monsters, sorted by FAV, put my cursor on Ox-dub Amelit that I needed for Evolution and it says I have it. It also has that X mark. I didn't input any Ox-dub Amelit since I don't have any. The same thing for Kirin. I don't have Keeper of the Gold. Would be nice to have this feature fixed, so that you can scroll down a visually see which ones are lacking evo material.

**Comment by madcowfred** [comment]
It's not telling you that you have it, it's telling you that you have zero of [monster]. I'll look at making some changes to make it clearer which items you have and don't have.

**Comment by madcowfred** [comment]
I've changed how evolution materials are shown - they're now shown as 'faded' if you're missing the material and gives a slightly more helpful tooltip.
