### ISSUE TITLE
[suggestion] automatically remove materials via my food page

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#323]
It would be nice if I could click something that lets me say I evolved X skill-up monsters (from the my food page) and they were removed from the my materials. Not a huge deal, but it can get tedious keeping everything in sync.

**Comment by madcowfred** [comment]
A few people have asked for this, wasn't really sure where to put it. Best I can come up with is:
- Hover over food icon, evolve icon appears and tooltip says CLICK TO EVOLVE.
- Click, box pops up asking how many, press go.

... and I guess some sort of note at the top of the page explaining that that's how it works.

**Comment by madcowfred** [comment]
Added, visit page and click food.
