### ISSUE TITLE
[bug] image link doesn't show up in team description

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#324]
I have an image link in one of my team's descriptions: 

https://www.padherder.com/user/scrllock/teams/#41636

If I'm simply viewing the team, it doesn't display, but if I hit edit, I can verify that the link is still there. I have tons of youtube links on my other teams, and those all show up fine.

**Comment by madcowfred** [comment]
Links in team descriptions are whitelisted, they only display if they're on the list. I've just added Twitter's image server to the list, you might need to edit/save the team for it to update.

**Comment by ngamber** [comment]
good to know, thanks!
