### ISSUE TITLE
Three Kingdoms Gods are not being added to monster list through bulk add monsters

### ISSUE THREAD

**Issue by sousuizer0** [madcowfred/padherder-issues#325]
Self explanatory. I tried to add my new Guan Yus and Liu Bei through bulk add several times and it didn't work. Had to go over to normal add monsters and that worked though.

**Comment by madcowfred** [comment]
Just tested and it seemed to work fine, what exactly are you putting in the bulk add box?

**Comment by sousuizer0** [comment]
I figured out what I was doing wrong myself, was just putting in ID#Priority without the monster level before priority and there wasn't anything telling me there was anything wrong after I submitted.

**Comment by madcowfred** [comment]
I've improved the way the 'Bulk add monsters' box handles things, it should now correctly show errors if you do 'ID#notanumber'.
