### ISSUE TITLE
Skill lv/food/materials interaction

### ISSUE THREAD

**Issue by raspberrytealeaf** [madcowfred/padherder-issues#327]
I fed my Susanoo a billion leeks and had my leeks entered on the food page so I remembered how many dumb dragon plants/green lanterns/etc I needed. When I maxed his skill and entered it on Padherder, it removed the leeks from my food page. That's a nice feature. However, the food row on the materials tables still accounted for the # of un-evoed leeks I had entered on the food page. To remove them, I had to set Susan's skill to a non-max level, then set the leeks to 0 to make them vanish from the materials page, then go set Susan's skill back to max to make the leeks vanish again from the food page.

**Comment by madcowfred** [comment]
Hm, I hadn't thought about this case - not sure what a reasonable solution is. Possibly an alternate tab on My Food for "All monsters" to include max skill/missing ones?

**Comment by raspberrytealeaf** [comment]
Maybe remove the food from the food and materials tables when the skill is entered as max level unless you have dupes of the monster or another monster w/same skill? :s Idk what would be a great solution.

**Comment by raspberrytealeaf** [comment]
New approach: Perhaps users just need some kind of way to hide food so it doesn't count in the materials list?

**Comment by madcowfred** [comment]
Pushing a 'fix' for this - if you visit My Food and just hit 'Save changes' it will set any food you no longer need to 0.
