### ISSUE TITLE
Enter key to save monster edit

### ISSUE THREAD

**Issue by nihil679** [madcowfred/padherder-issues#329]
Currently, the enter key to save a monster after editing it within your My Monsters page isn't working. I am unsure if it is due to browser or if the feature was altered/removed.

Firefox 29.0

**Comment by madcowfred** [comment]
Looks like it's related to https://bugzilla.mozilla.org/show_bug.cgi?id=935876. The two choices seem to be:
1. Use the 'keypress' event. Works properly on Chrome, doesn't work on FF29, behaves like 2 in IE11.
2. Use the 'keydown' event. Still works properly on Chrome, if you press Enter with a <select> dropdown open on Firefox/IE it will still fire the 'keydown' event.

For now I've gone with 2 so things at least work on every browser. Hopefully at some point Firefox gets a better 'fix' for this bug :(
