### ISSUE TITLE
Ultimate Ranger Santa instead of Low Dark Ninja

### ISSUE THREAD

**Issue by ryuujinzero** [madcowfred/padherder-issues#330]
In the sets page, 533 Ultimate Ranger Santa shows up instead of 553 Low Dark Ninja in the 'Ninjas' set. I figure this was probably just a typo in the monster number.
![31481914f071bc120624c441d5e28f5b](https://cloud.githubusercontent.com/assets/5858306/2871679/b81f409a-d31c-11e3-8d34-abd81b5542f6.png)

**Comment by madcowfred** [comment]
Fixed.
