### ISSUE TITLE
Rendering Bug / Chrome+Linux

### ISSUE THREAD

**Issue by winterspite** [madcowfred/padherder-issues#332]
Monsters without awakening skills appear to have a rendering bug when viewed on Chrome+Linux:

https://i.imgur.com/BaP9SeO.png

This bug does not appear for those with awakening skills, the box renders normally.

**Comment by madcowfred** [comment]
No idea about this one, could be idiotic wrapped behaviour. Just deployed a fix for a different issue, maybe that fixed it?
