### ISSUE TITLE
Super Metals at wrong time or not displaying for Blue starters

### ISSUE THREAD

**Issue by theinfra** [madcowfred/padherder-issues#334]
Today is May/8th and in puzzledragonx show that there's Super Metal Dragons for people with blue starter. It is currently 9pm PST (11 for me) and I'm actually IN the dungeon, but in the events type it shows as "No events" where I would expect to see a "Super Metals for xxxx". I actually remember seeing through the day today that I had the event, and when I entered the site and saw the No Events notice I thought I missed it, thinking that it was 9 pm MY time, but in padx it shows that it's PST which is correct (since I am actually doing the dungeon right now)

Don't know if it's display or the event was mis-scheduled or there's a wrong comparisson with the timezone

**Comment by madcowfred** [comment]
Looks like the PAD wiki front page has the wrong date so it broke events, can't do much about it.
