### ISSUE TITLE
JP Account's mosters are determined max to be evolved even they are not

### ISSUE THREAD

**Issue by Albert-Lo** [madcowfred/padherder-issues#336]
![screen shot 2014-05-11 at 5 53 46 pm](https://cloud.githubusercontent.com/assets/2975977/2940112/017a64aa-d970-11e3-9a69-9ca255016119.png)

![screen shot 2014-05-11 at 5 55 36 pm](https://cloud.githubusercontent.com/assets/2975977/2940115/36770384-d970-11e3-8d7d-45d759096c9b.png)

Basically all monster I have except the ones from PADBT series are determined to be max evolved even they are in their first state of evolution.

**Comment by Albert-Lo** [comment]
An extra observation:
When I change my acct to NA, the other monsters will go back to normal but then the ones from PADBT will have same problem I mentioned. Hope this will help.

**Comment by madcowfred** [comment]
Fixed.
