### ISSUE TITLE
Lilith missing on My Food page/suggestion

### ISSUE THREAD

**Issue by Tygre** [madcowfred/padherder-issues#337]
I have a lower evolved Lilith for low cost teams that isn't max skilled.  The BAO Copperhead monster is a skill up for her, but she's not listed on the food page.

Also, I have skill up monsters that need evolved which I don't have the main monster for.  (Ogres I haven't evolved, but have the fey stuff from the Pal machine, etc) Is there a way to put a manual Add Food option at the bottom for this situation?

**Comment by madcowfred** [comment]
Added.

Not currently, it's on the list once I work out a sane way to do so.
