### ISSUE TITLE
Baby tamadra food count

### ISSUE THREAD

**Issue by raspberrytealeaf** [madcowfred/padherder-issues#341]
Baby Tamadra count doesn't update with json import. (Or at least mine didn't when I last went to update my padherder last night, lol.)

**Comment by madcowfred** [comment]
Import does not currently update food numbers, it will probably end up like:
- Add/update _ONE_ of each monster (highest level) in My Monsters.
- Delete any others from My Monsters.
- Update food with the count of monsters (minus the kept one).

**Comment by madcowfred** [comment]
Added food updating to Import JSON
