### ISSUE TITLE
Seeing yourself while logged in on the find friends results

### ISSUE THREAD

**Issue by raspberrytealeaf** [madcowfred/padherder-issues#342]
Since favorited/friended users show up with hearts on them in the find friends results, I think that a logged in user who sees themselves in the results should also have some kind of marker/color... Like a different background color, or a border color, or maybe the fa-user icon? (Alternatively, text like, "hey retard this is you don't add yourself".)

**Comment by madcowfred** [comment]
Added a star icon.
