### ISSUE TITLE
Wed dungeon, materials in Dungeon Reminder section do not include most light masks

### ISSUE THREAD

**Issue by ts0ng** [madcowfred/padherder-issues#344]
The only Light mask which is showing up is Mystic Mask, but not seeing Divine, Demon, and Evo masks.
![image](https://cloud.githubusercontent.com/assets/7581103/2971109/59e802a8-db66-11e3-853e-87079a28d027.png)

**Comment by Tygre** [comment]
if you don't need the material, it doesn't show up in the reminder...

**Comment by ts0ng** [comment]
I figured that might be the case but I did indeed have an open requirement

**Comment by ts0ng** [comment]
I'll reconfirm on Wed and post screenshots if necessary.

**Comment by ts0ng** [comment]
I guess it won't show if your only needs are low priority(?)  Thanks all.
