### ISSUE TITLE
Dungeon Reminder is not showing all the materials

### ISSUE THREAD

**Issue by dlim87** [madcowfred/padherder-issues#345]
e.g. For today (thursday) it doesn't display the 1 type of trifruit (which I don't have or need) and dragon plants, which I do have multiple needed in all categories other than high, and have a reasonable stockpile of.

Actually, it probably would be helpful to display all of them regardless of whether you need it or not, so you can more easily stockpile them in case you're expecting to get a monster you need later, but don't want to add yet: i.e. a descend boss, or pengdra food

**Comment by Tygre** [comment]
Umm, the reminders are to remind you of materials you need.  If you have enough, or don't need them, it won't remind you of them.  If the priority for the monster that needs them is Low or Zero it still won't show up.  Personally I wouldn't want materials I don't need or want showing up in the reminders, I need to know what I need, not what I don't.  =/

**Comment by madcowfred** [comment]
^ What that person said. Dungeon reminders, by design, exist to remind you about materials you still need for evoing - that's it.
