### ISSUE TITLE
Ultimate Evolution Material Tracking

### ISSUE THREAD

**Issue by TheSmacker** [madcowfred/padherder-issues#346]
It would be great if the materials needed for ultimate evolutions could be displayed in the dungeon reminder. It would be even better if you could specify which evolution you wanted the materials displayed for.

**Comment by Tygre** [comment]
Its already in place.  You need to select which evolution you want from the drop down on the monster's edit line and the materials you need will be added automatically and show up both on the reminders and the My Materials page.  When theres multiple stages of evolution, there will be a > there when you are out of edit.  Click it to see the evolution chain and all the materials needed for it.

**Comment by TheSmacker** [comment]
Ah, I completely missed that it was available to change after you clicked edit. My mistake.
