### ISSUE TITLE
Mousing over the dungeon reminder materials while on the my food page adds the "click to evolve" text on your mats

### ISSUE THREAD

**Issue by raspberrytealeaf** [madcowfred/padherder-issues#349]
As the title says, if you go to your my food page then mouseover the dungeon materials list at the top of the page, it will also have the "click to evolve" msg that the actual food has. (e.g. a dragon seed will have this message.) Not a life threatening error that will cause the apocalypse but it tickles my OCD.

**Comment by madcowfred** [comment]
Fixed.
