### ISSUE TITLE
"sort by day" option for daily dungeon materials

### ISSUE THREAD

**Issue by wmedlar** [madcowfred/padherder-issues#35]
This would make it much easier to see which materials I need and simplify weekly dungeon planning.

**Comment by madcowfred** [comment]
I haven't gotten around to updating some of the My Materials internals for this yet but there is a new feature today to remind you about daily dungeons:
![padherder26](https://f.cloud.github.com/assets/99630/1087772/42e02910-1621-11e3-94b9-1e45542cffcc.png)

**Comment by incrediblehulf** [comment]
Yes, My Materials should be sorted into rows like...
- Keepers
- Masks
- Plants
- Sprites

The uncommon mats can probably be safely left alone. 

Maybe adding something for Pengdra farming (in My Mats, above uncommon mats) would be useful?

**Comment by madcowfred** [comment]
Added 'Group by rarity' and 'Group by dungeon' buttons to My Materials.
