### ISSUE TITLE
I can not access my monsters to modify them

### ISSUE THREAD

**Issue by jchills75** [madcowfred/padherder-issues#350]
I can see them in my sets i can see them for fodder but when I click on my monsters it says that they are blocked by my filters even though i have no filters. this problem happened on 3 different desktops. the irony is that I can see my monsters on my i-phone but you can not edit monsters from this device. thanks for anyones help.

**Comment by madcowfred** [comment]
That sounds 100% like a config issue on your end. If you want to edit on your iphone, go to the dropdown and 'Switch to mobile site', that is sort of usable.
