### ISSUE TITLE
Add the ability to update user information in the API

### ISSUE THREAD

**Issue by Neraud** [madcowfred/padherder-issues#352]
The user API (/user-api/user/[username]/) in only accessible in read.

The materials and monsters sections are already accessible in PUT/ PATCH via dedicated APIs.
It would be helpful to add the ability to PATCH the account information (account_id, country, and the new fields added by issue #351 )

**Comment by madcowfred** [comment]
Working on this now but it requires doing some backend changes that I had been putting off for as long as possible :cry:

**Comment by Neraud** [comment]
That's not a top priority improvement, so I guess you could keep putting it off ;p

But I suppose the mobile app would require this improvement anyway.

**Comment by madcowfred** [comment]
The backend changes were going to break things quite gloriously, instead I went the lazy route:
- /user-api/foo/ no longer has profile things in the base object
- /user-api/foo/ now has a 'profile' object with various profile things
- You can PATCH/PUT to the URL in 'profile'.'href' and update any of the settings

**Comment by Neraud** [comment]
Would it be possible to have the profile id in a dedicated field ?

In PADListener, for my calls to PADherder, I build all the URLs with an endpoint and service relative URLs. Having only a full URL kind of breaks that.

(it's so low priority that I feel like it doesn't need a dedicated issue, but I can open one if you prefer)

**Comment by madcowfred** [comment]
Oops, missed the id field when defining the serializer - added now.
