### ISSUE TITLE
Occasional missing monster images

### ISSUE THREAD

**Issue by omnibon** [madcowfred/padherder-issues#354]
![screen shot 2014-05-28 at 13 41 36](https://cloud.githubusercontent.com/assets/4631122/3104354/f0ebc464-e665-11e3-8b54-bfd560f59b64.png)

Seem to have some images not appearing. Url of image shows something is added to the monster number

**Comment by madcowfred** [comment]
Can't seem to reproduce, try Ctrl-F5? The extra thing in the filename is a hash so static files can be cached for a long time (the filename changes if the file changes).

**Comment by omnibon** [comment]
The two monsters with 'missing' images were always 1067 andromeda and 1075 strawberry dragon. I could reproduce it by adding loads of andromeda/strawberry dragon in the box - but, it seems the problem goes away if I disable all my chrome extensions! Looks like it's just an isolated case; sorry my bad!
