### ISSUE TITLE
Don't see Super Kings available for me to add as material.

### ISSUE THREAD

**Issue by spacemixup** [madcowfred/padherder-issues#359]
Don't see Super Kings available for me to add as material.

**Comment by madcowfred** [comment]
They're definitely there, under "Rarely used materials" when grouped by rarity and "other materials" when grouped by dungeon.

**Comment by spacemixup** [comment]
Grouped by rarity
2nd grouped by dungeon

All super kings show except emerald

**Comment by madcowfred** [comment]
Because emerald kings _are not used for any evolution_. At all. Go look them up on PDX or the Wiki or whatever. The other ones are there because they ARE used in evolutions, which is the whole point of My Materials.

**Comment by spacemixup** [comment]
Ok thanks for the clarification. From a user stand point is there no way to
add mats for things you haven't put into pad herder yet?

**Comment by madcowfred** [comment]
You can always add mats for whatever you like.

**Comment by spacemixup** [comment]
Sorry I think I am misunderstanding you English is not my first language

From your first response you say "

They're definitely there, under "Rarely used materials" when grouped by
rarity and "other materials" when grouped by dungeon.
—" - then you say they aren't there because they're not used for any
evolutions.

Which tab should I be looking at to see super emerald kings to add the
quantity I have??

**Comment by madcowfred** [comment]
1. My Materials is for tracking materials used to _evolve monsters_.
2. Super King Emerald Dragons are _not used to evolve any monster in the 
   game right now_.

1 + 2 = there is no reason to keep track of how many Super King Emerald 
Dragons you have.

I initially thought you meant super kings in general - the others are 
listed because they are _used in evolutions_ (Ultimate Hera/Zeus, for 
instance).

**Comment by spacemixup** [comment]
Ah okay thank for clarification.

I was hoping the tracking for super kings so I could know how many I need
to use to max a monster without needing to use pdx to do the math each time
by manually plugging in its exp and level.

cheers.

**Comment by madcowfred** [comment]
If you hover over the "Pengdra" column on the My Monsters page, it pops 
up a thing that shows how many Kings/Super Kings you need to max a monster.

**Comment by spacemixup** [comment]
very cool thank you.
