### ISSUE TITLE
Clicking save while editing monsters triggers an uncaught TypeError

### ISSUE THREAD

**Issue by Reinboom** [madcowfred/padherder-issues#361]
- OS: Windows 7
- Browser: Chrome 34.0.1847.131 m
- Error: Uncaught TypeError: Cannot read property 'level_at_xp' of undefined

Whenever I edit a monster and hit save or enter, I get the above error within chrome console. The visual update never confirms a save. Reloading the page confirms that the save did occur however.
This occurs within padherder.min.js

**Comment by madcowfred** [comment]
I broke some stuff, should be ok now.
