### ISSUE TITLE
Unable to update manually

### ISSUE THREAD

**Issue by pdxmarcos** [madcowfred/padherder-issues#363]
![padherderbug6-9-2014](https://cloud.githubusercontent.com/assets/6752419/3219736/da8c00fc-eff8-11e3-99e8-0bbefad4ad8a.PNG)

Receiving this error everytime I attempt to update padherder manually.  I have recently started using the android padlistener app.

username: pdxmarcos

**Comment by madcowfred** [comment]
Using what browser/OS?

**Comment by pdxmarcos** [comment]
O/S: Windows XP Professional SP 3
Chrome Version 35.0.1916.114 m

**Comment by madcowfred** [comment]
Not sure, try popping open the JS console (Ctrl-Shift-J) and see if any errors appear in the console? I don't see your browser even trying to edit the monster which is odd.

**Comment by pdxmarcos** [comment]
PATCH https://www.padherder.com/user-api/monster/1014372/ net::ERR_EMPTY_RESPONSE

libs.min.2a9e87ac27da.js:3

**Comment by madcowfred** [comment]
I have no idea, heh - that is definitely not showing up on the server log, so I'm assuming a browser issue. Try closing/reopening the tab, or restarting the browser?

**Comment by pdxmarcos** [comment]
Closed the tab/re-opened and restarted the browser to the same effect.  Could this be as a result of being behind a work firewall?

**Comment by madcowfred** [comment]
Entirely possible if you have a poorly configured proxy that doesn't support all HTTP verbs - PUT/PATCH/DELETE :(

**Comment by pdxmarcos** [comment]
It seems likely that it is on my end because I can update on my phone through the android chrome browser.

**Comment by madcowfred** [comment]
I've just made a change to use PUT instead of PATCH, apparently PATCH was 'only' added in Mar 2010. Let me know if editing a monster works now.

**Comment by pdxmarcos** [comment]
I get back to the office on Thursday and I'll test it then, thanks!

**Comment by pdxmarcos** [comment]
It appears to work!
