### ISSUE TITLE
daily dungeon reminder not showing up

### ISSUE THREAD

**Issue by W2T3** [madcowfred/padherder-issues#364]
My daily dungeon reminders no longer show up.  They worked as of about a week ago.  I've selected the option in my account info, but despite missing Keeper of Rainbow and Keeper of Flame, I don't get a dungeon reminder.  Fwiw, I've updated Chrome, deleted cookies, and refreshed and re-logged in a couple times.  Screenshots:

![padherder1](https://cloud.githubusercontent.com/assets/7852463/3235429/a4a05d64-f0d2-11e3-8049-2f52601e71fe.jpg)
![padherder2](https://cloud.githubusercontent.com/assets/7852463/3235430/a4a110ec-f0d2-11e3-86dd-62792e18d124.jpg)

**Comment by madcowfred** [comment]
Fixed.
