### ISSUE TITLE
Unable to Edit After Double-Clicking on an expanded Ult. Evo Line

### ISSUE THREAD

**Issue by FaxCelestis** [madcowfred/padherder-issues#366]
Image: clicking at point where arrow is triggers the bug.

Refreshing the page fixes the issue. Win 7, Chrome 35.0.1916.114 m

![bug](https://cloud.githubusercontent.com/assets/7397366/3271652/c347877c-f30e-11e3-998a-215f643e69b1.png)

**Comment by madcowfred** [comment]
This bug has existed for ages, surprised nobody has found it until now :sheep: This is fixed in the beta branch but I'm not sure when I'll be ready to deploy it. Don't double click there for now!

**Comment by FaxCelestis** [comment]
I'm not sure if I'm prone to finding obscure bugs or if my experience as a bug tester is rearing its ugly head, lol.

**Comment by madcowfred** [comment]
Err, this isn't actually fixed on live, apparently Github is a bit weird.
