### ISSUE TITLE
no upcoming events found

### ISSUE THREAD

**Issue by W2T3** [madcowfred/padherder-issues#367]
Was working yesterday, but no upcoming events found today, where there should be pengdra village and dragon plant infestation.  I'm in group B, so it should be 2PM pengdra village, 7PM dragon plant, 12AM village again.

Screenshot:
http://i.imgur.com/yfk84WP.jpg

**Comment by madcowfred** [comment]
Looks like the PAD Wiki has no event data, hrm.

**Comment by madcowfred** [comment]
http://pad.wikia.com/wiki/User_blog:Myskaros/Lack_of_urgent_dungeon_times - apparently Clessasaur has disappeared :cry: I'll hit some things with a hammer and see about getting times from PDX instead.

**Comment by madcowfred** [comment]
Aaand seems like the wiki is back. Which is good because PDX is annoying.
