### ISSUE TITLE
Ult Evos showing level 1 stats in mouseover

### ISSUE THREAD

**Issue by FaxCelestis** [madcowfred/padherder-issues#369]
Pic related.

Refreshing page does not fix the problem.

Win 7, Chrome 35.0.1916.114 m

![bug2](https://cloud.githubusercontent.com/assets/7397366/3293145/869aeb76-f597-11e3-94ee-6fb9d75dedff.png)

**Comment by madcowfred** [comment]
Probably a side effect of the dodgy "show popovers for evolution chains too" change, seeing if I can make that whole chunk of code more robust.
