### ISSUE TITLE
When setting a monster as Zero priority, it doesnt show up on the My Sets page when using Share Url

### ISSUE THREAD

**Issue by pazurururu** [madcowfred/padherder-issues#37]
I'd like to show that I have these useless dragons to my friends!

THanks.

**Comment by madcowfred** [comment]
This is actually a stupid default, click the username dropdown top right -> My Account -> minimum priority. Leaving this issue here to remind me to change the damn thing to default to Zero :hamster:

**Comment by madcowfred** [comment]
Ok, the default for this has been changed to 'Zero' since it's a constant source of confusion.
