### ISSUE TITLE
Latest JP monsters

### ISSUE THREAD

**Issue by wmedlar** [madcowfred/padherder-issues#370]
Any plans to add the latest JP monsters, like the Haku and Beelz ultimates, or are you waiting for them to drop stateside?

**Comment by madcowfred** [comment]
They'll go in with the next update, just waiting on beta testers to do some actual testing :-1:

**Comment by wmedlar** [comment]
Ah, excellent. Thanks for all the hard work. Hope I'm not abusing the API too much.
