### ISSUE TITLE
No way to close add/edit dialog box in My Sets

### ISSUE THREAD

**Issue by incrediblehulf** [madcowfred/padherder-issues#373]
![screen shot 2014-06-19 at 4 35 09 pm](https://cloud.githubusercontent.com/assets/5452676/3328706/36ea6ad2-f7bf-11e3-9ade-5d4ab1e29672.png)

Still broken after fix. Cache, cookies, etc. were cleared before screenshot was taken. Esc key and clicking outside of box do not work, either.

**Comment by incrediblehulf** [comment]
If it's helpful, my browser is the current version of Chrome.

**Comment by madcowfred** [comment]
Oh, that box. The only way to close it right now is to click the monster icon you originally clicked. It could prooobably use a close button.

**Comment by madcowfred** [comment]
Well now it has a close button.
