### ISSUE TITLE
Can you bring back the old cell-editing system? Or make the new popup structure optional?

### ISSUE THREAD

**Issue by asakasamo** [madcowfred/padherder-issues#376]
I strongly prefer the old cell-editing system, where you could double-click the cells and edit them directly. It was so much more convenient, and didn't require the extra effort of having to look for the stat you're trying to edit in the popup.

That being said, I love Padherder to death and would like to thank you for this beautiful creation.

**Comment by madcowfred** [comment]
It's pretty unlikely - the inline editing requires a huge amount of code, becomes less useful when columns are hidden, and tended to be rather flaky. If you double-click in a cell that stat _should_ be selected in the popup, you should still be able to go:
- double click +HP
- press up, or type 2, or whatever
- press enter

and be done. If that's not working ittttt's a bug.

**Comment by asakasamo** [comment]
I guess it's not as bad as I made it out to be. I'll just have to get used to it, lol. One thing, though - could you make it so that double-clicking the "need xp" column focuses the "curr xp" box in the popup? As far as I know, PAD doesn't give you the "need xp" value, only your current xp, so that's the one you would be able to enter. (I have a feeling you knew this already, because the original inline editing required you to enter your current xp value.)

**Comment by madcowfred** [comment]
There was actually an old bug about that: GH-233. You can only get current XP via Power Up Fusion, while you can get level+xp-to-next-level via monster info/etc. Not sure what a reasonable default is, maybe it needs to be a preference somewhere :(

**Comment by FaxCelestis** [comment]
Related: the new window doesn't play well with adding monsters on Safari under iOS 7. Not sure if it's limited to iOS or if it's mobile in general.

**Comment by madcowfred** [comment]
@FaxCelestis could you make a new bug with some more info and screenshots?

**Comment by FaxCelestis** [comment]
Absolutely, I'll put something up to today.

**Comment by FaxCelestis** [comment]
Done: GH-382.
