### ISSUE TITLE
Squid materials show up in My Materials when it is not in My Food

### ISSUE THREAD

**Issue by prittyglue** [madcowfred/padherder-issues#377]
I deleted my squids from my monster box as well after I finished max skilling my Artemis; however, my materials still show me needing 100+ dragon flower to evolve all my supposedly deleted squids.

**Comment by madcowfred** [comment]
On 21/06/2014 11:20 PM, prittyglue wrote:

> I deleted my squids from my monster box as well after I finished max
> skilling my Artemis; however, my materials still show me needing 100+
> dragon flower to evolve all my supposedly deleted squids.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/madcowfred/padherder-issues/issues/377.

Try going to My Food and just hitting the 'Save' button down the bottom, 
that might fix it. Not sure how to communicate that to people :(

**Comment by prittyglue** [comment]
Right that worked. Thanks for the fast reply!
