### ISSUE TITLE
Troouble with piccolo (1403)

### ISSUE THREAD

**Issue by chalumeau-zz** [madcowfred/padherder-issues#378]
I have a trouble with piccolo (monster 1403), I can create the monster, but when I edit its level, the level always remains at LV1. Do you think there could eb a bug about that ?

Thank you for all the work you make for us !

**Comment by madcowfred** [comment]
Looks like the new DBZ collab monsters have a 3.5Million XP curve, added that and it seems to work now.

**Comment by chalumeau-zz** [comment]
OK, great, thank you very much ! it’s a good news the curve is “only” 3,5M.  

Benoit Hautefeuille

AXINT SAS, Président

5, rue de la Claire, 69009 LYON

Tel 06 29 85 94 53

De : Freddie [mailto:notifications@github.com] 
Envoyé : mercredi 25 juin 2014 14:35
À : madcowfred/padherder-issues
Cc : chalumeau
Objet : Re: [padherder-issues] Troouble with piccolo (1403) (#378)

Looks like the new DBZ collab monsters have a 3.5Million XP curve, added that and it seems to work now.
