### ISSUE TITLE
food mats for max skilled monsters

### ISSUE THREAD

**Issue by adubs09** [madcowfred/padherder-issues#379]
When I have a food number greater than 0 for a monster in the food tab, and I skill up the monster to max slvl, the monster disappears from the food tab, but the required number of mats still shows up in the materials section and on the daily reminders. To remove the reminder and the required mats needed, I need to decrease the skill level of my monster to make the monster show up on the foods tab again, remove the amount of food i have, and then reset the monster slvl to max.

**Comment by madcowfred** [comment]
You can just go to My Food and hit 'Save changes' (without making any) to force an update. I'm going to leave this open so I come up with a better solution since that one sucks.

**Comment by madcowfred** [comment]
This should be fixed now.
