### ISSUE TITLE
Cannot make further changes once monster is at max level

### ISSUE THREAD

**Issue by nocutename** [madcowfred/padherder-issues#381]
I wanted to add some +eggs to a monster that is currently at max level.  They system will not allow editing on any of my max leveled monsters.  Is it designed that way?  If so let me know and I will in the future leave them at 98.

Thanks for a resourceful and wonderful tool

**Comment by madcowfred** [comment]
Err, it shouldn't be doing that, and I can't reproduce it. What monster? Where are you editing it?

**Comment by nocutename** [comment]
Freddy, it seems to be working now.  Sorry for opening an issue for this item.  I wanted to change Artemis.  She was able to change and then I looked at my other maxed out monsters.  The few I have, I could not change them as well.

**Comment by madcowfred** [comment]
If you work out how to reproduce it let me know.
