### ISSUE TITLE
Blazing Dragonfire Angel, Uriel Leader Ability

### ISSUE THREAD

**Issue by discomethod** [madcowfred/padherder-issues#386]
The calculation involving Blazing Dragonfire Angel, Uriel's leader ability is not working. I tried this by setting Blazing Dragonfire Angel as my friend's leader and looked at the stats for my mono fire team. The 2x HP, 1.35x ATK, and 2x RCV for fire monsters are all not working.

**Comment by madcowfred** [comment]
Fixed.
