### ISSUE TITLE
Reduce possible alternate evolutions

### ISSUE THREAD

**Issue by w1drose** [madcowfred/padherder-issues#387]
Title is confusing, so I'll give an example here. 

I have a DD Tiamat and a DB Tiamat. I would like the text for alternate evolutions to say only 3 alternate evolutions needed, since I have two already. Right now, both of them say 4 possible alternative evolutions.

**Comment by madcowfred** [comment]
This would be rather a pain to implement :\ You could just turn off the alternate evolution display (it's in My Account... somewhere) if that works for you?

**Comment by w1drose** [comment]
Oh... I had no idea that was possible haha. Thanks!

What about changing My Sets to reflect branching Uvos (if we have both)? For example, the late bloomers can have a drop down button detailing all of their uvos? 

Sorry, I'm just a huge collectionist haha :)

You're doing great! I can also make this a separate issue if you would like!

**Comment by MichealRein** [comment]
I'd like Sets to have the different Ogre ults.

**Comment by madcowfred** [comment]
Closing this issue in favour of #408, please create a new one for My Sets and branching ults.
