### ISSUE TITLE
Lakshmi 7* (#1114) not apply multiplier 1,5x to healers in "My teams"

### ISSUE THREAD

**Issue by SilverDrakon** [madcowfred/padherder-issues#388]
Heavenly Fortune Goddess, Lakshmi (#1114) leader skill - Water & Healer Type Monsters HP x1.5, ATK 1.5, RCV x1.5.
But in 'My teams', if Lakshmi is leader - i not see multiplier from her on other healers in team.

**Comment by madcowfred** [comment]
Fixed.
