### ISSUE TITLE
Suggestion: Priority Done

### ISSUE THREAD

**Issue by FarmerJoeh** [madcowfred/padherder-issues#389]
Is it possible to set the "Done" priority yourself? Currently raising up multiple low cost monsters which are done, but still have 2 possible evo's (which I don't want to give them) but they do not show up as Done.

Or, have done be assigned when there's no further evolution selected? (This is all under the assumption that the final Evo determines the Done or not.)

**Comment by novas0x2a** [comment]
Related, in things like the dungeon reminders it tells me to collect mats to de-ult an "Ice Samurai Ogre" into a "Samurai Ogre" even though I'm unlikely to want to do that; being able to mark evolutions as "not useful" or "not gonna do that" would solve that problem.

**Comment by FaxCelestis** [comment]
I'm pretty sure it's only doing that, @novas0x2a , because you have it listed as wanting to uvo into the Wood Samurai Ogre.

**Comment by madcowfred** [comment]
It used to honour the "no evolution selected" case, apparently it broke a while back. Fixed.
