### ISSUE TITLE
Divinegon Ultimate Evolutions

### ISSUE THREAD

**Issue by fkbsar** [madcowfred/padherder-issues#391]
This is something that you might already be working on but Divinegon now has 5 ultimate evolutions but there is only one listed.  I know everything takes time.  Thank you for your hard work and this program has saved me a lot of flipping back and forth and trying to remember what is needed for an evolution.

**Comment by madcowfred** [comment]
Er, I can see all 5, not sure where you're looking.

**Comment by fkbsar** [comment]
Maybe its my resolution but I can only see the Red Shining. Sorry for the
bother. I will check on my end.

**Comment by madcowfred** [comment]
Hm, I checked on my phone (Android, system browser) and it seems to display ok. Do you happen to use iPhone/Safari? There's another bug reported where the bottom of the add/edit monster dialog gets chopped off.

**Comment by fkbsar** [comment]
Actually I'm using a desktop to access padherder. When I hit "expand
evolutions" they all expanded down except that one and vampire that Ive
noticed. On vampire I don't see the Arcane Monarch.

**Comment by madcowfred** [comment]
Expanding evolutions just expands the 'chain' for the final evolution you have chosen - it doesn't show the alternate ones by design.

**Comment by fkbsar** [comment]
Ahhhh.  Thank you for you time and patience in explaining this. I really do
appreciate your software.
