### ISSUE TITLE
AddMonster Bar Disappears

### ISSUE THREAD

**Issue by smauggy** [madcowfred/padherder-issues#394]
I use Opera 20. The Add Monster button is there as the page is loading but once it's done the Metal Dragon Alert drops down and covers it.
![bug1](https://cloud.githubusercontent.com/assets/8163278/3578605/d3a28f52-0bac-11e4-86ac-6ec85d1d98bf.JPG)
![bug2](https://cloud.githubusercontent.com/assets/8163278/3578606/d54a3bac-0bac-11e4-95a5-330a9798c587.JPG)

**Comment by madcowfred** [comment]
I've made some changes to the navbar to try and fix this, let me know if it's any better.

**Comment by smauggy** [comment]
Yep, that fixed it. Thanks so much :D
