### ISSUE TITLE
Haku 7* (#1268) not apply multiplier 3,5x to team ATK in "My teams"

### ISSUE THREAD

**Issue by SilverDrakon** [madcowfred/padherder-issues#396]
Lunar Corona Byakko, Haku (#1268) leader skill -    3.5x ATK when attacking with any three of following Orb types: Fire, Water, Dark or Heal.
But in 'My teams', if Haku is leader - i not see multiplier from her on other members in team.

**Comment by madcowfred** [comment]
Should be fixed now.
