### ISSUE TITLE
New odin evo auto deleted with padlistener, batman evo missing

### ISSUE THREAD

**Issue by Dalamar6** [madcowfred/padherder-issues#397]
Please fix.

To clarify: I think you have the odin in the api listener pulls data from, but since the name is japanese on padherder it gets excluded since padlistener and japanese aren't getting along too well?

**Comment by madcowfred** [comment]
Not sure why PADListener would be deleting it, it definitely isn't comparing the names.

**Comment by Dalamar6** [comment]
It was fixed when you changed godin to english and added the batman evo.

**Comment by madcowfred** [comment]
Ah. PADListener probably deletes monsters marked JP only, might be something to raise with Neraud.
