### ISSUE TITLE
BAO Copperhead showing as BAO Robin

### ISSUE THREAD

**Issue by jhaelyn** [madcowfred/padherder-issues#399]
I was adding a BAO Copperhead via the Bulk Add Monsters. I typed in "928" and on the side, it showed BAO Robin. If I press enter, it enters it into my moster as BAO Robin. I saw there were several issues previously regarding to the BAO Copperhead/Robin, but they were all previously fixed.

Thanks!

**Comment by jhaelyn** [comment]
Also, I ran into the same problem when I tried to add 930 - BAO Bane, it's trying to add it as BAO Batman+S. Gloves. And 677 for BAO Batman+Batarang is getting added as カグヤ - http://www.puzzledragonx.com/en/monster.asp?n=677

**Comment by madcowfred** [comment]
Dupe #252. Also fixed.
