### ISSUE TITLE
Events API is wrong

### ISSUE THREAD

**Issue by tamadra** [madcowfred/padherder-issues#400]
Right now showing: 

[{"starts_at":"2014-07-24T15:00:00Z","country":2,"title":"Dungeon of Gold Dragons","group_name":"A"},{"starts_at":"2014-07-24T16:00:00Z","country":2,"title":"Dungeon of Gold Dragons","group_name":"C"},{"starts_at":"2014-07-24T17:00:00Z","country":2,"title":"Dungeon of Gold Dragons","group_name":"D"},{"starts_at":"2014-07-24T18:00:00Z","country":2,"title":"Dungeon of Gold Dragons","group_name":"E"},{"starts_at":"2014-07-24T19:00:00Z","country":2,"title":"Dungeon of Gold Dragons","group_name":"B"},{"starts_at":"2014-07-24T23:00:00Z","country":2,"title":"Super Gold Dragons Descended","group_name":"C"},{"starts_at":"2014-07-25T01:00:00Z","country":2,"title":"Super Gold Dragons Descended","group_name":"D"},{"starts_at":"2014-07-25T01:00:00Z","country":2,"title":"Super Gold Dragons Descended","group_name":"D"},{"starts_at":"2014-07-25T03:00:00Z","country":2,"title":"Super Gold Dragons Descended","group_name":"E"},{"starts_at":"2014-07-25T05:00:00Z","country":2,"title":"Super Gold Dragons Descended","group_name":"B"}]

Notice that group D shows up twice for the "Super Gold Dragons Descended" and that the times are wrong, compared to PDX

**Comment by madcowfred** [comment]
Should be fixed now.

**Comment by tamadra** [comment]
Now, it's still inconsistent with PDX and PAD wikia:

{"starts_at":"2014-07-25T16:00:00Z","country":2,"title":"Dungeon of Ruby Dragons","group_name":"C"},{"starts_at":"2014-07-25T17:30:00Z","country":2,"title":"Dungeon of Ruby Dragons","group_name":"D"},{"starts_at":"2014-07-25T19:00:00Z","country":2,"title":"Dungeon of Ruby Dragons","group_name":"B"},{"starts_at":"2014-07-25T20:30:00Z","country":2,"title":"Dungeon of Ruby Dragons","group_name":"A"},{"starts_at":"2014-07-25T22:00:00Z","country":2,"title":"Dungeon of Ruby Dragons","group_name":"E"},{"starts_at":"2014-07-26T00:00:00Z","country":2,"title":"Dungeon of Ruby Dragons","group_name":"C"},{"starts_at":"2014-07-26T01:30:00Z","country":2,"title":"Dungeon of Ruby Dragons","group_name":"D"},{"starts_at":"2014-07-26T03:00:00Z","country":2,"title":"Dungeon of Ruby Dragons","group_name":"B"},{"starts_at":"2014-07-26T04:30:00Z","country":2,"title":"Dungeon of Ruby Dragons","group_name":"A"},{"starts_at":"2014-07-26T06:00:00Z","country":2,"title":"Dungeon of Ruby Dragons","group_name":"E"}

No Super Rubies at all. Can I ask where the source of your events data is? Or is there a crowdsourced source that we can help update?

Thanks.

**Comment by madcowfred** [comment]
Oh, it didn't support multiple events per time slot. That's probably fixed now.

**Comment by tamadra** [comment]
Thanks
