### ISSUE TITLE
Updating Monsters from "My Teams"; Identifying Duplicates

### ISSUE THREAD

**Issue by alewares** [madcowfred/padherder-issues#402]
Hey, this is a suggestion for two quality of life changes.
1. Updating Monsters from "My Teams"
   Frequently, users that don't use automated updating tools will find priority in updating monsters that are on their main teams. It would be convenient to have an edit button like in "My Monsters" in the "My Teams" tab, allowing one to quickly find their core monsters and keep them up to date without the hassle of scrolling through their box. I understand that Priority is a way to also increase update efficiency, but this would be a step above that. Personally, I find that when I am focusing on a specific team, that I have to go through my "High Priority" category to find every member of it separately.
2. Identifying Duplicates
   If you have several monsters of the same level and name, the Team Editor will display them all exactly the same. Having a +egg, Awakening, or other way to differentiate between them when duplicates show up on the Team Editor would help with easier creation of teams. For instance, you may want your +297 to be the leader rather than the +30. Adding duplicates at the moment is a bit annoying. If you have, for example, 3 Red Sonias, the way it works now is unintuitive. Here are some user steps that lead to unexpected results:

a. Under Sub 1, you search a word to find all your Red Sonias. You click the first one.
b. Under Sub 2, you search a word to find all your Red Sonias. You click the second one.
c. Under Sub 3, you search a word to find all your Red Sonias. You click the third one.

One would think this yields the three monsters separately, but this is not the case. What this actually does is just put one specific Red Sonia three times - in my case this resulted in 3 +297 Red Sonias (I only have one).

EDIT: After some testing, selecting team members from the search function will always yield three of the same one - it doesn't matter if you click 1 2 3, 3 3 3, or 2 1 2 for instance. The only proper way to add duplicates now would be to scroll through the list, find each one, and hope that the one you clicked is the right one (there is still no way to differentiate between different +'s).

As you can see, these quality of life changes address inconveniences in the UI that would yield great usability. Thank you for your time!

**Comment by madcowfred** [comment]
Added some more info to the search results
