### ISSUE TITLE
Suggestion: Hyper-Maxed Stats (+297, fully awoken)

### ISSUE THREAD

**Issue by wzhang125** [madcowfred/padherder-issues#403]
Under My Teams, we can see what our team looks like at max evolution and max levels. How about including the option to see them at max +eggs and max awakenings as well?

**Comment by madcowfred** [comment]
The awakening thing was added for #405, not sure that adding a separate button just for +297 is a worthwhile use of time.

**Comment by mccool37** [comment]
I think they mean when clicking the 'Show Max Stats' button it should also display the monster's stats as if they had full +eggs.

**Comment by wzhang125** [comment]
I mean having a separate button as people would still want to see max level stats without +297. I suppose it comes down to how difficult it would actually be for you to implement it since I'm sure there are others out there who would appreciate this feature. 

I'm personally interested in seeing teams at +297 because it gives a hard upper bound for the team's potential. I'm currently running a 2/4/2 mono-green team as my main team, and while I'm working on switching to a spike lead (Kirin), I'm curious as to what my green team could and could not do at +297.

**Comment by madcowfred** [comment]
This has now (finally) been added - "Show maxed stats" --> "Show maxed +297 stats" --> "Show normal stats".
