### ISSUE TITLE
Suggestion: "Pending" priority

### ISSUE THREAD

**Issue by magusonline** [madcowfred/padherder-issues#408]
Creating another Priority group called, "Pending". For those who acqiure new monsters from their box frequently (maybe especially during those fests, etc).

I already use the High -> Zero priority a lot. But adding automatically through PADListener sometimes throws my rhythm off. But if there was another category called "Pending" or something that could be added, then I could suggest to Neraud to do the same thing and add another group to his program (or do it myself as he's left the source open I believe) for his "Created monsters" function on his app.

Thanks again for listening and considering. I hope it comes through!

**Comment by madcowfred** [comment]
Adding a new priority is a little non-trivial due to internal stuff, I probably do need to actually fix that though. This "Pending" priority would be skipped for materials because I hate touching that code.

**Comment by madcowfred** [comment]
Linking to newer one since nobody checks past the first page of issues - #490 .
