### ISSUE TITLE
Removing Food Items

### ISSUE THREAD

**Issue by m4rkstorch** [madcowfred/padherder-issues#409]
I noticed an issue with the implementation of the My Food feature.
I was working on skilling up my Haku and had hoarded 21 chasers.  I evolved 3 and updated my account here.  When I max skilled her, she disappeared from the list on the My Food tab so I had to go back and bump her skill down so that I could erase the extra masks an lits that were showing up as needed on the food row of the Materials page.  I don't have a good solution other than to just zero the food when you max skill something but I wanted to make sure you were aware of the required workaround as it seems a bit counterintuitive.

**Comment by madcowfred** [comment]
You can just save the My Food page and it will fix itself, but yes this needs to be fixed properly without that hack. Dupe #379.
