### ISSUE TITLE
Underlord Arch Hades is also devil

### ISSUE THREAD

**Issue by jacul** [madcowfred/padherder-issues#41]
Now he is God only.

**Comment by madcowfred** [comment]
Fixed.

**Comment by jacul** [comment]
Still the same, Could you please check? Thanks.

**Comment by jacul** [comment]
And Fertility Deity Holy Ceres is also healer.

**Comment by madcowfred** [comment]
Really fixed this time, I forgot a step. Also updated the entire set of ultimate Old Greeks since none of them had their second type.
