### ISSUE TITLE
Lakshmi skill needs updating

### ISSUE THREAD

**Issue by jonrmitchell** [madcowfred/padherder-issues#410]
Lakshmi's skill does 20x damage now instead of 10x.

Here's the facebook announcement, you may want to go through and check that you got the other skill tweaks from the same time too:

https://www.facebook.com/notes/puzzle-dragons-north-america-gungho/new-monster-updates/878530518842208

**Comment by madcowfred** [comment]
Looks like my data updating tools stopped working, they have been beaten with a stick and things should now be mostly up to date.
