### ISSUE TITLE
Show all possible skillups on "My Food" (Siren, the Demons, the Ninjas, others)

### ISSUE THREAD

**Issue by novas0x2a** [madcowfred/padherder-issues#414]
You mentioned doing this in #286 ("I could probably even automate it entirely and find every possible skillup monster instead of requiring a hard-coded list, that seems like a fun project.")

Just consider this a vote for doing so! I'd be a :smile_cat: The inv management required to get a single demon to level 26 is kinda nuts. :sweat:

Thanks!

**Comment by madcowfred** [comment]
My Food is specifically designed to track monsters with food that requires evolution. Siren/Devils/etc can be trivially skilled up via drops so they're not really suitable for it.
