### ISSUE TITLE
Suggestion-Work with puzzledragonx

### ISSUE THREAD

**Issue by mccool37** [madcowfred/padherder-issues#416]
I'm not sure how you might work this out but I believe both sites could benefit if you two "combined" somehow. Their site provides information on the dungeons and a full schedule list of what's going to come out on what day, different events, godfests, etc as well as more detailed information on the different monsters (you already link there when clicking on monster profiles). However, their monster collection sucks (I only update it because I think more people search for friends using their system so it helps).
This is where Padherder could come in. The site is fairly easy to use and allows for a simple way to add monsters, figure out how much material you need vs how much you have, evolve your monsters deal with food, etc. 
If both sites worked together so that, for example, when searching for a friend with a monster you would like, rather than searching their site it redirected to yours and searched the Padherder database as if one had use the Padherder Find Friend tab (this is just an idea, I'm not sure how it would actually be worked out). You already direct traffic to their site so perhaps they could return the favor and get rid of their crappy system in the process.

**Comment by madcowfred** [comment]
Seems like this is pretty unlikely to happen :\
