### ISSUE TITLE
My Teams pages are bugged (funky display)

### ISSUE THREAD

**Issue by nickjrlover** [madcowfred/padherder-issues#418]
I think I'm doing this right? Not sure if I am; sorry if I'm not D:

The Teams pages (for my teams and others' teams) are acting strange. It only looks normal if all five groups are expanded and the first four have at least one team each. Or if you expand the groups in order from top to bottom. (Also, the first team in each group seems to have this indent before the leader's picture; not sure if that's intended or not.)

![mine_fullyexpanded_noproblembutindented](https://cloud.githubusercontent.com/assets/8418385/3878633/e357848c-2170-11e4-8dda-005503070833.PNG)
Looks fine since all groups are expanded and the first four groups have teams in them. (And there's that indent I mentioned.)

![mine_fourthgroupempty](https://cloud.githubusercontent.com/assets/8418385/3878664/1f295bb6-2171-11e4-9b57-294e2eb76ec3.PNG)
But when I emptied the fourth group, this happened... (I put the teams at the bottom back into the fourth group for the screenshots below)

![mine_oneclosed](https://cloud.githubusercontent.com/assets/8418385/3878632/e356111a-2170-11e4-89ad-f2783f78a85f.PNG)
I closed one group and this happened.

![mine_twoclosed](https://cloud.githubusercontent.com/assets/8418385/3878635/e359bff4-2170-11e4-8a7f-8db9f294d564.PNG)
Got worse when I closed two.

![mine_threeclosed](https://cloud.githubusercontent.com/assets/8418385/3878634/e357fffc-2170-11e4-907d-13939875d141.PNG)
I closed three, and now it looks like a mess.

![mine_allclosed](https://cloud.githubusercontent.com/assets/8418385/3878698/9dc6bacc-2171-11e4-8209-ea6f64b45f20.PNG)
And then this happened when I closed all groups on my page.

So I looked at someone else's teams, and...

![notmine_staircase](https://cloud.githubusercontent.com/assets/8418385/3878638/e36850d2-2170-11e4-9c4a-f87aa9b977fd.PNG)
?? I don't remember it lining up like that.

![notmine_bigindent](https://cloud.githubusercontent.com/assets/8418385/3878637/e363b2de-2170-11e4-8c1d-0c6214cc66aa.PNG)
I opened one of the groups, and there's that big indent.

![notmine_evenbiggerindent](https://cloud.githubusercontent.com/assets/8418385/3878636/e35fc1c4-2170-11e4-8fcf-a84252ddec81.PNG)
The indent got worse when I opened the lower team groups.

The pages looked fine for the first month or so that I used padherder on my laptop; they only started acting up recently, maybe within the last week or two weeks. Not sure how recently this started happening due to limited internet on my laptop.

Using Firefox 30.0 and Windows 7.

**Comment by madcowfred** [comment]
I can't reproduce this but I've made a minor adjustment that may help.

**Comment by nickjrlover** [comment]
No dice, sadly; other users' team pages still behave the same way, and My Teams behaves slightly differently but still looks like a mess when I start closing groups.

Thanks for the effort ^_^ I appreciate your work. Been trying to figure out why the display is like this on my laptop but not on my phone (when I use desktop mode on it) or other computers, but I haven't figured it out quite yet. For now, it's thankfully not too much of a hassle since all teams are automatically open on My Teams (and they therefore don't look like a mess when I enter the page).

Hopefully this can be fixed eventually since I'm a bit of an archivist and will probably end up scrolling through like 500 teams one day haha I'll post another reply if I figure out the cause of this.

**Comment by madcowfred** [comment]
I can reproduce this in IE whatever-I-have-installed, and I've applied some very minor changes that seem to fix it in that case. Let me know if that helps.

**Comment by nickjrlover** [comment]
It worked! :D Now it's behaving correctly; none of the stuff I mentioned is happening now. Thank you!
