### ISSUE TITLE
black fairies don't show up in my food

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#419]
I have three pandoras at various priorities, but none of them show up in the My Food section.

**Comment by ngamber** [comment]
neither do centaurs, it seems.

**Comment by ngamber** [comment]
and minotaurs, too.

**Comment by jonrmitchell** [comment]
and Blue Chasers? My Karin is max lvl (=done status) if that makes a difference.

**Comment by madcowfred** [comment]
Should all be fixed.
