### ISSUE TITLE
The ability to add to "My monsters" from the set screen

### ISSUE THREAD

**Issue by Randuin** [madcowfred/padherder-issues#42]
This would make it really easy for a new user to populate their monster list

**Comment by TyrAlduin** [comment]
First off PADherder is now one of my favorite pass times when I am bored and waiting for Stam. I have recently been getting a few of my friends interested in PAD and they are slowly adopting PADherder as well. 

It seems it has been a few months so maybe there wasnt enough interest? But, If there was a way to click on the monster pictures in sets and have an option to be sent to the PDX site or simply add a level 1 version of the monster to your list that would be awesome!

**Comment by keht191** [comment]
Bulk Add was fixed recently to show additions more quickly but I also agree that this would be a lot faster as well.

**Comment by madcowfred** [comment]
Added (finally).
