### ISSUE TITLE
Problem with team add

### ISSUE THREAD

**Issue by dms1485** [madcowfred/padherder-issues#421]
Hi, nub here. Love the app! I can add one team no problem; but when I try to add a second team, the "adding team" circles endlessly.  If I logout and log back in, it will let me add one team again. Please advise and thanks for your patience with this old lady. Donna

**Comment by madcowfred** [comment]
Hi! Adding multiple teams seems to work for me, what web browser (Chrome, Firefox, Internet Explorer, Safari, something weird) and operating system (Windows, OS X, something weird) are you using?
