### ISSUE TITLE
PADherder UX is nonexistent without JS

### ISSUE THREAD

**Issue by Llammissar** [madcowfred/padherder-issues#422]
I get that Javascript really enhances a lot of things, and I don't mind enabling it for when it's needed, but it's really jarring to come to a page that displays almost nothing without it.  To some degree, PADherder is a spreadsheet, so a limited fallback that just displays static data would honestly be nice (e.g. on my mobile, where CPU time is at an extreme premium or my laptop where the site kind of chugs and I just want to see how much XP I need for skill fodder).

**Comment by madcowfred** [comment]
It's 2014, JS is pretty much A Thing and I'm not interested in duplicating a pile of code.
