### ISSUE TITLE
Team Export to PDX Simulator Incorrect Awakening/Plus Eggs

### ISSUE THREAD

**Issue by discomethod** [madcowfred/padherder-issues#424]
As an example, I've tried exporting a simulation of my maxed Mono Fire team (https://www.padherder.com/user/discomethod/teams/#5531;maxed) via the "PDX Simulator" button.

However, there appears to be something wrong with the URL parameters, because my Cao Cao shows up with +4 eggs when I really have +0 eggs. Additionally, there are no Awakening skills even though all of them are activated in a maxed team.

My guess is the Awakening level number is in the +egg spot.

**Comment by discomethod** [comment]
On second thought, it could be that PDX is doing that thing where it automatically replaces your team builder monsters with the monsters in your collection if you're logged in.

**Comment by madcowfred** [comment]
Fixed.
