### ISSUE TITLE
youtube links in team descriptions are no longer whitelisted

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#425]
I have an extensive video index using the team feature, and now have to copy and paste each link. you mentioned having a whitelist when I asked for twitter images to show up as links, was removing youtube from the whitelist intentional?

**Comment by madcowfred** [comment]
Casualty of the API changes, I'll look into reimplementing it as part of the client side code.

**Comment by madcowfred** [comment]
Fixed. The first youtube link a description will also now be embedded because why not.

**Comment by ngamber** [comment]
Awesome! thanks

On Sat, Sep 6, 2014 at 9:50 AM, Freddie notifications@github.com wrote:

> Fixed. The first youtube link a description will also now be embedded
> because why not.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/madcowfred/padherder-issues/issues/425#issuecomment-54712748
> .

## 

## Nathan Gamber

231-480-1729
ngamber@gmail.com
