### ISSUE TITLE
Materials counting can set to -1

### ISSUE THREAD

**Issue by Chrammer** [madcowfred/padherder-issues#426]
The Materials counting, the number you currently have, can set to a negative scale, which wouldn't be an issue, - normally...

But it screws with the layout and showing of the materials showed in the evolutions tab at "my monsters".

For every number under 0 it shows the material one time more, 
for example (to envolving Monster: Siegfried, the Blue Champion; Material: Keeper of Rainbow):

Material - Keeper of Rainbow: '- 1'
Materials shown which are needed to envolve Siegfried: "Keeper of Rainbow: '2' "

On top it screws with the layout of Padherder, due to using 1.5 rows instead of just 1.
It needs one space more than normally, so it trys to allign the needed materials.
For example on top: (Keeper of Rainbow is now KoR)
                                               Blue-sapphilite, Dragon Fruit, Mystic Mask, KoR, KoR
Siegfried, the Blue Champion:
                                                Dub-mythlit,

---

I think these bug only occurs with PADListener. It can set the value of the Materials to negative.

I tried to set the value to a negative one on my own, but that didn't work.

---

I would say it's just a small bug, because only newer player will be confused to have more than 5 Materials to envolve a monster. And it just screws a bit with the layout.

It could be a problem with monster that just need 1-4 materials to envolve, because more matierials are shown.

---

Dunno if there's a fix for you or the developer of PADListener has to fix it.

Hopefully I could help to improve and get your really great App bug-free.

**Comment by madcowfred** [comment]
PADListener bug, I've changed the API to clamp values to the range 0-100 now.
