### ISSUE TITLE
Materials stuck on "Loading Data..."

### ISSUE THREAD

**Issue by apritchard** [madcowfred/padherder-issues#429]
My 2nd padherder account cannot display the My Materials page correctly.  It shows "Loading data..." with a spinning circle next to it right under the "Grouped by rarity" tab and above the "Save changes" button.  On the My Monsters page, my monsters correctly display their requirements and indicate whether they are filled, but I get no helper box at the top telling me which of my material requirements are met by the daily dungeon.

I updated this account using PadListener for Android, so I don't know if that caused the problem, but I appear to have no way to edit my materials at all now.

**Comment by madcowfred** [comment]
This is a PADListener bug where it sets materials to negative values. This is no longer possible (it will set to 0 instead) and I've fixed the database, your second account should work now.
