### ISSUE TITLE
Suggestion: Change default sort for monster list

### ISSUE THREAD

**Issue by putty174** [madcowfred/padherder-issues#431]
Simplest solution would be to make the current Default - Ascending sort selection the default one. Why would monsters I don't want to do anything to appear at the top?

Probably best sort order would be High > Mid > Low > Zero > Done

**Comment by madcowfred** [comment]
It.. is the default? There's also an option in My Account to move 'Done' monsters to the bottom.

**Comment by putty174** [comment]
Ahh, didn't find that section of the account settings. But still, having it preset to Default - Descending was unusual for me. You can close this issue if you want.

**Comment by madcowfred** [comment]
New accounts definitely defaulting to Default - Ascending, dunno.
