### ISSUE TITLE
My hades is confused

### ISSUE THREAD

**Issue by OhNoBananas** [madcowfred/padherder-issues#432]
![hades](https://cloud.githubusercontent.com/assets/8020388/4090204/8314dbac-2f7a-11e4-8740-ad9854b45523.png)

Its saying my Light Uvo'ed Hades has a max level of 50...It seems confused.

**Comment by madcowfred** [comment]
That isn't max level, it's the level you're targeting - just edit the monster and set the Target to Max. This is a PADListener bug with how it creates monsters, I'll annoy Neraud to fix it.
