### ISSUE TITLE
Favorite Team Star Not Toggling

### ISSUE THREAD

**Issue by wpnewborn** [madcowfred/padherder-issues#435]
If I want to unfavorite a team if I click the gold star nothing happens.  Instead, I have to edit team, uncheck the favorite box, and then the star goes back to white.  Expected behavior would be for the star to be toggled with just a click.

**Comment by madcowfred** [comment]
What OS/browser? Seems fine here on Win7 with latest Chrome and Firefox.

**Comment by wpnewborn** [comment]
Hmm, I think it might be related to an outdated version of Chrome.  On my desktop it works fine (OSX 10.9.3, Chrome 37.0.2062.94) but on my laptop it does not (OSX 10.8.2, Chrome 24.0.1312.57).  Had the same problem on my laptop when using Safari 6.0.2 but no problems with Firefox (17.0.1)

**Comment by madcowfred** [comment]
Not messing around with old browsers.
