### ISSUE TITLE
Mephisto, new JP monsters/info

### ISSUE THREAD

**Issue by blvcksvn** [madcowfred/padherder-issues#436]
Just a few things I'd like to mention: In "Sets", Mephistopheles should be in [Descended 5] rather than [Dragon Swordsman].
Data for monster skills are not updated (Durga, Hera Ur, DW Loki)
If it's not too much trouble, could you add some of the new cards? Specifically Joan of Arc and Mulan from the Dragon Knights series and Kanetsugu from the Descended 5 series? I'd like to be able to keep track of them and make teams.
Links for convenience:
http://www.puzzledragonx.com/en/monster.asp?n=1365
http://www.puzzledragonx.com/en/monster.asp?n=1364
http://www.puzzledragonx.com/en/mission.asp?m=799

**Comment by madcowfred** [comment]
Should all be done.
