### ISSUE TITLE
Bug: "Shinji&Kaworu&Unit-13, FI" Active Skill: Outdated

### ISSUE THREAD

**Issue by kapowshazam** [madcowfred/padherder-issues#439]
the new active is:  Attacker type cards ATK x3.5 when HP is less than 99%.

references: 1) puzzledragonx.com > http://www.puzzledragonx.com/en/monster.asp?n=1201
                   2) I have the monster myself and I can vouch that Reference 1's information is correct.

**Comment by madcowfred** [comment]
This was confusing until I realised you meant the leader skill. Fixed.
