### ISSUE TITLE
Can we have an option to erase all monsters/info and start from scratch?

### ISSUE THREAD

**Issue by ghost** [madcowfred/padherder-issues#441]
Useful when starting new accounts and/or just completely resyncing.

**Comment by blvcksvn** [comment]
It might be easier to make a new account and link it to your current one. You can use the same email.

**Comment by ghost** [comment]
A new PADherder account? But the I still have the old account with all the
monster listings I don't need/want, correct?

**Comment by blvcksvn** [comment]
Yeah. Just log out, register a new one and you can go back and forth if you want via the dropdown menu once you link accounts. I have 3 connected for my JP/US/US alt accounts.

**Comment by ghost** [comment]
The point is that I'd just want to completely clear my existing PADherder
account. I don't need/want the data.

**Comment by madcowfred** [comment]
Added a new 'Reset account' option on the username dropdown.

**Comment by ghost** [comment]
Thanks! I just tried this out and it works great. :)

**Comment by ghost** [comment]
I just noticed -- using this option doesn't reset the team group names even though it deletes the teams.
