### ISSUE TITLE
Please show current owned monster count on the materials screen.

### ISSUE THREAD

**Issue by ghost** [madcowfred/padherder-issues#443]
It would make it much easier to manually adjust materials.

For example, if there are six Metal Dragons in the monster list, the materials screen should also show "I: 6" (Inventory: 6) or something so that you know how many you actually have.

**Comment by madcowfred** [comment]
Materials such as metal dragons don't belong in your monster list - they only need to be there if you plan to use them in a team.

**Comment by ghost** [comment]
I think the user should be given the option whether to put the monsters on
the monster list (after all, they ARE monsters) for whatever reason. If
materials really do NOT belong on the monster list, then they should not be
allowed on there at all.

**Comment by madcowfred** [comment]
You can have them on there, I just have no interest in messing with materials code to support it.
