### ISSUE TITLE
Ultimate evolution exp. gain incorrect

### ISSUE THREAD

**Issue by mccool37** [madcowfred/padherder-issues#445]
It is quite nice how the ultimate evolution will automatically level up the monster for you when done. The issue is that sometimes the gain is off (always less). I'm not sure where the issue is here but if I had to guess, the ultimate evolution system doesn't account for the 50% exp gain for same element monsters, It's not a big issue, just something I though I would bring up.

**Comment by madcowfred** [comment]
Fixed.
