### ISSUE TITLE
Differentiate between ultimate and normal evolutions

### ISSUE THREAD

**Issue by colblitz** [madcowfred/padherder-issues#45]
Maybe a "sort by", or a visual indication (cell borders?)

(also not sure if there's a differentiation in the data, but it probably wouldn't take long to go through by hand and mark them?)

**Comment by madcowfred** [comment]
The ultimate evolutions are all flagged as such, would just need some reasonable way to display them. I shall think on it :dog:

**Comment by kidoblivious** [comment]
(I didn't want to open a new issue just to report a tiny thing, and thought this was a good place to report)

When I mouse over my Flamedragon M's evo image, its tooltip says 'Normal Evo' when it's an Ulti evo

TY, that is all

**Comment by madcowfred** [comment]
Derp, that should be fixed momentarily. Also closing this issue since I apparently implemented it.
