### ISSUE TITLE
Tooltip is broken for expanded evolutions

### ISSUE THREAD

**Issue by andyzaft** [madcowfred/padherder-issues#451]
Unless this is intentional, but it used to work that the tooltip on expanded evolution icons would show the full information of the critter the cursor hovers over. Now it just shows number and name. This occurs in Firefox 32 and Chrome 37.0.2062.120, both on Win7.

**Comment by pknintendodude** [comment]
Additionally, clicking on the expanded evolution icon will not take you to the padx page.

**Comment by madcowfred** [comment]
Fixed.
