### ISSUE TITLE
Monster box empty

### ISSUE THREAD

**Issue by ghost** [madcowfred/padherder-issues#452]
My monster box is empty. Each time i add a monster, it shows up until i go to another page, and then disapears when i come back to the monster page. Says 'O monsters shown" and "all monsters are hidden by your filter settings" whereas i don't have any filter set.
Same thing when i open the "Shameful collection". Monsters don't show up. 
no problems with My sets etc...
What shall i do ?

**Comment by madcowfred** [comment]
Errr no idea. Browser/OS? Are you behind some sort of weird proxy server?

**Comment by ghost** [comment]
browser is IE9, OS is Windows 7. It works on Firefox but not IE...

2014-09-19 9:53 GMT-04:00 Freddie notifications@github.com:

**Comment by madcowfred** [comment]
Not sure, I don't ever test with IE since it is a pox upon humanity. Things appear to work in IE10 right now, might be time to upgrade or use a better browser :v:
