### ISSUE TITLE
Just an Aesthetic Suggestion to Improve Readability/Usability

### ISSUE THREAD

**Issue by mezmerie** [madcowfred/padherder-issues#46]
Hi. First of all, I love PADherder! I just discovered it last week. 

There are a couple of things that I think would make it easier (for me at least) to edit and organize monsters... (and might be easy to implement to boot!)
1. Feel free to ignore this suggestion if there are other reasons for the way it is or if you think it wouldn't be a popular change ... everyone has their own preference. But I have a very large, wide screen and the "Note" column is very wide and distracting ... I'd prefer to have all the relevant information clustered together on the left and the "Note" column on the extreme right. (Especially since that column is probably not always used... on mine it's completely empty.)
2. You know how you have slightly bolder row borders separating the monsters by priority? I love that. If you could do the same thing with column borders, visually clumping HP, ATK, and RCV together, and Level and Target together, and Skill isolated, it would be less confusing for me when updating my monsters late at night after having a few drinks!

Anyway, these are just suggestions and thanks for a great application!

Stephanie

**Comment by madcowfred** [comment]
Implemented and live.

**Comment by mezmerie** [comment]
Wow, that was fast! Thanks! I wonder if people will complain about having the Note column moved ...
