### ISSUE TITLE
add shinra bansho skillups to My Food

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#463]
please.

**Comment by madcowfred** [comment]
Probably added.

**Comment by ngamber** [comment]
astaroth skillups show up as BAO Bane, and Baal skillups show up as BAO Grundy, FYI.

**Comment by madcowfred** [comment]
Oh right, this is where that GODDAMN BAO COLLAB broke IDs between JP and US versions. Will just have to wait for the slow wiki to update monster info.
