### ISSUE TITLE
Some UVOs aren't associated with their Skill Up fodder in "My Food"

### ISSUE THREAD

**Issue by sunglassesmichael** [madcowfred/padherder-issues#464]
I'm sure this list is not comprehensive, since my Monster Book has lots of gaps, but here are some I'm sure about:

D/R Demon Lucifer: Sixth Angel
D/D Demon Lucifer: Sixth Angel (Not positive about this one, but likely)
G/G Freyja: CoC Goblin, HxH mob
D/B Loki: Dumpty
Sticker Girl UVOs
G/D Bastet (not positive, but likely)

**Comment by madcowfred** [comment]
Loki doesn't have food because ECO Dumpty drops with the skill, same with Bastet -> Deviling. The other stuff should be fixed.

**Comment by sunglassesmichael** [comment]
Oops. Sorry. You're right. I thought about that with the Pirate mobs, but forgot about Dumpty and Deviling.
