### ISSUE TITLE
Urgent dungeon alerts show for the wrong times

### ISSUE THREAD

**Issue by sunglassesmichael** [madcowfred/padherder-issues#465]
We had a period where urgent dungeon alerts weren't showing at all and since they've come back the times have been off.

I thought it might be a Daylight Savings issue, because up until today they were always one hour off, but today I had one that was 90 minutes off.....?

**Comment by sunglassesmichael** [comment]
I live in Japan where we don't observe Daylight Savings Time.

**Comment by madcowfred** [comment]
Are times wrong for NA or JP urgent dungeons?

**Comment by wpnewborn** [comment]
Hi freddie,

I'm having this issue too right now.  I'm group E NA, and Padherder says super metals 1 hour after they came and went.

**Comment by sunglassesmichael** [comment]
Sorry it was NA. The email that notified me of your response was a victim of the spam filter.

**Comment by madcowfred** [comment]
Applied a temp fix for this, it will probably break again in a week when some of the US goes on DST. Tiemzones suck.
