### ISSUE TITLE
Streamlining editing a monster?

### ISSUE THREAD

**Issue by bleeben** [madcowfred/padherder-issues#47]
Instead of having to click on the edit button for a particular monster, perhaps also having the option to double-click (or some other action) on the particular field you want to edit (for example, so that I can double click on Kenshin's level, type in the new value, press enter, taking away the UI time of mousing between the edit button and the level textbox)

**Comment by madcowfred** [comment]
Added, double click a cell to edit that monster - if it contains an input/select box it will be focused.
