### ISSUE TITLE
My level max Awoken Hera-Ur isn't correctly displaying as maxed on the My Sets page.

### ISSUE THREAD

**Issue by wpnewborn** [madcowfred/padherder-issues#472]
I just maxed my Awoken Hera-Ur and instead of getting a star on the My Sets page she is displaying as level 99.  Also, the tooltip on the left says 2/5 max level instead of 3/5.  Same with 2/5 max awoken instead of 3/5.

https://www.padherder.com/user/newborn/sets/

**Comment by madcowfred** [comment]
That would be because she's not actually at her max evolution (dancing queeeeen).
