### ISSUE TITLE
Lu Bu Display Problem

### ISSUE THREAD

**Issue by Lapan** [madcowfred/padherder-issues#477]
Padherder believes my evolved Lu Bu is done at level 50, see screenshot
![lubu](https://cloud.githubusercontent.com/assets/5336032/4716083/c9205c30-5904-11e4-8433-aadc12f1450c.png)

**Comment by samulilin** [comment]
That's because your target level is 50. Change that to 99, and it should work fine.

**Comment by Lapan** [comment]
Thanks, no idea how or when that happened, or that you even could set that to other levels
