### ISSUE TITLE
AB Bluebird Blues Awoken Skills need updated

### ISSUE THREAD

**Issue by FlipperInJapan** [madcowfred/padherder-issues#478]
Apparently there has been an upgrade to #951 AB Bluebird Blues, and it now has 2 awoken skills. I only realized when I fused another one for a skill up and it awoke on me :)

**Comment by madcowfred** [comment]
Fixed.

**Comment by FlipperInJapan** [comment]
Thanks Freddie. I just wanted to say that you've done (still doing) an
amazing thing with this website! I've only been playing this game for a few
months, and I can't imagine playing it with your website. The few times
that the gateway to your website went down, I felt like I was unable to
play the game because I couldn't update my PADHerder account. Anyway, good
luck on your finals and again, Thank you so much for keeping this site
going for us!!!
sincerely,
Paul
