### ISSUE TITLE
Devil Fish & Romantic Cathy skill descriptions

### ISSUE THREAD

**Issue by Tito151** [madcowfred/padherder-issues#483]
Devil Fish's active skill description is set to Beelzebub's Yoroshiku description, but in game, it still has the original skill description of less health, more damage plus 1.5x dark damage enhance (I hope this isn't changing!).
Romantic Cathy's Leader skill shows an expression error; Unrecognized punctuation character "{".

**Comment by madcowfred** [comment]
Fixed
