### ISSUE TITLE
Supergirl active skill needs updating

### ISSUE THREAD

**Issue by mccool37** [madcowfred/padherder-issues#492]
Description for the skill says, "(999 Turns, 999-999) Unknown- Needs Data Update"
Skill is as follows:
Effects:    Change left-most column into Light orbs and the right-most column into Water orbs.
Cool Down:  12 Turns ( 8 min )
Max Levels: 5

Copied from PuzzleDragonX

**Comment by madcowfred** [comment]
Fixed
