### ISSUE TITLE
Monsters with different IDs in NA and JP mixed up

### ISSUE THREAD

**Issue by Neraud** [madcowfred/padherder-issues#495]
Since last update, some monsters are being mixed up.
For example if you look at [my set](https://www.padherder.com/user/Neraud/sets/), you'll see my BAO Batman with the correct icon, but identified as "#677 US. BAO Deathstoke" and with a lvl 58 (max should be 50).

The issue is the same in PADListener after updating the monster info from your API.

Looking at the output of the monsters API, it seems that the monsters with different IDs in JP and NA are incorrect.
In the old JSON (you can take a look at the [one bundled in PADListener](https://raw.githubusercontent.com/Neraud/PADListener/master/PADListenerApp/src/main/assets/monsters.json)), I can see a correct Batman : 

```
{
    "name": "BAO Batman+Batarang",
    "image60_href": "/static/img/monsters/60x60/932.e1c82cd34b16.png",
    "id": 932,
    "image40_href": "/static/img/monsters/40x40/932.fed9b6d39204.png",
    "name_jp": "BAB\u30fb\u8759\u8760\u4fe0\uff0b\u8759\u8760\u93e2",
    "pdx_id": 9320,
    "us_id": 677,
    [BATMAN STATS]
}
```

In the new JSON, Batman has been replaced by a duplicated Deathstoke.
It still has Batman's ids, images and jp_name, but it's name and stats are from Deathstoke.

```
{
    "name": "BAO Deathstroke",
    "image60_href": "/static/img/monsters/60x60/932.e1c82cd34b16.png",
    "id": 932,
    "image40_href": "/static/img/monsters/40x40/932.fed9b6d39204.png",
    "name_jp": "BAB\u30fb\u8759\u8760\u4fe0\uff0b\u8759\u8760\u93e2",
    "pdx_id": 9320,
    "us_id": 677,
    [DEATHSTOKE STATS]
}
```

**Comment by madcowfred** [comment]
I think this is fixed now, what a mess.

**Comment by Neraud** [comment]
Seems indeed fixed : PADherder displays correct information, and updating the monster information from the API in PADListener fixes the sync issues.

Thanks for the quick fix !
