### ISSUE TITLE
Wrong Monster IDs - Padlistener sync problems

### ISSUE THREAD

**Issue by Lapan** [madcowfred/padherder-issues#500]
The following Monsters can't get synced by padlistener, presumably thanks to wrong ids in padherder:
- Goddess of Secrets, Kali
- Bonfire Fox, Mitsuki (seems to work again)

Adding more to the list if i come across more

**Comment by JamesCID** [comment]
Adding  Zhang Fei  (1424, 1425) and D Kali  (1588, 1589) are equally bugged

**Comment by madcowfred** [comment]
Those should all be fixed now.
