### ISSUE TITLE
Phantom God Odin/Tamadra leader skill issues

### ISSUE THREAD

**Issue by mccool37** [madcowfred/padherder-issues#502]
Phantom God Odin's leader skill displays as doing 2x attack despite being 2.5x. In the team menu, the damage calculator displays correctly (using the 2.5x) though.
As for the Tamadra version, while this one will display the correct number (2x) on the team page it multiplies as 2.5x.

**Comment by madcowfred** [comment]
That could be very annoying to fix as they're the exact same leader skill name with different effects, ugh :(

**Comment by madcowfred** [comment]
Now that I have the ability to fix this it's no longer relevant, boo.
