### ISSUE TITLE
Suggestion: filter By Awoken skill 

### ISSUE THREAD

**Issue by ybouzekri** [madcowfred/padherder-issues#503]
Hi,
I would to tell you first that I love your site it is very helpful.
My suggestion is as the title says, i would like to be able to filter monsters by their awoken skill,
like i want to filter all monsters that have Fir Row Enhance and such...

I'm desperately searching for this feature and I would very much appreciate it.

Regards

**Comment by madcowfred** [comment]
Dupe #458.
