### ISSUE TITLE
[DATA] Monsters incorrectly flagged jp_only (ex : Light Kali)

### ISSUE THREAD

**Issue by Neraud** [madcowfred/padherder-issues#504]
Some monsters have been added to NA, but are still flagged are jp_only.

For example : 1585 (Goddess of Secrets, Kali) and 1586 (Shining Goddess of Secrets, Kali).

Being flagged jp_only and not having an us_id messes with PADListener.

**Comment by madcowfred** [comment]
Fixed those two, let me know if there are any more.
