### ISSUE TITLE
Ult Evo for Mechdragons Hadar & Canopus Not working

### ISSUE THREAD

**Issue by FlipperInJapan** [madcowfred/padherder-issues#507]
The materials for these 2 mechdragons are not showing up for the Ult Evo. I have the other mechdragons in my pad herder, but the material says I have none.

**Comment by madcowfred** [comment]
They won't show up unless you specifically add them in My Materials. You can just click the 'Evolve' icon to evolve them anyway, it doesn't actually require the box to be green.

**Comment by FlipperInJapan** [comment]
Fred, the Mechdragons were in My Materials, but they were greyed out, and when you mouse over them it says none in inventory even though they were in My Materials. I didn't know that you could force them to evolve even without the materials, so that is good to know. I just added the evolved form to My Monsters, and deleted the evolve materials out of the PADherder, so not a big deal. I just wanted to let you know it wasn't working properly. FYI, I just tested it again to make sure with a new Hadar and the other Mechdragons needed for the evolve are still greyed out, even though they are in the inventory in My Materials.

v/r,
Paul

**Comment by madcowfred** [comment]
Hm, that's very odd then, I'll investigate tomorrow.

**Comment by madcowfred** [comment]
Just tested and everything seems to work. Could you check to see if I accidentally managed to fix this?

**Comment by FlipperInJapan** [comment]
Hmm. Still isn't working on mine. Maybe is it just a problem for me. I
added #287 Annihilate Mechdragon, Hadar to My Monsters, and I have  Ice
Mechdragon, Aldebaran, and Fire Mechdragon, Betelgeuse in my inventory, but
all of the mechdragons needed for the evolution are grayed out on the evolution
column, and a mouse over says none in inventory. I also have the Keeper of
Gold, but it is solid and shows up fine. Only the mechdragons are grayed
out. I'm more than happy to help you figure this out, but like I said, it
is not a big deal for me. I've already evolved my Hadar, and just added him
manually. Let me know if you need me to try anything else. Hope this helps.

**Comment by madcowfred** [comment]
Oh, I see what you mean. PADherder treats 'materials' and 'monsters' as completely separate things - having a Mechdragon in your My Monsters list doesn't mean you want to be able to use it as a material. If you go into My Materials and add a Mechdragon there, it will count.

It's a little confusing and probably needs to be explained better somewhere.

**Comment by FlipperInJapan** [comment]
Fred,
It appears you made some updates to the PADherder, and now I can't access
any of my data. Monsters, Material, Sets, ect. I tried hitting reset on the
the Monsters filter like we had to do last update, but didn't work. I hope
you get it fixe soon. I'm lost without it.
thanks,
Paul
