### ISSUE TITLE
please add these missing uvos:

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#509]
1726 (Awoken Kagu)
1737 (Ultimate Hera-Is)
1602 (Ultimate Blue Flower Dragon)

**Comment by ngamber** [comment]
1727-1731 as well.

**Comment by ngamber** [comment]
One more set: 1712, 1713.

**Comment by madcowfred** [comment]
The non-Valk ones have been added, I'll have to modify some scary internals to add support for ultimate ultimate evolutions. Damnit GungHo :disappointed:

**Comment by ngamber** [comment]
Thanks, and good luck!

**Comment by ngamber** [comment]
Oh, and 1300 (ultimate okuninushi) too. Also, I've cleared cache/refreshed/incognito'd and I'm not seeing any of these showing up yet, just fyi.

**Comment by madcowfred** [comment]
Apparently I forgot to hit DEPLOY. Added okuninjasushi and pushed button.

**Comment by ngamber** [comment]
1712 and 1713 (samurai zaerog and ultimate stone dragon) are still missing.

**Comment by madcowfred** [comment]
Fixed now, looks like there was a weird bug with adding new evolutions.

**Comment by ngamber** [comment]
Thanks, looks good!

**Comment by madcowfred** [comment]
Valks added, hopefully nothing explodes.
