### ISSUE TITLE
Pengdras

### ISSUE THREAD

**Issue by BRiL1201** [madcowfred/padherder-issues#51]
Would be cool to have a way to maintain pengdras, to see how many dragon plant or dragon seed you need to evolve them, and would also be good to see how man evolved pengdras it takes to MAX your monster.

i know I could put the pengdras in the monster list, but i have a lot at any given time - it'd just be easier if there was a special spot for them to be maintained. :)

**Comment by madcowfred** [comment]
Not really that interested - if you can count up how many pengdras you have, you can tell easily enough how many materials you need.
