### ISSUE TITLE
How to add teams to other team groups in My Teams

### ISSUE THREAD

**Issue by FlipperInJapan** [madcowfred/padherder-issues#510]
Maybe it is because I'm on a Mac, but I cannot for the life of me figure out how to add teams to the other team groups in My Teams. No matter what I have tried, when I add a new team it always show up under the first group only. Also, Is it possible to add a filter to search through teams for a name?

**Comment by madcowfred** [comment]
This is one of those things that isn't communicated very well at all by PADherder - simply drag-and-drop the team name into another group. There should probably be a team group dropdown when creating/editing a team though.

Not sure what you mean by searching through teams - do you want to filter based on the team name?

**Comment by FlipperInJapan** [comment]
Thanks Fred. The drag and drop is working fine. I just didn't know that it was how to do it. 

Yes, a filter, or a way to alphabetize them. I'm old and memory doesn't work so well, so I put all of my teams in PADherder. It becomes hard to find the team I'm looking for with so many teams in the list. It's not an huge priority, and it will help to be able to put them different groups now, so if you can do it without too much trouble, it would be a nice to have option. 

I really appreciate all the hard work you have put into this for us. Congratulations on finishing your exams. You finish up your Bachelor's Degree, or Doctorate?

sincerely,
Paul

**Comment by madcowfred** [comment]
Added a new dropdown to set the team group
