### ISSUE TITLE
Using 'Bulk add monsters' gives ultimate evolutions a previous target evolution

### ISSUE THREAD

**Issue by bloodwars** [madcowfred/padherder-issues#517]
Bug/Feature Request:  Checkbox/boolean in edit monsters to show/hide un-evo as an evolution in My Monsters (default to hide) and to not count those lits as needs in My Materials if it's hidden (I know if you set priority to Zero it will hide them as needs, but that doesn't cover all cases).

seeing that I need 30+ lits when i really need 4 is annoying/confusing.

**Comment by madcowfred** [comment]
Why are you setting things to an alternate evolution if you don't want to actually do them?

**Comment by bloodwars** [comment]
I'm not, or i don't understand what you're asking.  I bulk added my entire box from PAD, and it includes 40+ uvo/maxed monsters, and every single uvo'd monster in padherder is showing up with the de-uvo (5 lits) thing in the evolution box.  if there's a way to make that go away, i'd love to know how to do it.

**Comment by bloodwars** [comment]
okay i see what happened.  it defaults them all to the de-uvo from the bulk add.  so i have to manually go and re-set each guy to evo: none in the edit->evo dropbox.

**Comment by bloodwars** [comment]
I guess that means this issue is closed, but there's an issue where bulk add defaulted all my uvo's to a de-uvo evolution by default, which doesn't make sense.

**Comment by madcowfred** [comment]
Yeah, that sounds like a bug. I shall investigate!

**Comment by madcowfred** [comment]
This should finally be fixed now :\
