### ISSUE TITLE
Uvo Ronia LS does not work in teams

### ISSUE THREAD

**Issue by steelstiletto** [madcowfred/padherder-issues#518]
I made a previous issue because the Ronia leader skill was listing incorrectly, and that has been fixed now, but the new uvo for Ronia still does not work in the team list. Clicking the "Max Level" button for my team: https://www.padherder.com/user/steelstiletto/teams/#96338 actually reduces the recover, because my Ronia gets evolved and the LS stops working.

**Comment by madcowfred** [comment]
I saw these when updating leader multipliers but there's a bit of an issue with a few new ones, namely that the multipliers are different for different monster types. I'll have to implement some new support for annoying leader skills.

**Comment by madcowfred** [comment]
Should be fixed now
