### ISSUE TITLE
Linking/Unlinking Issues

### ISSUE THREAD

**Issue by ghost** [madcowfred/padherder-issues#520]
My first issue is that I can't link my two accounts 'Kainerok' and 'Mifrate' because I never received a verification email when registering Mifrate, and I didn't receive an email to accept the link either.

The second issue is that when clicking the "unlink" option, I get a 404: Page Not Found error. 

Thanks :)

**Comment by rennai76** [comment]
I too had this problem (link rennai76 to rennai762).  I was able to successful in linking the same account to itself (rennai76 to rennai76) and was able to unlink it.  When I tried to just relink (76 to 762) I got an error that the accounts were already linked (ID 2009).  I tried reversing the link (762 to 76) and that worked (ID 2033).  I am still unable to remove ID 2009 from either account however.  I'm guessing that the ID was deleted from the DB after three days without correcting the account information.

**Comment by madcowfred** [comment]
Gmail tends to stick padherder emails in spam for no discernible reason, there's not a lot I can do about  that. If you change the email address (username dropdown->My Account) it will send a new confirmation email, though that does require another address. I can reset it manually I guess?

I'm investigating the account linking weirdness, it looks like there are a few logic errors hiding in there.

**Comment by Thelmecle** [comment]
I got this problem i linked an account with a wrong email adress and now i can't unlink or link my account even if i have enter the new mail adress ... 
A solution is possible ?

**Comment by madcowfred** [comment]
Fixed being able to link accounts to themselves and also the fact that link verifications never actually expired, that should fix these problems.
