### ISSUE TITLE
PADherder data not loading after the update today!

### ISSUE THREAD

**Issue by FlipperInJapan** [madcowfred/padherder-issues#522]
Fred,
I sent you an e-mail, but thought you might not get it in a timely manner since it was a reply to the previous requests. I cannot access any of my PADherder data after the update you just finished today. I hope that this isn't an issue only for me. FYI, I thought that maybe it was an issue like last update where we had to hit reset on the search filter, but that didn't work, and I can't access anything on the site. It just says loading on most screens, except My Monsters. It just comes up as none showing. Under My Teams, I can see the names of the teams I created and the icon of the leader of the teams, but no Teams are showing up.
I hope you can get this correct soon. I'm lost without it. Thanks again for everything!

v/r,
Paul

**Comment by steelstiletto** [comment]
My friend and I are also having the same problem, so I can confirm that it is not just FlipperInJapan having this issue.

**Comment by madcowfred** [comment]
I broke shit, oops. Fixed now.

**Comment by FlipperInJapan** [comment]
Thanks for getting it back up so quickly. I was truly lost. I spent several
weeks trying out different teams for the sky prison, and finally found one
last week that worked for me, but with my cursed memory, I couldn't for the
life of me remember what the team was. Is the data saved on the website, or
on my computer? Is there a way to back up the data and see it off line when
the site is down?

Have a great weekend and thanks again!
