### ISSUE TITLE
Feature Request: Add "Total Weighted Stats" to the Sorting dropdown.

### ISSUE THREAD

**Issue by bloodwars** [madcowfred/padherder-issues#523]
When looking for cost restricted teams, weighted stats (hp/10 + att/5 + rcv/3) is probably the most useful way to sort/select monsters, but it's the only option that's missing from the sorting options right now.

I also wouldn't mind seeing it in the team build or on the pop up bubbles when you're mousing over an icon in the My Monster tab either.

**Comment by jtanium** [comment]
+1

**Comment by madcowfred** [comment]
Added.
