### ISSUE TITLE
Wrong Monsters  IDs

### ISSUE THREAD

**Issue by JamesCID** [madcowfred/padherder-issues#525]
While using PaListener the   following monsters  can't  sync properly:

500 - Princess Punt (And her Evo)
502 - Dinocorn
1524 - Noble Dragon , Yoroku  (And His Evo)

For the NA  client

**Comment by madcowfred** [comment]
Fixed.

**Comment by JamesCID** [comment]
1524 still fails to properly sync.

**Comment by madcowfred** [comment]
Should really be fixed now.
