### ISSUE TITLE
Dungeon events are incorrectly timed in the notification dropdown

### ISSUE THREAD

**Issue by DreadPirateShawn** [madcowfred/padherder-issues#533]
This doesn't happen every time, but a few times now I've seen dungeon events (eg "Super Sapphire Dragons for 2m") appear during incorrect windows.

For instance, just now at 8:55p (PST) on Dec 12, I saw "Super Sapphire Dragons for 5m" appear, but nothing was showing up in my game. So I checked puzzledragonx.com, and the expected window is actually at 7pm for group C. Over the next 5 minutes, it steadily counted down to zero, despite no dungeon appearing in the game and no dungeon being scheduled on puzzledragonx.com or the PadGuide app.

Tonight I viewed this on both Firefox and Chromium on a Linux Mint distro, same behavior in each. (Previously, I've seen this on my work laptop, Chromium again but this time on a Mac laptop.) This time I captured a couple of screenshots.

My screenshot from padherder includes my account number -- 342528375, which is group C, since the third digit is 2 or 7, per http://pad.wikia.com/wiki/Event_Time_Lookup -- and also shows the time (8:58p bottom right) and the wayward event notification (top right).

![8 58_screenshot_pad](https://cloud.githubusercontent.com/assets/1418951/5422653/b6368ff0-8243-11e4-9fc2-b2fe4f7ffdfa.png)

My screenshot from puzzledragonx shows the schedules for all groups (7pm for group C) since I was logged out. (When I logged in after taking the screenshot, it displayed only 7pm for me, as expected.)

![8 58_screenshot_puzzledragon](https://cloud.githubusercontent.com/assets/1418951/5422654/b9bcdf26-8243-11e4-90e6-0e1fc8f11d8a.png)

Let me know if you're not sure what's going on, or need help fleshing out a repro -- I can try to keep watch for it to happen again.

**Comment by madcowfred** [comment]
PADherder still uses the wiki as an urgent dungeon source. The wiki is basically abandoned at this point. I need to get around to using PDX probably :\

**Comment by madcowfred** [comment]
Finally remembered to do this, blerf. SHOULD be fixed now.
