### ISSUE TITLE
Some max levels in Sets messed up again

### ISSUE THREAD

**Issue by zably** [madcowfred/padherder-issues#536]
During the last update, some of the monsters in "My Sets" no longer show a star at max level (and the heart for a completed max level set goes away, which is how I noticed). It probably has something to do with new ult-evo's.  I'm not sure if this is all of them, but the RGB Japanese 1.0 gods, RGB Indian 1.0, all of the Norse pantheon, Horus, Isis, Astaroth, and Archdemon Lucifer are the ones I noticed.

http://i.imgur.com/U9Lq3Ht.jpg

PS. I know it's minor, do you even want bug reports about this type of thing?

**Comment by madcowfred** [comment]
I like all sorts of bug reports. This is almost certainly related to #538.

**Comment by madcowfred** [comment]
This should be fixed now :frowning:
