### ISSUE TITLE
God Valk not appearing in Evolution column

### ISSUE THREAD

**Issue by blvcksvn** [madcowfred/padherder-issues#537]
For Light Valk specifically, her God Uvo doesn't appear from the possible evolutions if not in her uvo stage. Is this intentional to not have an issue with double ultimate evolution? I only found it an issue because I can't have her God Uvo show up on my teams tab.

**Comment by JamesCID** [comment]
Have  you changed  the  evo target?  Double click  her at your monsters,  pick the god valk  as target evolution (Her name is in Japanese) and she should  show  up  at your teams once you click on maxed.

Works fine for me.

**Comment by madcowfred** [comment]
Hm, that's an odd one - the ultimate ultimate evolution shows up if she's Princess Valkyrie but not if she's Great Valkyrie.

**Comment by madcowfred** [comment]
This should be fixed now, ugh what a mess :frowning:

**Comment by blvcksvn** [comment]
Still not working, unfortunately..

**Comment by madcowfred** [comment]
This is a very odd bug - the ultimate ultimate shows up for Princess Valkyrie, but not for Great Valkyrie or Valkyrie. I'll have to look in to what the scary evolution code is doing. Reopening.

**Comment by DreadPirateShawn** [comment]
Issue #543 might be related. (Edited: Originally posted details as a comment here, but flipped to separate ticket for clarity, just in case.)

**Comment by madcowfred** [comment]
This should really be fixed now.
