### ISSUE TITLE
jewel evos horribly broken

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#539]
Upon trying to set a monster's destination evolution to one involving a jewel, a 500 error is generated. In addition, all of my monsters currently set for one had their evolution unset (valks, beelzebub, kagutsuchis).

**Comment by ngamber** [comment]
In addition, it looks like _all_ of my set evolutions were unset. Ones that don't require a jewel seem to work fine, however.

**Comment by madcowfred** [comment]
The issue causing #536 and #538 had gotten the evolution table into a horribly broken mess, it was simplest to just nuke it from orbit rather than trying to untangle everything. Sadly this means _EVERY_ target evolution was set to nothing :(

**Comment by ngamber** [comment]
Oh, got it. Also, speaking of jewel evos, noticed that valk super ultimates now show up twice in the evolution dropdown.

**Comment by madcowfred** [comment]
Really? I have a 694 normal ultimate, it shows 515 (de-ultimate) and 1727 (superultimate) as options.

**Comment by madcowfred** [comment]
Ah, I see some broken ones for the colourful valks. Sigh.

**Comment by blvcksvn** [comment]
My great valk still isn't showing superuvo valk. I suppose this is simply not going to work then?

**Comment by madcowfred** [comment]
Should be fixed. Reopening #537 for the other, slightly different Valk issue.
