### ISSUE TITLE
"Save" icon doesn't appear when editing monster. [BUG]

### ISSUE THREAD

**Issue by mezmerie** [madcowfred/padherder-issues#54]
Work-a-round is to just hit enter after editing a field. Don't know how to make this a bug. (By the way, "Magical Search" is great!)

**Comment by madcowfred** [comment]
Oops, fixed :fish:

**Comment by mezmerie** [comment]
Awesome, thanks! Not too many people even noticed on my forum. I rely on this application so much, do you take donations? I suspect GungHo will eventually have a similar website where you won't even have to update your monsters (like WoW), it will just reference the main game database, but in the meantime, this is super helpful.

Date: Sat, 14 Sep 2013 22:51:36 -0700
