### ISSUE TITLE
#325 Dark Flame Ifrit only showing #324 Shining Flame Ifrit in evo box

### ISSUE THREAD

**Issue by blvcksvn** [madcowfred/padherder-issues#541]
Normally it should show Ifrit and the five different uvos, but right now it's only showing the Fr/Lt version. Also worth noting that the icon for the 5 -lits de-uvo shows the Fr/Lt icon rather than the Fr only icon.

**Comment by madcowfred** [comment]
Oh dear, evolutions not quite fixed. Seeing if I can solve this without blowing up the evolution data again.

**Comment by madcowfred** [comment]
This should be fixed now.
