### ISSUE TITLE
No evolution appearing in "My monsters"

### ISSUE THREAD

**Issue by Honky-Tonk-Hero** [madcowfred/padherder-issues#544]
For a while every time I access the "My Monsters" tab I have to reset filters, although I never used a filter before.

But now after reseting filters monsters appear with nothing in the "Evolution" column. And the evolve button is greyed out.
Additionally in the "My Materials" tab it list 0 in every box, regardless of how many materials you already have or how many you need.

**Comment by FaxCelestis** [comment]
Read the news.

**Comment by madcowfred** [comment]
Evolutions broke in a bad way, read the latest News post - https://www.padherder.com/news/67/
