### ISSUE TITLE
A count of the number of monsters

### ISSUE THREAD

**Issue by bleeben** [madcowfred/padherder-issues#55]
There's already a count on the bottom of the monsters pages for stuff like + eggs, and pengdra cost. So one for the number of monsters currently listed as well? ( I end up having to count to doublecheck that I haven't forgotten to add any monsters every so often)

**Comment by thismightberyan** [comment]
Might be good to have a way to track Pengdras easily (and therefore account for jewel dragons / dragon plants needed to evolve).

**Comment by madcowfred** [comment]
Added, will now display '96 monsters shown' on the footer.
