### ISSUE TITLE
chibi REM and christmas monsters missing

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#550]
1781-1794 are now available in NA.

**Comment by ngamber** [comment]
Also, UPC speculates that the new REM monsters will be regulars in the pink rem from now on, aside from genie and christmas kirin, whom I would suggest belong in their own set,

**Comment by madcowfred** [comment]
Monsters updated, Christmas REM set added, leader skills done, one small goat sacrificed to the gods of please nothing break.
