### ISSUE TITLE
Performance Issue?

### ISSUE THREAD

**Issue by kimono38** [madcowfred/padherder-issues#551]
Lately (around 3 weeks or more), PADherder getting so slow that sometimes it can't even fully load the page even with multiple refresh.

I wonder is it something to do with the auto update App take up all the bandwidth?

It getting so frusrated to even to make an update, i started to ignore more update lately. Now the PADherder is totally out of sync from my box. I manually update by the way, not using any app.

**Comment by madcowfred** [comment]
The server has plenty of spare capacity, I doubt the issue is PADListener updates. Where are you located? What is loading slowly?

**Comment by kimono38** [comment]
I'm located at Malaysia, i tried it both my office and my house. I have 331 monsters, and the monsters tab picture won't finish loading. It just stop after 20 icons. If i choose set, it take a long time to load the page and the icon is incomplete. Does the icon come from your server or link to PADX?

**Comment by madcowfred** [comment]
The icons come from my server, or more technically, via CloudFlare. It's entirely possible that you have poor connectivity to whatever server CloudFlare uses to serve you the files, I'm not sure what I can do there :(

**Comment by kimono38** [comment]
Today the PADherder is smooth like butter. First time in months. I wonder if you did something to it. Thanks anyway for replying and providing such a wonderful tool for us :)

**Comment by madcowfred** [comment]
I didn't touch anything, let's go with "magic". Glad it's working better though!
