### ISSUE TITLE
(non-)materials

### ISSUE THREAD

**Issue by Marco-PF** [madcowfred/padherder-issues#552]
Hey Freddie,

Do you think you could fix it so the high metal/jewel dragons get imported as materials and not monsters? The regular, king & super king metal/jewel dragons seem to update like this, looks like a bug with only the "high" ones. 

Not sure but I think this should apply to pengdras too, unless I'm misunderstanding the term "materials" in this context.  As a matter of fact, perhaps any monster of type "enhance" or evo mat should default to materials unless/until the user changes it to (regular) monster. Could you even add this as a field in the "edit monster" screen? Maybe just a checkbox ("[_] save as material")...?
Thanks!

**Comment by madcowfred** [comment]
Materials are things that are used as part of an evolution, nothing else - hence no High dragons, Pengdra, etc. There's not much reason to track how many you have when they're just for food.

**Comment by Marco-PF** [comment]
Yes, that's what I'm saying. ;-)
High metal/jewel dragons being imported show up under my monsters but do not show up under my materials. At least, this is what is happening for me. If you can't replicate this, do you have any suggestions for me to fix it? Thanks!!

The other thing I was saying was that it could be useful to have a checkbox or other boolean field to the edit monster box for when you want to move it from my monsters to my materials. (I think you thought I meant the other way around, which occasionally may be useful such as extreme metal king or dub mythlits... or not lol)

**Comment by Marco-PF** [comment]
Oh, also, imported pengdras show up under my monsters and not under my materials.

Maybe I misunderstood. Did you mean that this is how they should appear? You said "no high dragons, pengdras" following the sentence about materials. Maybe I read that wrong. Did you mean pengdras and high dragons are _not_ materials used only as part of an evolution/fusion? I don't think that would make sense if the kings and super kings are "materials" but maybe I missed something. Thanks again...

**Comment by madcowfred** [comment]
This is how they should appear.
- My Materials is for _evolution materials_ - things that are used to evolve other monsters.
- High dragons, Pengdras, and various other things are _not used to evolve other monsters_ and hence won't show up in My Materials.

**Comment by Marco-PF** [comment]
Okay, this makes sense. Thanks for the explanation. I was thinking fodder is fodder but you separate evolution fodder from the rest. I guess, I've rarely seen the jewel and King jewel dragons used in an evo so I've equated them to the high dragons. My mistake. Thanks again, really appreciate your hard work on padherder! You rock!
