### ISSUE TITLE
Multiple monsters: incorrect icons

### ISSUE THREAD

**Issue by hawksdelight** [madcowfred/padherder-issues#553]
the evo of the Shining Dragon Knight is missing the secondary att of yellow

**Comment by madcowfred** [comment]
He definitely has the secondary attribute, looks like his image just hasn't been updated to have the second orb. I'll leave this open and change the title so I remember to check for a new one every now and then :\

**Comment by blvcksvn** [comment]
A few other monsters have this bug, mostly Pad Z monsters. Baal also has a Dark subtype in his uvo.

**Comment by MagneticSpark** [comment]
If you're going to update the icons of these monsters, could you also update the icons of the PAD Battle tournament cards? Gungho updated them a while ago, they look a bit different now.

**Comment by FaxCelestis** [comment]
Also looks like the fairy tale girls (Cinderella, etc.) aren't updated.

**Comment by madcowfred** [comment]
This should allll be fixed now. Hopefully.
