### ISSUE TITLE
Wrong IDs  for new monsters (Padlistener)

### ISSUE THREAD

**Issue by JamesCID** [madcowfred/padherder-issues#555]
Hi,  I noticed there  are monster that can't  be synced properly.

The ones I noticed:
- New monsters  from Gungho Collab (1521 for example)
- Water insect dragon dungeon  (1592  for example)
- King  Devitama (1323)

Not sure if chibidra also falls under this category  but most likely he does.

**Comment by madcowfred** [comment]
Those should all be fixed now.
