### ISSUE TITLE
Multiple Evolutions - Materials

### ISSUE THREAD

**Issue by Gannonball09** [madcowfred/padherder-issues#56]
Is it possible to add the materials for the future evolutions of certain monsters? For example, I have Berserk. PadHerder shows me what I need to evolve Berserk into Siegfried. However, I also would like to have listed what I need to evolve Siegfried as well as the ultimate evolution after that. This feature would help people like me that like to plan for things long term. Thanks!

**Comment by madcowfred** [comment]
Dupe of GH-18.
