### ISSUE TITLE
Incorrect IDs when Syncing  via PadListener

### ISSUE THREAD

**Issue by JamesCID** [madcowfred/padherder-issues#563]
The monster I found affected are  Light Shieldra (1543), Cauchemar and his evo  (1628 and 1629), Chrono Turtle (488, 489),  Gamble Mage (486, 487)  and the Norns (1669-1674).

Also,  this happens on every  update,    is it possible  to script  the fix  or is everyone  unique?

**Comment by madcowfred** [comment]
Fixed. Monsters get manually updated, it's probably easier to just bug Neraud and get him to sync all monsters from your data instead of actually believing the jponly flag.
