### ISSUE TITLE
Cauchemar?

### ISSUE THREAD

**Issue by OhNoBananas** [madcowfred/padherder-issues#564]
Can you add him to the descends lists in sets? Him and my Light shieldra keep giving me the "unknown monster" error in Pad Listener, and I think this would solve it.

**Comment by madcowfred** [comment]
Sets have nothing to do with how PADListener works. Try, er, updating your data? I don't actually use PADListener so I dunno.

**Comment by OhNoBananas** [comment]
Yah I saw that, but noticed he still isn't shown in sets though, two
different issues for sure.

**Comment by madcowfred** [comment]
Added him to the Descended meta-set.
