### ISSUE TITLE
Dragon Shogun should be D/D appears to only be D

### ISSUE THREAD

**Issue by theonlyalterego** [madcowfred/padherder-issues#565]
http://www.puzzledragonx.com/en/monster.asp?n=1129

image https://www.padherder.com/static/img/monsters/60x60/1129.4308a7ae9209.png does not match http://www.puzzledragonx.com/en/img/book/1129.png

**Comment by madcowfred** [comment]
Er, I meant to post that I'd fixed this instead of just closing it. Oops.
