### ISSUE TITLE
Missing LS and DBZ part 2 set

### ISSUE THREAD

**Issue by MagneticSpark** [madcowfred/padherder-issues#566]
card #1571 is missing it's leader skill in My Teams. The description is there, but it's not multiplying. And there's no DBZ part 2 section in My Sets.The cards were added in JP in september 2014 I think. The cards are Cell, android 16, android 17, android 18, and Buu (collab boss).

**Comment by MagneticSpark** [comment]
Just noticed something... It's not just Cell (#1571),  quite a few JP only cards seem to have their leader skills broken. Tigrex & Rex Neko (#1612), Gore Magala (#1608), Killua (#1012), Vegeta (#1560), Gold Seiya (#1725)... All of them have their LS descriptions, but no multiplier. Here's what I'm talking about: http://i.imgur.com/WFUdyYq.png Strangely enough, goku seemed to work just fine. There are probably more bugged cards out there, but these are the ones I spotted so far :p

**Comment by madcowfred** [comment]
Leader skill multipliers are entered manually, and I don't usually bother with JP leader skills as it's a fair bit of tedious work for relatively few users (~2% of total accounts are set as JP). I sometimes add specific ones that people bug me about, that's about it :frowning:

I'll add the second DBZ REM monsters as a set.

**Comment by MagneticSpark** [comment]
Oh, I didn't know it was added manually. If it's too much work, then fixing just Cell, Gold Seiya and unevolved Android 17 is fine by me. Oh and Saori too (#1437) ^^ 

And just wanted to let you know that Gungho lowered the CD from some DBZ cards: http://mobile.gungho.jp/news/pad/141226_skill_dragonball3.html

If you could update that as well it would be great :D

**Comment by madcowfred** [comment]
- Added the DBZ Part 2 monsters to the existing 'Dragonball Z REM' meta-set.
- Updated (almost) all of the JP leader skill data, there's a few new ones that will need custom support.
