### ISSUE TITLE
Material mouse over

### ISSUE THREAD

**Issue by dlibby** [madcowfred/padherder-issues#57]
An Enhancement.

Would be neat if on the "My Materials" page, one could mouse over the material monster's H(igh), M(edium), L(ow) columns and a pop over tool tip would appear with a text list of the monsters those materials are used for. This would be handy in the case of box congestion. Even in my Medium Category, some monsters are more important than others. I could then better prioritize mats and sell accordingly.

Thanks for all your hard work!

**Comment by madcowfred** [comment]
This is now implemented in the 'Dungeon reminder' box at the top of the page, I want to change some other things with My Materials before I add it there.

**Comment by madcowfred** [comment]
Now added to My Materials page.
