### ISSUE TITLE
No monster icons for 1297 and 1067

### ISSUE THREAD

**Issue by thebobwaffles** [madcowfred/padherder-issues#571]
In the "My Monsters" and "My Teams" sections, my 1297 Divine Wardens, Umisachi and Yamasachi and 1067 Andromeda dont have monster icons in the lists. They do when I hover over them, but its bugging me to see no icon in my list.

**Comment by madcowfred** [comment]
Not sure what went wrong here, I've regenerated the smaller images and that appears to have fixed it.
