### ISSUE TITLE
[EU] Wrong sortorder for BAO Collab and Shinra Bansho Collab Monsters

### ISSUE THREAD

**Issue by mastercontrolprogramm** [madcowfred/padherder-issues#572]
Hi!

Maybe EU got the japanese sort order?

My account for reference !
https://www.padherder.com/user/criminalenergy/monsters/#31,0,31,2047,268435455,0,,0,0,0,eq,0,0,0,0;boxfav,0

Correct Order Red
949: AB Red Bird Red
-> 934: Exiled Apollo
-> 925: BAO Firefly + Flamethrower should be between
906: Flame Baron
-> 971: BAO Catwoman
475: Hellfire Pyro Demon

Correct Order Blue
951: AB Bluebird Blues
-> 927: BAO S. Grundy Reborn
907: Aqua Baron

Correct Order Green I
1682: Ace Archer, Green Arrow
-> 1049: Sacred Dragon King Saiga
-> 674: US. BAO Robin+E. Stick
522: Snow Globe Dragon Vert

Correct Order Green II
953: AB Green Bird Hal
-> 929: BAO Venomous Copperhead
908: Green Baron

Correct Order Green III
103: AB Dragon Knight
-> 1055: Kaguya
-> 928: BAO Copperhead
686: King Woodsie

Correct Order Yellow
955: AB Yellow Bird Chuck
-> 931: BAO Venom-Enhanced Bane
909: White Baron

Correct Order Purple I
1084: Purple Sky Fruit, Grape Dragon
-> 886: Emperor Masterion
-> 678: BAO Batman+Remote Claw
-> 670: BAO Joker+A. Blossom
320: Dark Golem Mk.III

Correct Order Purple II
1694: Evil Genius, Lex Luthor
-> 1054: Bokkle
959: AB Black Bird Bomb

Correct Order Purple III
830: Protection Demon of Dark, Jyaki
-> 677: BAO Batman+Batarang
-> 669: BAO Joker
406: Cerberus

Thank You!

Best Regards
A Fan

**Comment by Marco-PF** [comment]
I'm sorry I can help or comment on this but I am curious as to what this sort order is based upon? I don't fully understand the default sorting options (like "box" or anything beyond the first level, such as ATT (but then what)) so that's why I'm asking. How do you "know" the order is incorrect and what the correct order should be?

Didn't mean to hijack. Appreciate the feedback - thanks!!

**Comment by Marco-PF** [comment]
can't*

**Comment by madcowfred** [comment]
This should be fixed now, EU will use US override IDs (GODDAMN BAO COLLAB) for display/sort purposes.

The sorting stuff is.. weird. There are 3 complex sorts:
- default: ['-priority', 'element', 'name', '-currentxp', 'zero']
- boxatt: ['element', 'element2', '-rarity', '-id', '-plus', '-level', 'zero']
- boxfav: ['element', '-rarity', '-id', '-plus', '-level', 'zero']

... and the basic sort types have 'default' added to the end. Box (ATT) and Box (FAV) are intended to match the in-game ATT and FAV (assuming you have all of your monsters favourited) sort options.

**Comment by mastercontrolprogramm** [comment]
Confirmed working!
Thank you!
