### ISSUE TITLE
Suggestion: Exclude max level monsters with Zero priority from the "Done" list

### ISSUE THREAD

**Issue by noip** [madcowfred/padherder-issues#573]
I have a bunch of low cost cards that I use for S-rank etc, and they're all clogging up the top of my monsters list because, at max level, they're counted as "done"

It would be good to exclude cards which have been set to priority Zero from the Done list.

**Comment by mccool37** [comment]
You could move the done listing to the bottom of the page.

**Comment by madcowfred** [comment]
The accepted way to deal with this is to go to My Account (username dropdown in the top right) and change the 'Done position' to 'Normal position' - that will leave Zero priority Done monsters down the bottom.
