### ISSUE TITLE
material dungeon reminder won't turn up again after I closed it

### ISSUE THREAD

**Issue by gundamftw** [madcowfred/padherder-issues#579]
I accidentally click the "x" and closed the dungeon reminder, and I can't get it back.  I tried the dungeon reminder checkbox in setting, it doesn't do anything either I check or uncheck it.

**Comment by madcowfred** [comment]
The only way this should 'break' is by clicking 'Hide for today'. Can you check your JS console (Ctrl-Shift-J in Chrome, Ctrl-Shift-K in Firefox I believe) for any errors?
