### ISSUE TITLE
Favoriting/bookmarking friend's public pages?

### ISSUE THREAD

**Issue by pazurururu** [madcowfred/padherder-issues#58]
Not sure how to make this issue an Enhancement Type:

Goal: Allow a user to follow other users' monster pages.
Steps: On someone else's page, a user could click on a star or bookmark icon, and it would be visible on a "favorited" or "followed" list on the user's main page. The user can then use this link to revisit this page.

**Comment by madcowfred** [comment]
I guess I added this!
