### ISSUE TITLE
Add option to not import < X rarity monsters from JSON

### ISSUE THREAD

**Issue by jgoldshlag** [madcowfred/padherder-issues#580]
One annoyance when using the JSON import is that the random trash monsters I have around end up getting imported. It would be great to have an option to not add monsters of less than X rarity to My Monsters (ignore this for material monsters). X could be fixed at 4 or 5, or give us a drop-down

**Comment by madcowfred** [comment]
Finally added this. This along with the improved "ignore enhance/evolve/awoken material monsters" support should make importing much less annoying.
