### ISSUE TITLE
light insect dragon missing from my materials

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#587]
evo mat for ult. starling.

**Comment by madcowfred** [comment]
Probably because SuperStarling is still flagged as JP only so the evolution is also considered JP only.

**Comment by ngamber** [comment]
The orbs required by superstarling count towards my total blue orbs in that
section, though. Seems kinda inconsistent.

**Comment by madcowfred** [comment]
Hrm, that is true. I think there's currently a distinction between:
- A material used in multiple evolutions that also happens to be used in a JP-only evolution, which will show up on the list
- A material that is only used in JP-only evolution(s), which won't show up at all

... and they should probably work the same way.

**Comment by madcowfred** [comment]
I've made a change to just ignore JP only flag for materials, that appears to make Mr Insect Dragon show up. Also various weird JP things but hey, thems the breaks.
