### ISSUE TITLE
Missing sets and other minor issues

### ISSUE THREAD

**Issue by MagneticSpark** [madcowfred/padherder-issues#589]
I know us JP players are the minority, but I can't help but feel PADherder as incomplete with all of these sets missing.

Missing collab REM Sets:
name                          (card number)

HUNTERxHUNTER (1009, 1011, 1013, 1015, 1017, 1019, 1021, 1023, 1025, 1027)
Puzzle & Dragons Battle Tournament (1278, 1280, 1282, 1284, 1286, 1288, 1290, 1292)
Dragon Ball Z part 3 (1795, 1797, 1799, 1801)
Saint Seiya part 2 (1718, 1720, 1722)
Bikkuriman (1487, 1489, 1491, 1493, 1495, 1497, 1499)
"Monster Hunter" part 2 (1198, 1605, 1607, 1609, 1611)

Minor issues:

1) There are some missing collab bosses:
Angry Bird Epic (NA has this collab as well): 1642
Bikkuriman: 1479
DBZ part 2 (you accidentally listed card 1578 as the boss): 1579
Monster Hunter 4G: 1603
PAD BT: 1276
Ragnarok Online (NA should eventually get this): 1315
HUNTERxHUNTER: 1029
Gungho Collab (I don't know how you'll classify Deviling since it also appears on other dungeons, but Archangeling only spaws in this dungeon, and it's a boss. NA also has this dungeon): 594, 595 too if you consider it a boss.

2) Missing collab invades:
HUNTERxHUNTER: 1031

3) The "Monster Hunter" set should actually be named Airour de Bazaar.

4) I feel like Chrono Turtle and Gamble Mage should be added to the Misc REM set.

**Comment by madcowfred** [comment]
Thanks for the comprehensive post, I've made all of these changes. I find it hard enough to get accurate set information for NA updates (REM only things, collab bosses, collab invades, etc), getting information for JP is much more difficult as I don't speak/read :jp: Just make an issue in future whenever you see something missing and I'm happy to update things.
