### ISSUE TITLE
PADHerder Not Displaying Properly

### ISSUE THREAD

**Issue by frostmourne16** [madcowfred/padherder-issues#590]
I'm not really sure what's going on here, but PADHerder's not displaying properly for me anymore: the ribbon bar seems to be floating at the bottom of the screen instead of the top like it always does. 

Issue crops up on both Chrome and Firefox. I tried clearing the cache but it's not working. I'm attaching a couple of screens for reference.

Thanks a bunch! :smile: 

![image](https://cloud.githubusercontent.com/assets/10775152/5978389/76401458-a8da-11e4-810b-886637e90367.png)
![image](https://cloud.githubusercontent.com/assets/10775152/5978401/87079716-a8da-11e4-984f-0c3a001eb00f.png)
![image](https://cloud.githubusercontent.com/assets/10775152/5978441/c4b32a1c-a8da-11e4-9c32-42f18be7f5ec.png)

**Comment by madcowfred** [comment]
That's a new one. I have absolutely no idea why that would be happening :(

**Comment by frostmourne16** [comment]
@ Freddie:

Never mind. Found out what's causing the issue - turns out its a DNS
resolution problem that's causing PADHerder to wig out. Switching over to
Google's public DNS server solved it.

Thanks anyways.

Yours sincerely,
FROST
