### ISSUE TITLE
missing sets: 2/4/15

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#591]
These were added to the NA client today, but I don't think they're showing up as JP-only yet either: 

chibi 3kingdoms
HnK collab (also will be food--no evo'd drops here!)

**Comment by madcowfred** [comment]
Which monsters and what do they skill up? Finding things on PDX is annoying.

**Comment by ngamber** [comment]
http://www.puzzledragonx.com/en/monster.asp?n=1851 
http://www.puzzledragonx.com/en/monster.asp?n=1853
http://www.puzzledragonx.com/en/monster.asp?n=1855

these are the evolved fotns skillups. 

unfortunately the mini three kingdoms are a bit hard to distinguish, since they're lumped in with the normal three kingdoms set. doing a search for 'mini' and ignoring the angels and errant saint seiya mob should at least show them: 

http://www.puzzledragonx.com/en/search.asp?q=mini&searchoption=1

**Comment by madcowfred** [comment]
Added the skillups and a Mini Three Kingdoms set. Didn't add the Godfest Only stuff (Zee Huge Liang etc) since I have nfi where they go.

**Comment by ngamber** [comment]
yeah, the mini godfest guys are in the pal machine as well, so I'd say they're the same set, just moar stars.

**Comment by ngamber** [comment]
FWIW the REM grimoires are going live tonight in NA (light/dark) as well: 

http://puzzledragonx.com/en/monsterbook.asp?s=109&e=0&ue=0&s1=1&s2=1&o1=1&o2=1

don't see them after setting my account to JP either. 

thanks!

**Comment by madcowfred** [comment]
They're there - red/blue/green in the Descended meta-set (so probably Descended 37 by now), other two in Misc REM. I think that's where they belong :|

**Comment by ngamber** [comment]
my bad, did a search for grimoire, that screen is frighteningly large in JP.

**Comment by ngamber** [comment]
they still need to be flagged as available in NA, though.

**Comment by madcowfred** [comment]
The light/dark ones should be updated, pdx/wiki still claim the other 3 grimoires are JP only. I think I updated all of the other stuff too, let me know if there's any more.

**Comment by ngamber** [comment]
fotns isn't flagged for na yet.

**Comment by madcowfred** [comment]
Which ones? The REM monsters and collab dungeon drops appear to be.

**Comment by ngamber** [comment]
Sorry, the set itself, not seeing the REM set, or raoh under collab bosses.

**Comment by madcowfred** [comment]
Ah, I had done those but forgot to deploy. Up now.
