### ISSUE TITLE
RGB PADZ Collab Monsters still showing in Japanese

### ISSUE THREAD

**Issue by pknintendodude** [madcowfred/padherder-issues#592]
Minor Issue--

Some of the PADZ Collab Dungeon drops are still in Japanese, and they are not showing up as skillup food for the RGB Ripper Dragons.

These monsters would be:
- Melagon: http://www.puzzledragonx.com/en/monster.asp?n=962
- Melaburn: http://www.puzzledragonx.com/en/monster.asp?n=963
- Hellfire Dragon, Inferno: http://www.puzzledragonx.com/en/monster.asp?n=964
- Zabgon: http://www.puzzledragonx.com/en/monster.asp?n=965
- Zabshark: http://www.puzzledragonx.com/en/monster.asp?n=966
- Stormy Sea Dragon, Levia: http://www.puzzledragonx.com/en/monster.asp?n=967
- Morigon: http://www.puzzledragonx.com/en/monster.asp?n=968
- Morigannon: http://www.puzzledragonx.com/en/monster.asp?n=969
- Boulder Dragon, Garmut: http://www.puzzledragonx.com/en/monster.asp?n=970

Again, it's just a minor issue, as this collab is probably not going to be coming back for a while, just whenever you get a chance. Thanks!

**Comment by madcowfred** [comment]
Uh I meant to comment and forgot. Updated, added food, etc.

**Comment by pknintendodude** [comment]
Thanks!
