### ISSUE TITLE
Random evolution collapses

### ISSUE THREAD

**Issue by beanplanter42** [madcowfred/padherder-issues#595]
Similar to a previous issue someone else had.

When I log in, most of my monster evolutions simply said "x evolutions available" instead of showing the evolution materials. There doesn't seem to be a consistent logic to who gets the "x evolutions available" and who doesn't. I fiddled with the "collapse evolutions" and Account settings but it's still not changing. 

I don't have any Ignore Lists with PADListener, so I'm not sure what's giving this problem.

**Comment by madcowfred** [comment]
Edit them and pick an evolution. If you haven't logged in for a while, evolutions broke badly a month or two ago and had to be reset.

**Comment by beanplanter42** [comment]
Ah, ok. Thanks very much!
