### ISSUE TITLE
Okuninushi Leader Skill acting strangely in team builder

### ISSUE THREAD

**Issue by steelstiletto** [madcowfred/padherder-issues#597]
I have two Okuninushi teams that don't show the correct damage stats when I click the "Show Maxed Stats" button. The multiplier appears to correctly be x16 before I click the button, then drops down to x4 after. I created two additional test teams to show the issue better. One with base form Okuninushi, and one with uvo Okuninushi. The one with base form seems to drop from 16x to 4x when the max stats button is clicked, but the team with already uvo Okuninushi works fine all the time.

Test case demonstrating the drop in multiplier:
https://www.padherder.com/user/steelstiletto/teams/#120933

**Comment by madcowfred** [comment]
Neat bug, thanks for the report and test cases. Should be fixed now.

**Comment by steelstiletto** [comment]
Ha, so the one affecting attack is fixed, but now his leader skill messes up for RCV under the same circumstances. When using the max level button, it does not apply the updated leader skill change to RCV. This bug just can't be stopped. Poor Okuninushi.

**Comment by madcowfred** [comment]
Ok it's really fixed this time. I think. Maybe.
