### ISSUE TITLE
new monsters (and sets?)

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#599]
(big) zhao yun is out, along with mini-gzl (1714) and mini-ggy (1716) and their respective evos.

**Comment by madcowfred** [comment]
Updated the monsters.

**Comment by ngamber** [comment]
Are these supposed to be in an active set? They have evolutions but don't need to be evolved for their skillups, so I'd argue they stand on their own instead of just fodder (though chimeras and fey creatures have sets, so that screen is understandably getting a bit crowded). At the very least, big Zhao Yun should be in Descended 6.
