### ISSUE TITLE
Uvo Okuninushi LS stops affecting ATK in team builder

### ISSUE THREAD

**Issue by steelstiletto** [madcowfred/padherder-issues#600]
The never dead bug is back again. Okuninushi looses his boost to ATK (but still gains the boost to RCV) when he uvo's on the team screen. Test case: https://www.padherder.com/user/steelstiletto/teams/#120998

Okuninushi just loves causing trouble.

**Comment by madcowfred** [comment]
What the hell :(

**Comment by madcowfred** [comment]
This should really be fixed this time :cold_sweat:
