### ISSUE TITLE
missing sets/monsters - 2/23/15

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#601]
http://www.puzzledragonx.com/en/whatsnew.asp?d=022315

new FFCD stuff - jp only of course :(

new ults (shown in the above link): 
     tyrannos, plesios, and brachy
     venus
     vritra
     indra
     wukong
     pandora

partial/missing sets:
- Descended 7:
   (My account is set to JP right now, and I see grimoires and Sonia Gran, but not these)
   Zhao Yun (which should show up in NA too now) http://puzzledragonx.com/en/monster.asp?n=1710
   Medjed: http://www.puzzledragonx.com/en/monster.asp?n=1836
  
  new Pad-Z descend guy: http://www.puzzledragonx.com/en/monster.asp?n=1878
  
     Zeus&Hera: http://www.puzzledragonx.com/en/monster.asp?n=1922
- Mini 3k
  Mini versions are also present for the godfest guys and zhao yun. I'd suggest just adding them to a "Mini Three Kingdoms 2" set. All regions but NA have all of them, NA only has guan yu/gzl at the moment, but will have the rest soon (sometime this week hopefully?):
     http://www.puzzledragonx.com/en/monster.asp?n=1714
     http://www.puzzledragonx.com/en/monster.asp?n=1716
     http://www.puzzledragonx.com/en/monster.asp?n=1821
     http://www.puzzledragonx.com/en/monster.asp?n=1823
     http://www.puzzledragonx.com/en/monster.asp?n=1876
- Bowl Dragons
  Blue is available in NA atm, the rest have all been released in JP:
  http://www.puzzledragonx.com/en/monster.asp?n=1762
  http://www.puzzledragonx.com/en/monster.asp?n=1761
  http://www.puzzledragonx.com/en/monster.asp?n=1763
  http://www.puzzledragonx.com/en/monster.asp?n=1764
  http://www.puzzledragonx.com/en/monster.asp?n=1765
- Bowl Dragon Invades (similar to chasers or fairies, they invade, require evo, and skill up armor knight set (FOOD!)
  http://www.puzzledragonx.com/en/monster.asp?n=1774
  http://www.puzzledragonx.com/en/monster.asp?n=1776
  http://www.puzzledragonx.com/en/monster.asp?n=1778
  http://www.puzzledragonx.com/en/monster.asp?n=1772
  http://www.puzzledragonx.com/en/monster.asp?n=1780

I think this is everything missing from what's currently deployed, but I know sometimes you've already added stuff on your end, so I apologize if there's anything redundant here. As always, thanks for your hard work!

**Comment by madcowfred** [comment]
Thanks for the comprehensive issue, this should all be done now :cow:

**Comment by ngamber** [comment]
Looks good, but blue bowl is active in NA, as well as the muse skillup guy, which are only showing up in JP mode for me.

**Comment by madcowfred** [comment]
Ah, forgot to update those. A new build is deploying now, should be updated in a few minutes.
