### ISSUE TITLE
new ultimates and skill changes (NA)

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#608]
https://www.facebook.com/notes/puzzle-dragons-north-america-gungho/new-ultimate-fusions-and-skills-have-arrived/1029548347073757?id=484776928217571

Ult SQ and Yamato are active in NA, as well as some skill/awakening changes.

**Comment by ngamber** [comment]
Likely due to this, Red Fairy doesn't show up under My Food, either.

**Comment by ngamber** [comment]
Actually, scratch that, same thing with JP account. I'll open a separate issue.

**Comment by madcowfred** [comment]
Probably all updated
