### ISSUE TITLE
Table header in mobile useless

### ISSUE THREAD

**Issue by Dakiton** [madcowfred/padherder-issues#61]
When you scroll down the monster page on a mobile device the sticky header doesn't stay aligned properly.  What you see is the header for Monster over everything.
What you see is the header for Monster over everything.

![screenshot_2013-09-26-21-23-27](https://f.cloud.github.com/assets/5383395/1223602/49ffc958-2724-11e3-878a-ef51548c6a64.png)

**Comment by madcowfred** [comment]
See GH-184.
