### ISSUE TITLE
Dungeon reminder bug (maybe?)

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#616]
Noticed this for some time, basically if you have enough of an evo mat for the day to satisfy your high, medium, and food requirements, but also have some required for low priority evos, the reminder won't go away until you satisfy your low requirements as well. 

As far as I can tell, this only occurs when a mat is required for the food section, and if it were just in the H/M/L categories, as soon as the number for H+M is met, the reminder goes away. 

example:
http://i.imgur.com/CiGixhI.png

note light keepers are at 6, fulfilling both H+M and the food total, but the reminder is still there (since there are more in the low category).

**Comment by madcowfred** [comment]
Fixed this to properly use H+M+F for "do I have enough of these?"
