### ISSUE TITLE
damage calculator

### ISSUE THREAD

**Issue by sbotzek** [madcowfred/padherder-issues#617]
Do you have plans on adding a damage calculator?  With all of my teams in padherder it seems like a natural place to have something like this.

**Comment by zably** [comment]
http://pad-spike-calc.appspot.com/#
This is a damage calculator site that interfaces with padherder (just copy the URL for the team you want, and the rest is pretty self explanatory).

Uevo DMeta is bugged (doesn't apply to attackers for some reason) but the rest seems to be handled correctly, applying rows, TPA, orb enhances, etc.

**Comment by madcowfred** [comment]
PADSpike! looks pretty cool, I'll ask the guy if he minds me linking directly to that from Team pages.

**Comment by madcowfred** [comment]
Added a link to PADSpike! from team pages, much easier than implementing my own version of it from scratch.  https://bitbucket.org/JePaCa/spikecalc/issues/13/add-ability-to-link-to-a-teamid
