### ISSUE TITLE
My PadHerder Teams are messed up!

### ISSUE THREAD

**Issue by NeedHelpPls** [madcowfred/padherder-issues#619]
It's hard to describe so here's a picture and my padherder link. This happened when I updated the name of a team. Can this be fixed? Thanks.

https://www.padherder.com/user/Ducktor/teams/
![tjsxv6l](https://cloud.githubusercontent.com/assets/11593321/6768160/0e48b6b0-d031-11e4-9d30-500fb941783a.png)

**Comment by madcowfred** [comment]
Looks like I forgot to escape some things, oops. Should be fixed now.
