### ISSUE TITLE
new monsters - 3/26 (NA)

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#622]
Amberjack ultimate is live (1880)

Angel 2 series data is now in NA/EU client, godfest likely this weekend, english skills and names already available.

**Comment by madcowfred** [comment]
Updated.

**Comment by ngamber** [comment]
Set still not showing up.

**Comment by madcowfred** [comment]
Looks like the angels were still set as JP only, should be fixed now.
