### ISSUE TITLE
Can you add " High Plus " or High+ to Priority Please

### ISSUE THREAD

**Issue by KittraKat** [madcowfred/padherder-issues#632]
Hi I just started using padhearder and just found this blog here on Github.

I have Not had time to look if this has been suggested before. 

I would appreciate a New priority heading I can filter on; where I can put " High Plus " or " High+ "
in the priority for what we are definitely working on right now.  

At present I am putting all my exp in Fallen Angel Lucifer until he reaches 50 then I can evolve him.

I have several monsters listed at high as I need to work on them. Please let me know if this is do-able or if I should change all the Highs I have to Med and just use High for the one or two Monsters  I am presently working on?

I am also confused on how I can chose High, Med, Low or Zero editing the monster; but in the filter I can chose all of those and also " Done ". How can I edit the monster so it so it shows the priority - " Done " ? I am assuming that " Zero " is presently being used for finished monsters I don't want to level or evolve further.

I do think a lot of users would like this feature.  

Also is there any place to find basic instructions for Padherder?

Kittra :)        <-- That is my user name in the game and I use Kittra on Padherder
ID: 352,150,376

**Comment by pingon** [comment]
What I would love to see is a TOP priority.  Like these are the cards, above all other cards, that I really want to dump my exp in.  Like I need to level my Vulcan and ur so that I can evo them and make my Minerva finally.  

I like having low, med, high but just want that extra bit for top, so I could sort and say "man, I should really look for the super ruby" or whatever.  Thanks!

**Comment by madcowfred** [comment]
The "please for the love of god add more priority levels" comes up fairly often and is currently tracked in #490. I've made some progress on it but there is still a lot of things to update and test :(

'Done' is an automatic thing when a monster is at max evolved (or has no future evolution selected) and at max level (or current level >= target level). It's not explained anywhere at all how this works.

There are currently no basic instructions, I think there really needs to be some sort of "Hi there, new user - click here to view some help on getting started". I'll make a new issue for that so I remember.
