### ISSUE TITLE
Kenshiro's leader skill calculated incorrectly

### ISSUE THREAD

**Issue by grencez** [madcowfred/padherder-issues#638]
Number 1861: "Attacker type cards ATK x1.2, RCV x1.2. ATK x3.5 when attacking with 4 of following orb types: Fire, Water, Wood, Light & Dark."
Two things are being calculated incorrectly on the team building page:
- The 1.2x ATK boost is not being applied.
- The 1.2x RCV boost is applied as 12x.

**Comment by madcowfred** [comment]
Should be fixed, typo/brainfart when adding it.
