### ISSUE TITLE
Unlink account problem

### ISSUE THREAD

**Issue by Thelmecle** [madcowfred/padherder-issues#639]
Hi ! 
 I got a probleme, first I never received the mail of confirmation for link my two account.
I waited and now they have the status expired but i can't unlink them. 
I tried on the two account and I tried to re-send the link but it's impossible too.
How can i do to unlink them ? Someone have the solution ?

**Comment by madcowfred** [comment]
Same bug as #520, hope to get to it this weekend.

**Comment by madcowfred** [comment]
This should be fixed now.
