### ISSUE TITLE
Adjustment to My Monsters filters logic

### ISSUE THREAD

**Issue by incrediblehulf** [madcowfred/padherder-issues#64]
Filters could default to ON, as they do already, but clicking one would leave it ON and it would turn the others in that category (element/priority/type) OFF.

This would make things easier since you usually are trying to view only the clicked category when using the filter as opposed to viewing everything except that category.

If that's too much of a pain to code, an ALL ON and ALL OFF button could be an alternative to the current RESET button, though the first method is more intuitive for the user.

**Comment by madcowfred** [comment]
There's actually already a way to do this, hold Shift and click a button to select only that one. I'll add some sort of hover tooltip since it was only briefly mentioned in a news update :dog:

**Comment by kidoblivious** [comment]
I also have a problem on my tablet: how do i shift click?

I presently have to whittle down my monsters, single click per category. To select the sort you want to filter to seems more natural to me, then adding categories back, per column.

**Comment by madcowfred** [comment]
Sounds reasonable enough, I'll add it to the list of things to do when I have some time.

**Comment by madcowfred** [comment]
Just pushed this live - clicking a filter when that entire filter group is enabled will disable all except the one you clicked.
