### ISSUE TITLE
missing uvos - 4/29 (jp)

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#640]
http://pad.skyozora.com/pets/2075
http://pad.skyozora.com/pets/2083
http://pad.skyozora.com/pets/1738
http://pad.skyozora.com/pets/1739
http://pad.skyozora.com/pets/1954

**Comment by madcowfred** [comment]
Added and hopefully evolutions.

**Comment by ngamber** [comment]
Durga and Meimei aren't active for me.

**Comment by madcowfred** [comment]
Ah, new bug in the update process. They should be active now.

**Comment by ngamber** [comment]
Thanks!
