### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by selynna** [madcowfred/padherder-issues#641]
I can't seem to log in to padherder.  I've reset my password twice and I know for sure that I'm typing it in right but it keeps giving me the "Your username and/or password are incorrect, please check them and try again."  Is there something I can do about this?

**Comment by madcowfred** [comment]
Are you using your _username_ and not your email address? They're different things!

**Comment by selynna** [comment]
I've tried both my username and my password

**Comment by madcowfred** [comment]
Send me an email (freddie at padherder.com) with your username and I'll poke at it.

**Comment by selynna** [comment]
Will do.  Thanks!

**Comment by madcowfred** [comment]
Problem solved.
