### ISSUE TITLE
Valkyries Evos  shown  duplicated  at "My Sets"

### ISSUE THREAD

**Issue by JamesCID** [madcowfred/padherder-issues#647]
Hi,   I  notice  the valkyries  are double  listed  when you click  on them  at "my  Sets"

  Pic  is showing  them  :: 

![valks](https://cloud.githubusercontent.com/assets/9942104/7669093/f05d3a06-fc25-11e4-879b-8e20b82f865f.PNG)

I  do have  two  UUevo  Blue vals  and 3  base ones,  so the bug seems to be affecting just  the  base forms  of the colored valkyries  and the  third  form   of the regular lvalk.  They are also  listed  twice   just  under that.

**Comment by madcowfred** [comment]
Finally fixed.
