### ISSUE TITLE
Add Skillup Watch

### ISSUE THREAD

**Issue by thismightberyan** [madcowfred/padherder-issues#65]
During certain events where skill ups are ample, put alerts similar to those for weekday dungeons if the player have monsters that can benefit from those skill ups.

Events could include colab events, the daily dungeons for swordsmen/naga/breakers/vamp, or even Samurai dragon dungeons for the appropriate Ninjas.

**Comment by madcowfred** [comment]
Probably not going to add this, the effort:reward ratio is pretty bad (it would involve parsing pages and a lot more JS). PuzzleDragonX/PAD Wiki usually have a good list of active/upcoming events and they like visits too :cow:
