### ISSUE TITLE
Ultimate Plessie evos appears twice for possible Plessi evolutions

### ISSUE THREAD

**Issue by mccool37** [madcowfred/padherder-issues#651]
Both in the alternate evolutions and the evolution chain, numbers 1920 and 481 appear twice each. If one UVO is reached then both of that set is eliminated but the message' 2 alternate evolutions' appears instead on 1 (IE. I have #481 so #1920 appears as two different possible alternate evolutions)

**Comment by madcowfred** [comment]
Probably the same bug as #647
