### ISSUE TITLE
Theurgia's leader skill does not apply a multiplier

### ISSUE THREAD

**Issue by mike-tesch** [madcowfred/padherder-issues#655]
Multiplier should be 2.5x for fire, 1.4x for water, 3.5x for fire/water monsters. It looks like it doesn't apply any multiplier.

**Comment by madcowfred** [comment]
This (and a few other leader skills) requires some new magic to support. If you actually have this monster, does a fire/water monster get all 3 multipliers or just the biggest one?

**Comment by mike-tesch** [comment]
Fire/water monsters get 3.5x only. They effectively just receive the 1.4x \* 2.5x = 3.5x. It might be worth checking out the other monsters in the Grimoire series, they work the same way.

**Comment by madcowfred** [comment]
Oh dear, I thought they worked in a much more annoying fashion than that. Fixed :\

**Comment by mike-tesch** [comment]
I'm noticing that there is a multiplier now, but I'm not sure if that is due to your change or just because I didn't notice it before. It looks like only the water 1.4x is applying. If this is just because you haven't pushed your changes live yet, let me know.

https://www.padherder.com/user/idconvict/teams/#148775

This team should have a 3.5x \* 3.3x multiplier for Theurgia. So her attack should be 17625. Gigas should have 2.5 \* 3.3 \* 1391 = 11475 attack, etc.

**Comment by madcowfred** [comment]
Dumb typo, this should really work now. Honest.
