### ISSUE TITLE
Suggestion: More statistics in "My Team" page

### ISSUE THREAD

**Issue by nevets1219** [madcowfred/padherder-issues#658]
An improvement for the lazy!

For row enhance teams, it would be nice to see how many row enhance (of what type) that is in the team. Similarly a count of "Skill Boost" would be helpful (maybe with some sort of marker noting which skills is immediately available). Same goes for most of the awakening skills.

http://www.puzzledragonx.com/en/article.asp?aid=4

**Comment by madcowfred** [comment]
Duplicate of #577, closing this (and working on the feature, honest).
