### ISSUE TITLE
new monsters & uvos [JP] (6/2)

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#662]
http://www.puzzledragonx.com/en/whatsnew.asp?d=060215

1848 and 1849 are rare invades (horsemen set?)

**Comment by madcowfred** [comment]
Updated.

**Comment by ngamber** [comment]
Awoken Haku isn't showing up.

**Comment by madcowfred** [comment]
Oops, missed that one. Should be done now.
