### ISSUE TITLE
LKali name is still displaying the Japanese name

### ISSUE THREAD

**Issue by mccool37** [madcowfred/padherder-issues#664]
The current name that is displayed is '綺羅の秘女神, Kali' however, the name in the english versions of the game is 'Sparkling Goddess of Secrets, Kali'
Thank you very much.

**Comment by ngamber** [comment]
specifically, this is 1747. Looks like the rest of the ults in that batch are displaying fine for me.

**Comment by madcowfred** [comment]
Updated.
