### ISSUE TITLE
Dark Izanami doesn't show up in my materials

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#667]
I've got several kagus set for awoken evo and she doesn't show up on the materials page.

**Comment by madcowfred** [comment]
Hrm, confirmed and investigating.

**Comment by madcowfred** [comment]
Wait, nope. If you have "Grouped by dungeon" enabled she's in the "Descended" group, and somewhere in the giant "Rarely used materials" group otherwise.

**Comment by ngamber** [comment]
Ah, sorry about that. Looks like a lot of the other ones are in the wrong place then, I'll open a separate issue.
