### ISSUE TITLE
fix Fist of the North Star REM display on sets page

### ISSUE THREAD

**Issue by m1s3ri** [madcowfred/padherder-issues#668]
the title doesn't fit in the box at 100% or 75% zoom, it's really ugly and detracts from using the Sets page as a showcase of your collection

http://puu.sh/id9Z8/43aa2da785.jpg this is 75% zoom

**Comment by madcowfred** [comment]
Changed to "Fist of North Star REM" which is kind of goofy but probably fits better :(
