### ISSUE TITLE
Renaming 'MAX' priority to something else (maybe Done)?

### ISSUE THREAD

**Issue by bleeben** [madcowfred/padherder-issues#67]
Currently 'MAX' is an automatic setting, even if you have it set at Zero priority, which distracts from what should be your highest and higher up priority monsters. I feel like it would make more sense to have them be automatically set to 'Done', but sorting lower than Zero priority.

Or, have them set to 'Max' or 'Done', but keep them stored and sorted as whatever user preferred priority setting? To differentiate the user situations between a MAX Horus versus a MAX Flame Knight, for example.

**Comment by madcowfred** [comment]
There probably needs to be an option to control where they're sorted - top/bottom/normal. I'll have a poke at it.

**Comment by TyrAlduin** [comment]
Agreed, this is starting to become a bigger issue now that I have started maxing out levels on a few of my monsters. Some monsters are no longer a priority to me as I have nothing left I want to add to them (i.e. Blazing Ice Ogre, King Shynee/Bubblie) while others are still a top priority for adding +eggs to (i.e. Byakko).

**Comment by iscribble** [comment]
I've noticed this as well! This might be a separate issue, but it's not even consistent. 

For example in [this screenshot](http://imgur.com/RUz17TB)(JP), Why is 音符のしにがみ ("Death of Note") at MAX priority when メカドン ("Mekadon") is not?

**Comment by madcowfred** [comment]
That's an arbitrary 'minimum max_level' limit which I believe is set to 10. Basically anything that isn't at least that level isn't worthy of MAX.

Working on this ticket today :goat:

**Comment by madcowfred** [comment]
Added this - go to My Account and change 'Done position' to whichever setting takes your fancy.
