### ISSUE TITLE
Can't Login!

### ISSUE THREAD

**Issue by Hailsatan** [madcowfred/padherder-issues#670]
I can't find any other site or email for actual site technical issues, but I just created my account today. After a cache clear, it wouldn't accept my password. I've done 6 password resets and no matter what I change the password to, when I try to login, it says it is invalid. I would really, really love to use this site if I could only log in to it! Is there something wrong with the authentication system? Is my account locked (seems unlikely after 3 or 4 hours on-site)... Please help!

**Comment by madcowfred** [comment]
Are you using your _username_ and not your email address? They are different things.

**Comment by Hailsatan** [comment]
You rock / I am embarrassed! So embarrassed. Thanks!
