### ISSUE TITLE
#1620 Light Wizard, Rei Sirius picture does not show up in my monster box

### ISSUE THREAD

**Issue by kronos189** [madcowfred/padherder-issues#672]
as stated in title.  My monster box is here for reference https://www.padherder.com/user/Kronos/monsters/#31,0,31,2047,268435455,0,,0,0,0,eq,0,0,0,0,;boxfav,0

**Comment by kronos189** [comment]
this is an ongoing issue for several months despite browser changes, refreshes, cache clearing, etc

**Comment by madcowfred** [comment]
Fixed. It's hard to fix things like this without bug reports :|
