### ISSUE TITLE
Un-evolved Shieldra have skills

### ISSUE THREAD

**Issue by zably** [madcowfred/padherder-issues#674]
I don't remember exactly when, but a few patches back, the unevolved shieldra (numbers 1537, 1539, 1541, 1543, and 1545) were changed to have the same skills as their evolved counterparts.  

It's a pretty minor bug for something no one uses, but I'm reminded of it everytime Padlistener tries to update my skill level 2 guy.

**Comment by madcowfred** [comment]
Updated.
