### ISSUE TITLE
Baby Tamadra not in Monsters but shows when hovering ingredients

### ISSUE THREAD

**Issue by qvinhd** [madcowfred/padherder-issues#680]
Hello,

I added some tamadras long time ago under Monsters but it is no longer there. I readded them but it just keeps stacking on top of the previous ones, not showing up on Monsters. Therefore when i hover over the dragon plant for example it says i need those ingredients even though they are not showing up on my Monsters page. Any suggestions are appreciated!!

**Comment by madcowfred** [comment]
Try resetting your filters, they might be displaying weird?

**Comment by qvinhd** [comment]
That worked! Thank you so much!!
