### ISSUE TITLE
Bug: Can not configure sets to show top row of wizards without showing second set as well

### ISSUE THREAD

**Issue by boostedhp** [madcowfred/padherder-issues#682]
Under configure sets in order to get the configuration to display the top row of wizards you must select to have both rows appear.  If you only select only one of the two rows neither will display under saved configs.

**Comment by madcowfred** [comment]
Internally they're the same set, just automatically split due to size. I'd probably "solve" this by just not showing a checkbox for the 2+ sets.

**Comment by madcowfred** [comment]
"Fixed" this now by just not showing the hide checkbox for meta-sets. They also now have a (1) (2) on the end of their name. At some point sets should probably be more configurable to solve the actual issue here :(
