### ISSUE TITLE
XP gets reset if level and XP changed at same time

### ISSUE THREAD

**Issue by xtop** [madcowfred/padherder-issues#69]
Here's what happens:
1.  Edit monster.
2.  Change level and XP.
3.  Save monster.
4.  Level is fine; XP gets reset to the minimum XP for the level, rather than the entry made in step 2.

**Comment by incrediblehulf** [comment]
It says in the Add Monster form that a change to level takes priority over a change to XP. Setting XP changes the level for you automatically.

**Comment by madcowfred** [comment]
This is by design, change one or the other.
