### ISSUE TITLE
Fairy Tale set not showing secondary element on evolved cards

### ISSUE THREAD

**Issue by neskenazi** [madcowfred/padherder-issues#695]
#1413 Happy Forest Maiden, Red Riding Hood
#1415 Queen of the Dwarfs, Snow White
#1417 Four Leaf Clover Princess, Thumbelina
#1419 White Coach Princess, Cinderella
#1421 Thorn Princess, Sleeping Beauty

They all should have secondary element the same as their primary on the evolved forms, right now it's showing as only the primary without secondary element

**Comment by madcowfred** [comment]
Fixed
