### ISSUE TITLE
Monster names messed up for Shinrabansho Choco / BAO collab

### ISSUE THREAD

**Issue by DreadPirateShawn** [madcowfred/padherder-issues#697]
If you enter the IDs for BAO collab monsters (eg BAO Deathstroke, ID 932) then the expected BAO collab monster icon will appear, however beside it is displayed a monster name from the Shinrabansho Choco collab (eg "#932 US. Wafer Man").

![screenshot_collab-overlap1](https://cloud.githubusercontent.com/assets/1418951/8613853/69bb784e-2698-11e5-819f-f14d6d4656b3.png)

Also occurs for:
- #928 BAO Copperhead > Kobokkle
- #925 BAO Firefly + Flamethrower > Light Dragon King Saiga

Presumably others in that number range, those are just the ones I have in my account.

Might be worth noting, this does not occur for the older Batman collab, eg "#672 BAO Catwoman+C. Claw" appears just fine.

**Comment by kernigh** [comment]
These are also broken:
- #927 BAO S. Grundy Reborn > KOB Leonhart
- #929 BAo Venomous Copperhead > Bokkle

Also, the evolutions for Shinrabansho monsters are a mess.  PADherder doesn't know that Wafer Man and Dragon Stone switched to Enhance Material from Evo Material.  It doesn't know the new evolution recipes for monsters who no longer use Wafer Man or Dragon Stone to evolve. The "Edit monster" screens for #1049 Sacred Dragon King Saiga and #934 Exiled Apollo list some impossible choices for evolution, including an option to evolve Exiled Apollo into Batman!

**Comment by madcowfred** [comment]
This is all a side effect of the BAO Collab US vs JP numbering mess that is the bane of my existence.
- Fixed the naming mess.
- Fixed the evolution mess.
- Updated the monster types.
- Updated evolve materials.
