### ISSUE TITLE
RE: Awoken Egytian, Shinrabansho Collab, and PA Collab

### ISSUE THREAD

**Issue by zably** [madcowfred/padherder-issues#698]
I'm pretty sure you know about most of this stuff, so you can ignore this if it's all redundant, but I couldn't find any of this in the suggestion board after a quick search.

First, Awoken Ra (2012), Awoken Bastet (2011), and Awoken Horus (2009) seem to need their flags set to NA so they show up in the Sets page.

Secondly, Shinrabansho collab is throwing errors again due to the mess with overlapped number with the BAO collab.  A few examples:

![image](https://cloud.githubusercontent.com/assets/7295661/8640783/be6e6630-28d2-11e5-99de-9c9562a1573e.png)

![image](https://cloud.githubusercontent.com/assets/7295661/8640786/dc290158-28d2-11e5-885b-9acfd1f90321.png)

Lastly, are you planning on adding the new collab cards to sets like the previous ones?  I noticed you updated some minor stuff like the Bowl Demons recently, but maybe the extra REM pulls with Shinrabansho and Puzzle Academy take more work.

Thanks again for all your work.

**Comment by madcowfred** [comment]
Fixed the BAO mess, need to manually hook up some ultimates.

Sets get updated when people remind me to. Make a new issue with whatever you want added/changed and I'll get it done!

**Comment by zably** [comment]
Cool, I just didn't want to needlessly flood you with requests.

For Puzzle Academy, the REM set only includes 2014-2017, but you can probably add 2018 to collab bosses, and 2019 to collab invades.  Additionally, a bunch of new chibi cards 2020-2028 were released at the same time, dunno if you want to put them with chibi 3k or as part of the PA REM like the Christmas chibis.

For Shinrabansho collab, the REM set includes #'s 1967-1981, and you can probably add 1992/1993 to collab bosses, and 1994/1995 to collab invades.

**Comment by madcowfred** [comment]
Fixed the Awoken Egyptian JP-only flag and made the suggested sets changes. Thanks.
