### ISSUE TITLE
team description silently corrupts write-up with "<" and ">" characters

### ISSUE THREAD

**Issue by DreadPirateShawn** [madcowfred/padherder-issues#700]
In the "My Teams" section, if the description write-up matches `<.*>` regex, the matching region will disappear.

For instance, enter the text:

```
Fl1: Cannot survive if he attacks when <50%.
Fl2: Use Ronia > Luci > Lu Bu = OHKO.
```

Upon saving, this becomes:

```
Fl1: Cannot survive if he attacks when Luci > Lu Bu = OHKO
```

Worth noting, the data is indeed being lost, not just hidden upon display -- view source shows:

```
<td class="team-desc" colspan="9">Fl1: Cannot survive if he attacks when  Luci &gt; Lu Bu = OHKO.</td>
```

Presumably, all text entered into the description field should be escaped, rather than stripping what appears to be html markup (but totally isn't).

**Comment by madcowfred** [comment]
This was basically a quick hack to fix an "uhh did you know you can put arbitrary HTML into team descriptions?" report. Should be fixed now to correctly escape HTML entities.
