### ISSUE TITLE
#1339 Demon Slaying Goddess, Durga shows wrong icon

### ISSUE THREAD

**Issue by Casao** [madcowfred/padherder-issues#701]
image shown:

![screen shot 2015-07-16 at 5 16 39 pm](https://cloud.githubusercontent.com/assets/648055/8735399/735418e8-2bde-11e5-9a8c-83667ebce12b.png)

Should be:

![screen shot 2015-07-16 at 5 17 01 pm](https://cloud.githubusercontent.com/assets/648055/8735408/83e295a4-2bde-11e5-8630-0cc29ee9d9aa.png)

**Comment by madcowfred** [comment]
Fixed.
