### ISSUE TITLE
Wrong leader skill for Mistrain and Sagirinokami

### ISSUE THREAD

**Issue by kernigh** [madcowfred/padherder-issues#705]
These monsters have the wrong leader skill in PADherder:
- #1353. Storm Dragon, Mistrain
- #1354. Phantom Thunder Dragon, Saggirinokami

The name "Dragon Soul" is correct, but the effect is wrong. PADherder says, "While your HP is 70% or above, a single hit that normally kills you will instead leave you with 1 HP. For consecutive hits, this skill will only affect the first hit."

The correct effect in game is "2x ATK & RCV for Dragon Type"

**Comment by madcowfred** [comment]
This is finally fixed.
