### ISSUE TITLE
new uvos 'n stuff (JP)

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#706]
http://www.puzzledragonx.com/en/whatsnew.asp?d=073015 - apollo/okuni uvos, new pantheon, nepdra
http://www.puzzledragonx.com/en/whatsnew.asp?d=072415 - new descend

**Comment by ngamber** [comment]
Not seeing them active, maybe needs a redeploy?

**Comment by madcowfred** [comment]
Should be active now, looks like a) the PDX pages for Apollo/Oku ninja sushi are very broken, and b) the deploy failed due to 2250's weird new monster type. Sigh.
