### ISSUE TITLE
Adding Aamir and Tackling Durga Issues

### ISSUE THREAD

**Issue by megancs601** [madcowfred/padherder-issues#710]
Just need to add Aamir ( "Aamir" No. 2068 & "Black Beast Demon's Servant, Aamir" No. 2069). Also, add the English translation of Durga's Ultimate (" Magic Hand Slayer Goddess, Durga "). I have Ultimate Durga in "My Monsters" list but it wont show up in "My Set" list,

Btw I really like PADherder :)

**Comment by madcowfred** [comment]
Should be fixed.
