### ISSUE TITLE
My Sets - Awoken Shiva

### ISSUE THREAD

**Issue by jpslayug** [madcowfred/padherder-issues#711]
Hi All,

I had a F/D Shiva that I evolved to Awoken Shiva.
Awoken Shiva is showing up properly in My Monsters, but it's not showing up in My Sets.
I even tried to add a 'placeholder' in My Sets, but it still won't show up (so I erased it).

Also, just noticed: I have 1982 Mashiro Kagato but he's not showing up on My Sets either.
It seems like it's looking just for 1983 Raging Kagato.

Thanks again for all you guys do!

**Comment by madcowfred** [comment]
Both fixed.
