### ISSUE TITLE
Durga Team Multiplier Not Applying

### ISSUE THREAD

**Issue by megancs601** [madcowfred/padherder-issues#712]
Sorry to bother you again about Durga, but I noticed that Durga's 5x leader skill isn't being applied to the Total ATK calculations in My Teams. My Kirin and Isis attack multipliers are fine. It's just Durga that has this issue.
![untitled](https://cloud.githubusercontent.com/assets/11465416/9122284/fa3932da-3c55-11e5-931a-5787c64dafd7.png)

**Comment by madcowfred** [comment]
Fixed.
