### ISSUE TITLE
Menu Covering Add Monster and Part of list

### ISSUE THREAD

**Issue by xedis** [madcowfred/padherder-issues#719]
Looks like this is the same issue that occurred with the mobile site in Issue #548 only this is happening in Chrome on Ubuntu 15.10 . If I am quick enough I can snag the button on a refresh but is no means optimal =/ Happens in all pages just with different stuff being covered....this is the main one though

Thanks for all the hard work you have done on the site its really useful when helping friends!!
![image](https://cloud.githubusercontent.com/assets/4144634/9292517/fcbbb79e-43b2-11e5-8a8e-39900400957c.png)

**Comment by xedis** [comment]
I figured out what it is.... if i auto-hide the taskbar it fixes it like so...

![image](https://cloud.githubusercontent.com/assets/4144634/9293679/b1289eba-43e8-11e5-8cde-ab8703724d41.png)

leaving open in case it is something you can fix really quick,,, otherwise don't worry about it close it and anyone can reference it here for the quick fix.

Edit\* Also the top monster on the list is still hidden along with the column names

**Comment by madcowfred** [comment]
Looks like it's just that "Super Dragon Infestation!" is a longish dungeon name and your screen is just wide enough to not trigger the compacted navbar. Whee. I've committed a change that should hopefully help a little.

Also, if you click the 'Filters:' text and Reset/Save as default it will fix the stupid Type=(blah) spam making the other bar huge :<
