### ISSUE TITLE
Freddie, Are You Alive?

### ISSUE THREAD

**Issue by FaxCelestis** [madcowfred/padherder-issues#726]
Haven't seen a news post from you for ages. You cool? Need help?

**Comment by madcowfred** [comment]
Been busy with work and being sick and traveling for work and getting sick while traveling. Also sometimes I sleep. There's not really any news to post beyond 35 "Updated some monsters" tickets :dog:

**Comment by FaxCelestis** [comment]
Just making sure you're doing ok. Glad to hear work is keeping you busy, though. It's a blessing and a curse all in one!
