### ISSUE TITLE
Extra evo options on mystic knights

### ISSUE THREAD

**Issue by kidoblivious** [madcowfred/padherder-issues#73]
Nice that the Ultimate Evo of the mystic knights is supported, however they seem to be listed as an option for my Dragon Knight and my Dark Dragon Knights (which I have in 2nd form as well as 3rd for historical Balance reasons). (Adding a phoenix knight also allowed me to select the Ult Evo, so I would extrapolate it to apply to the other two (naturally perhaps)

Thanks for Herder! :)

**Comment by madcowfred** [comment]
This is actually intended and part of some work on resolving other issues (GH-18, GH-57) - the ability to pick a future evolution and see the entire evolution chain, including material requirements.
