### ISSUE TITLE
Req: Latent awakening support

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#733]
Would be handy to record this somehow. Not a huge priority for me personally, but y'know.

**Comment by madcowfred** [comment]
Do you have any latent awakenings and a JSON dump? That would be useful to finish this.

**Comment by ngamber** [comment]
Someone gave me the array for latents, I'm still asking around for a full json dump, otherwise I can work on getting burp setup when I have time. 

http://pastebin.com/pTYRtaNE

This is apparently an amaterasu with 3 imp. RCV awakenings:

 [31,4000000,99,3,26,1557,58,72,99,5,50741]

and Gigas with one Imp. HP: 

[14225,2905708,87,7,27,512,0,0,0,1,21]

**Comment by madcowfred** [comment]
Hm, that's weird - 21 for an Imp HP is an odd value, and 50741 for 3 Imp RCV isn't much less weird.

**Comment by madcowfred** [comment]
Need some more data points to work out what they're doing, boo.

**Comment by madcowfred** [comment]
Duhhh.

50741 = 00011 (RCV) 00011 (RCV) 00011 (RCV) 0101 (flags?)
21 = 00001 (HP) 0101 (flags?)

**Comment by Raijinili** [comment]
My data fits that interpretation.

```
        69              4 0101 finger
   2164805     4  4  4  4 0101 finger finger finger finger
     84565        5  5  5 0101 heal heal heal
      2613           5  3 0101 heal rcv
  17877589  1  2  3  5  5 0101 hp atk rcv heal heal
      2117           4  4 0101 finger finger
  69273669  4  4  4  4  4 0101 finger finger finger finger finger
      2581           5  1 0101 heal hp
     16917        1  1  1 0101 hp hp hp
  86592085  5  5  5  5  5 0101 heal heal heal heal heal
```

I haven't found anyone with a flag other than 0101 (= 5). Maybe it just says "out of five"?

(Note the push order.)

**Comment by madcowfred** [comment]
OK, support for this is all in:
- New Latent column on My Monsters
- Latent support in the add/edit dialog
- New latent1/latent2/latent3/latent4/latent5 fields in the API endpoints
- HP calculation in various places is hopefully accurate (monster image popovers + team calcs)
- Latent awakenings display on team members and in the Awoken summary
