### ISSUE TITLE
New monsters available in NA (9/3)

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#734]
Shivadra, Mythical Beast Riders, Mech-Beasts, Mech-Dragons (Mecha dragons?) and new dragon caller exclusives. 

Names seem to be translated for some, but setting my sumires/satsukis to level 50 unevolved set them as DONE, which isn't expected behavior.

**Comment by madcowfred** [comment]
Partially done, don't have NA data for some of this stuff. Also not sure what "Mech-Beasts" includes :cactus:

**Comment by zably** [comment]
Mech-beasts are 2185-2189, Mech-dragons are 2190-2194 (maybe you have those already though).

**Comment by madcowfred** [comment]
Updated those now, thanks.

**Comment by ngamber** [comment]
I guess PDX is referring to them as "Cyber Beast" and "Cyber Dragon" but w/e.

**Comment by madcowfred** [comment]
This should all actually be done now.
