### ISSUE TITLE
Max level + Ultimate = "Done", even if marked for unevolving

### ISSUE THREAD

**Issue by Raijinili** [madcowfred/padherder-issues#737]
Level 99 L/F Apollo is marked for evolving to L/W Apollo, but is considered "Done".

I have "Don't suggest alternative ultimate evolutions" on, if that matters.

**Comment by ngamber** [comment]
Probably because L/W Apollo is marked as JP-only and your account is set to NA. Workaround is to set it to level 98 or set your account to JP : ¯_(ツ)_/¯

**Comment by Raijinili** [comment]
Tested with a level 99 L/F Amaterasu -> L/L Amaterasu. It's not just due to the region.

**Comment by Raijinili** [comment]
Related: #694

**Comment by styloplume** [comment]
I have the same issue with Freyr and Haku, shown as done while being set for reverse evo + new evo.
And I do have alternate uevo suggestions on.

**Comment by madcowfred** [comment]
Should be fixed now.
