### ISSUE TITLE
Allow (Evolve/Enhance) Material cards in teams.

### ISSUE THREAD

**Issue by Raijinili** [madcowfred/padherder-issues#738]
PDX now allows them:
http://www.puzzledragonx.com/en/simulator.asp?q=1176.1.1.0.0.0.0..432.1.1.0.0.0.0..432.1.1.0.0.0.0..432.1.1.0.0.0.0..432.1.1.0.0.0.0..1176.1.1.0.0.0.0

**Comment by Meldarion** [comment]
They already can be, provided you've added them to "My Monsters" and not just "My Food" or "My Materials"
(I have a team saved that uses Mystic Masks: https://www.padherder.com/user/meldarion/teams/#175150 )

**Comment by Raijinili** [comment]
Oh, never mind, then.

I update with JSON. Maybe I should make a concrete issue about that.
