### ISSUE TITLE
Class Monitor Athena Duplicates

### ISSUE THREAD

**Issue by zably** [madcowfred/padherder-issues#739]
Regarding #725, I think he meant that there are duplicate entries for Athena 2015 and 2016 in the sets page not when clicking on the spot, but that there's actually two "spots" for the same card in the set.  One is an ult-evo of the other, so maybe both were added accidentally.  Here's an example:

![image](https://cloud.githubusercontent.com/assets/7295661/9723543/7222fb7e-5591-11e5-927b-49f3d2f016af.png)

It's slightly different from the duplicate Valkyrie bug, which only shows up when open the menu with a click.

**Comment by madcowfred** [comment]
Fixed.
