### ISSUE TITLE
Xiao Qiao's HP buff incorrectly applied

### ISSUE THREAD

**Issue by styloplume** [madcowfred/padherder-issues#740]
Hello, thanks for the website, much appreciated :)
It seems XQ's leader skill is incorrectly applied to healers' HP.
Definitely not 1.25 x 1.25 (for leader + helper) but more like 1.2 x 1.2.
Anyway, XQ leader/Healer sub 1/Sub 2/Sub 3/Sub 4/XQ helper gives wrong total HP.
Thanks in advance !

**Comment by madcowfred** [comment]
Fixed, it used to be 1.2x according to my data :\

**Comment by styloplume** [comment]
It did, don't know when it got buffed as I only got XQ recently. Thanks a
lot !

2015-09-10 2:13 GMT+02:00 Freddie notifications@github.com:
