### ISSUE TITLE
JSON import mix up for Batman collab and Shinrabansho

### ISSUE THREAD

**Issue by styloplume** [madcowfred/padherder-issues#741]
Hi again, I've seen a couple of issues already dealing with the Batman/Shinra mix up.
However, JSON import still has an issue : Shinra cards are imported as Batman cards
and vice versa. Any chance you'll fix this ? Thanks !

**Comment by Tito151** [comment]
In my PADHerder, King Saiga is showing up as Catwoman, but it's just the picture.  The PADX links and ATT sorting still works properly.

**Comment by madcowfred** [comment]
Hm, I just went in to the code to fix the JSON import thing and it looks like it should work... for NA people. Is your account set to something else?

**Comment by styloplume** [comment]
Yeah, I'm in EU, want me to give it a try ?

**Comment by styloplume** [comment]
I can confirm it still doesn't work for EU.
The import log says #671 Sacred Dragon King Saiga has been created.
The monster box shows it as #1049 US. Sacred Dragon King Saiga and links to
padx #1049.
(#671 being Catwoman)

**Comment by madcowfred** [comment]
Should be fixed now.

**Comment by styloplume** [comment]
Indeed, thanks :)

**Comment by Tito151** [comment]
All good for me too!  Thanks.
