### ISSUE TITLE
Missing monsters for My Sets section

### ISSUE THREAD

**Issue by anhvo1977** [madcowfred/padherder-issues#745]
1. Scarecrow needs to be added to Collab boss for Batman 2: http://www.puzzledragonx.com/en/monster.asp?n=2138
2. Zhu Bajie needs to be added to Decended boss for Sha Wujing & Zhu Bajie Descended!: http://www.puzzledragonx.com/en/monster.asp?n=2183

Thank you.

**Comment by madcowfred** [comment]
Added Scarecrow, Zhu Bajie seemed to already be in there.
