### ISSUE TITLE
Save function isn't working in Firefox

### ISSUE THREAD

**Issue by nocutename** [madcowfred/padherder-issues#746]
I am using Firefox 40.0.3.  When I go to save a monster under "my monsters" I am getting:

Error: 403 {"detail": "CSRF Failed: CSRF token missing or incorrect."}

When I got to save under "My teams" nothing happens.

These work fine in Explorer browser.

**Comment by madcowfred** [comment]
Try logging out and back in. Not sure what would cause this, maybe cookies disabled or something? :|
