### ISSUE TITLE
Invisible Baby Tamadras

### ISSUE THREAD

**Issue by walruscake** [madcowfred/padherder-issues#747]
I added 4 baby tamadras to the 'My Monsters' section a few weeks back when I created my PADHerder. Later I realized there was a slot in 'My Food' for them, so I deleted them from 'My Monsters'. I've since removed the 4 from 'My Food' as well, but my account seems to think they're still around. The counters for my materials still mention the monsters needed to evolve the 4. (IE: My Dub-Topalit count still says I need 4 Dub-topalits to evo the 4 baby tamadras.) Where be they hidin'?

**Comment by choowy** [comment]
As far as I can tell, "Awoken materials" and "vendor" are hidden by default in your box. Baby TAMADRAs fall under awoken materials.

My Monsters, open Filters drop down menu, click awoken materials and you should find your baby TAMADRAs.

**Comment by walruscake** [comment]
Oops, that did solve it. Sorry for the trouble. Thank you for walking me through that!
