### ISSUE TITLE
API issues with cyber beasts and cyber dragons

### ISSUE THREAD

**Issue by JamesCID** [madcowfred/padherder-issues#759]
Apparently the ID  or a tag is wrong with them,  since PADListener can't parse the data properly and captures them all with ID 00 and the export csv function don't list them either 

Cyberdragons are #2185-2189 and Cyberbeasts are #2191-2194

**Comment by madcowfred** [comment]
They look basically correct at a quick glance :\

**Comment by QuasiTD** [comment]
I have a Markab(cyberbeast), #2190. I was able to add it manually to padherder, but padlistener isn't recognizing it and won't update it or upload it in the first place.

**Comment by madcowfred** [comment]
It's a PADListener bug where it didn't support Mech/Vendor types. https://github.com/Neraud/PADListener/issues/86
