### ISSUE TITLE
Evo Materials (Keeper of Rainbow/Dub-mythlit) have 1/1/1 stats on the Team view

### ISSUE THREAD

**Issue by wshsu314159** [madcowfred/padherder-issues#76]
I placed my Rainbow Keeper on a team as a dark sub, but its stats appear as 1/1/1 rather than the expected 3000/1000/150-ish.  This also occurs with the Dub-mythlit, and is strange as these two are often explicitly used as newbie stat sticks.  This seems to occur for all Evo Materials.

I suppose one can argue that a padherder user is not a newbie and should have access to better dark/stat mons?

**Comment by madcowfred** [comment]
Fixed.
