### ISSUE TITLE
Bug with Sakuyas' cards

### ISSUE THREAD

**Issue by sadielai** [madcowfred/padherder-issues#763]
Been trying to evo my Sakuya to L/L but it keeps giving me an error. I even tried adding a new version of her and it still doesn't work. Tried it on both Firefox and Chrome.
![screen shot 2015-10-02 at 9 09 11 am](https://cloud.githubusercontent.com/assets/13183732/10270522/754b3cd0-6aa9-11e5-9d67-7990d15da5a5.png)
![screen shot 2015-10-02 at 9 09 34 am](https://cloud.githubusercontent.com/assets/13183732/10270523/755b6704-6aa9-11e5-8cb4-f0fea00d2766.png)
![screen shot 2015-10-02 at 9 09 40 am](https://cloud.githubusercontent.com/assets/13183732/10270524/756e2114-6aa9-11e5-8c76-80ff43b51902.png)

**Comment by zably** [comment]
This happens sometimes when you already had a card added and a new evo comes out afterwards. Two things that worked for me were either:

1) Manually change the evo to a different one and back (so in your case, switch to the Awoken Sakuya evo, then back to L/G evo)

2) Delete and readd the card from scratch.

**Comment by sadielai** [comment]
Adding Awoken Sakuya and changing back to evo worked for me. Thank you!
