### ISSUE TITLE
Bean starters can't evolve

### ISSUE THREAD

**Issue by ghost** [madcowfred/padherder-issues#766]
Monsters Tyrra-bean(#1929) Plessie-bean(#1930) and Brachy-bean(#1931) evolutions don't show up. A quick google search reveals that the evolutions are not up on PaDX, but they evolve at Level 5, requiring nothing more than a single Dragon Seed.

**Comment by madcowfred** [comment]
This kind of makes PADherder angry because it assumes that evolving to a lower MonsterID is a backwards step :( I'll look into fixing it.

**Comment by madcowfred** [comment]
I've added them from the wiki and also fixed a weird bug making the evolutions not work. Success.
