### ISSUE TITLE
Evolution requirements not displaying properly

### ISSUE THREAD

**Issue by Artemyst** [madcowfred/padherder-issues#77]
Evolution requirements not displaying properly and also unable to evolve monster when it shows "1 evolution available!"

![capture](https://f.cloud.github.com/assets/5662733/1313223/791abdb8-3252-11e3-907b-387f0522c935.PNG)

**Comment by madcowfred** [comment]
The "1 evolution available!" message means you have to edit the monster and pick an evolution. It's currently bugged and (sometimes) ignoring the selected evolution when adding a new monster :(

**Comment by Artemyst** [comment]
That did the trick. Thank you!

**Comment by madcowfred** [comment]
I've fixed the bug that was causing this specific issue.
