### ISSUE TITLE
Exp curve for MP Dragons

### ISSUE THREAD

**Issue by Neraud** [madcowfred/padherder-issues#770]
The monster API is reporting incorrect exp curve for these monsters.

For example, Destroyer God, Shiva Dragon (id 2253). 
Reported  "xp_curve": 9990000
Expected : "xp_curve": 9999999

**Comment by madcowfred** [comment]
Fixed.

**Comment by ngamber** [comment]
There's also a 16m (iirc)  curve for mech hera now.
