### ISSUE TITLE
Suggestion - Add Mp Sell value to popup

### ISSUE THREAD

**Issue by jemer99** [madcowfred/padherder-issues#773]
Now that things are worth mp, I'm sure you can get this data from padx and then display it in the toottip.  Would make cleanup even better since I'm trying to see what cards i want to sell off.

Thanks

**Comment by ngamber** [comment]
This exists elsewhere kinda:

http://pad.allthings.moe/lookup

**Comment by madcowfred** [comment]
Added this to the monster popovers.
