### ISSUE TITLE
JSON import no longer deletes monsters not in the box

### ISSUE THREAD

**Issue by styloplume** [madcowfred/padherder-issues#780]
This only started recently but I've noticed that some monsters are not deleted from my padherder
despite them being gone from my box. It happened on a snowglobe dragon, moltdras, empress god izanami and various dungeon drops. Any idea what's going on ?

**Comment by madcowfred** [comment]
I made some changes recently in #603 to track monsters using PAD's internal ID ('cuid' in the JSON), it's entirely likely that I broke things there. I'll take a look.

**Comment by jgoldshlag** [comment]
Any luck finding the issue? This bug means my monsters just keep growing and growing. Is the internal ID in your API? If so, I might want to write my own import script I guess

**Comment by izenn** [comment]
I am also having this issue -- is there any chance of you releasing the source so the community can help find/squash bugs?

**Comment by madcowfred** [comment]
Should be fixed now.

**Comment by styloplume** [comment]
Happy new year !

I've checked my whole box versus my padherder after a new import.
I got only one issue : 1 Shimonita Leek in box vs 3 in padherder.
Other than that things look good, and I've noticed you now upgrade monsters
to their new evo if they have evolved in game, that's wonderful :)

Thanks a lot !

2016-01-01 12:48 GMT+01:00 Freddie notifications@github.com:
