### ISSUE TITLE
A few more new things available in NA

### ISSUE THREAD

**Issue by zably** [madcowfred/padherder-issues#783]
Artemis has a new ult #2237

Amaterasu and Yomi have new awokens, #2324 and #2325

Additionally, the Angel/Reaper invades are out now, is there some place to stick them in sets?  I noticed they weren't in the JP sets either, and there's only two, so maybe not.  They're #1848 and #1849 if you wanna take a look.

Lastly, Nordis is supposed to come out later today, #1844-1845, but maybe I'm jumping the gun.

**Comment by madcowfred** [comment]
Updated monsters, added a weird set.
