### ISSUE TITLE
Final Fantasy Collab out in NA

### ISSUE THREAD

**Issue by zably** [madcowfred/padherder-issues#788]
Not sure if you need numbers for cards that are out in JP?

REM includes #2029-2050.

Collab Boss is #2058-2059.

**Comment by TheBaddest** [comment]
Final Fantasy collab includes #2029 to #2066 (all REM, Fat Chocobo, and dungeon mobs) and #2084 is Fat Chocobo's evolution.

**Comment by madcowfred** [comment]
Apologies for how long this took to get to, I was out of the country :(

**Comment by zably** [comment]
No problem, we still love you.
