### ISSUE TITLE
Team page: "Maxed Stats" button de-evolving monsters

### ISSUE THREAD

**Issue by cwmajors** [madcowfred/padherder-issues#789]
I have an Awoken Isis in a team, and when I view "Maxed Stats", it devolves into a Blue Moon Sea Deity, Isis.

**Comment by zably** [comment]
Did you check what your target evo is?  Maxed stats takes that into account and will de-evo appropriately if you have a devolved version as your target.

**Comment by madcowfred** [comment]
What he said, 'Maxed stats' will set monsters to their selected target evolution.
