### ISSUE TITLE
Delete multiple monsters at once?

### ISSUE THREAD

**Issue by ghost** [madcowfred/padherder-issues#793]
Sorry I'm new at GitHub, I don't know if this is the right place to ask.

Is there a way to delete multiple monsters at once? PadListener syncs all of my descend drops/skill up fodders automatically and I don't want them to show up in my PadHerder. Deleting them one by one is really tedious, is any way to select multiples and delete them at once? Or like a similar interface like Evo Mats so I can just put 0 for their number?

**Comment by madcowfred** [comment]
This is the right place to ask - people have been asking this for quite literally years at this point :( Duplicate of #238
