### ISSUE TITLE
Suggestion: Criteria for "done" should include awakenings OR manual "done/not done" option

### ISSUE THREAD

**Issue by dumdummuoi** [madcowfred/padherder-issues#795]
Awakenings are such an integral part of the meta now, perhaps max level/max evolved monsters that don't have all their awakenings should not be marked as "Done" anymore. I would like to see targets for Tamadras correctly sorted by the priority I've given those cards.

Alternatively, a solution could be to allow users to manually override the "doneness" of each monster set by the system.

**Comment by madcowfred** [comment]
Seems reasonable enough, changed to require max awakenings.

**Comment by madcowfred** [comment]
This still exists, it's now an option in My Account as per #803
