### ISSUE TITLE
Bulk monster tracker

### ISSUE THREAD

**Issue by pfayze** [madcowfred/padherder-issues#8]
I'd love to be able to track how many of each un-evolved Pengdra I have so I can easily see how many Dragon Plants I need across all the colors. Similarly, I have dozens of CoC Barbarians that I want to evolve to skill up Thor, but it's annoying to have one entry for each. A simple quantity field would be much appreciated :)

**Comment by madcowfred** [comment]
Unsure about this - the My Monsters table is already quite wide and I'd prefer to slim it down rather than add things.

**Comment by pfayze** [comment]
They could be separated somehow, perhaps with a new priority "Material"? Or perhaps a special section for pengdras at least? I keep track in a spreadsheet how many dragons and pengdras of each color, as well as how many seeds total.

**Comment by jarch3r** [comment]
These changes would make padherder too high maintenance. It doesn't need to track the usage of every single dragon plant and pengdra. The monster box and basic addition seem just fine.
