### ISSUE TITLE
extra option for add bulk monster

### ISSUE THREAD

**Issue by tkkumo** [madcowfred/padherder-issues#80]
is it possible to add this option on it?

monster name (or id) $ lvl $ exp remain to next level, 

so when we open up our pet info page we can see all the information directly from there, or is there another more convenient way to add bulk monsters which i'm missing out

**Comment by madcowfred** [comment]
I'm not that interested in messing with making bulk add even more complicated. Just enter monsters as a level, the possible XP error is largely irrelevant unless the monster is close to maxed.
