### ISSUE TITLE
All monsters on 'Monsters tab' have disappeared!

### ISSUE THREAD

**Issue by iNeedMoreAccounts** [madcowfred/padherder-issues#801]
This happened last night while using the site on my ipad and I assumed it was a temporary server issue, however today after checking on my PC (using IE & Firefox) they are still gone.  The weird part is that they still show up on the 'Team page' and on the 'Sets page'.  I've tried resetting the filters on the 'Monsters tab' and reloading the page, etc. but they don't seem to be coming back.

The ability to keep track of all of the cards I have and look at team numbers and compositions has been invaluable to me and I'm missing it already! :)

**Comment by malhas** [comment]
Same thing happened to me yesterday after importing a JSON file.

**Comment by madcowfred** [comment]
That's... odd. Can you link your user pages so I can take a look? Probably some stupid JS error.

**Comment by malhas** [comment]
Sure. https://www.padherder.com/user/malhasjp/monsters/
I have another account linked but that one has no issues.

**Comment by madcowfred** [comment]
Ah, looks like there's a new 'Enhanced Heart Orbs' awoken skill. Hitting things with a hammer now.

**Comment by malhas** [comment]
Thanks a lot ;)

**Comment by madcowfred** [comment]
Should be fixed now.

**Comment by iNeedMoreAccounts** [comment]
Thanks so much!  Everything is working perfectly today :)
