### ISSUE TITLE
Suggestion: make the max-awoken conditional for DONE status

### ISSUE THREAD

**Issue by ngamber** [madcowfred/padherder-issues#803]
I have a number of monsters which are intentionally left without full awakenings (to avoid autoheals, similar reasoning as +198 monsters) and the new DONE status that seems to require full awakenings leaves those hanging out at the top of my list. 

I can just set them to zero priority for now, but I would personally prefer the old behavior, or an option to toggle it back on.

**Comment by madcowfred** [comment]
Added a new "Done includes awoken" option in settings, defaults to off.
