### ISSUE TITLE
Max leveled monsters with no further evo selected are no longer 'done'

### ISSUE THREAD

**Issue by iNeedMoreAccounts** [madcowfred/padherder-issues#804]
Since the issue I had with my entire monster list disappearing now that they are back I have several dozen monsters that have switched from being 'done' and are now displaying their previously selected priority.
I've tried changing their level from max to a lower number then switching them back to max level to see if they would move back to 'done' but it doesn't seem to work.

My account is 'houseofcards'.

**Comment by ngamber** [comment]
Probably related to this: 

https://github.com/madcowfred/padherder-issues/issues/803

**Comment by iNeedMoreAccounts** [comment]
Yea I think that's it, all the max leveled cards with no further evo selected are not fully awakened.  Can't say that I'm a fan of it working this way but I guess its intentional.  Thanks for clearing that up.
