### ISSUE TITLE
Some pantheons in Sets aren't properly showing awakenings and max skill icons

### ISSUE THREAD

**Issue by zably** [madcowfred/padherder-issues#806]
![image](https://cloud.githubusercontent.com/assets/7295661/11289077/769689f6-8ef7-11e5-9fe1-5d498a6f7903.png)

Similarly to #304, I think it mostly has to do with Awoken Evo's or split ults (with different numbers of awakenings) screwing things up.  It looks like generally, if there's an awoken form, the skill changes, and so the other ults no longer show the max-skill icon.  Additionally, if there's a split-ult with 7 awakenings or something, the other evo's that only have 4 won't show the icon for max awoken.

The ones I've noticed so far are:
1. The Egyptian pantheon (for example, D/L Anubis, doesn't show max skill since it's different from the awoken version, nor max awoken since it only has 4 vs. the Awoken Evo's 7)
2. Greek Gods 2 (my Artemis and Apollo aren't showing max awakenings since they only have 4 while the other Evo has 7)
3. Chinese Gods similarly don't show icons for non-awoken forms for both skills and awakenings
4. Three Kingdoms don't show awakenings for some ult-evos
5. Japanese Gods don't show skill or awakenings for non-Awoken Evos

This isn't super comprehensive, it's only the ones I happen to notice with my box, but if it's helpful, I can go test them all a bit more thoroughly to get a more complete list.

**Comment by madcowfred** [comment]
This _should_ be fixed now. Worst bug.
