### ISSUE TITLE
Jp names

### ISSUE THREAD

**Issue by abc987** [madcowfred/padherder-issues#807]
I'm not sure if this has been mentioned or not but from my understanding, the name jp names given in padherder is actually chinese ones, not jp

**Comment by madcowfred** [comment]
Well that's amusing. Do you know of a JP language site with a conveniently scrape-able list of monsters with names? :|

**Comment by abc987** [comment]
I'm not sure if this' up for it but anyway
http://www18.atwiki.jp/pazdra/pages/1131.html

**Comment by madcowfred** [comment]
OK, this is hopefully fixed now
