### ISSUE TITLE
Ltron's skill needs updating

### ISSUE THREAD

**Issue by sickcat99** [madcowfred/padherder-issues#812]
At the moment the max is set at 6 but she can reach 7 now.

**Comment by sakray07** [comment]
Yes, same with DMeta (4, max is 6). Also related, the Sonias and Ilm have had their max cooldowns lowered by 1 (13 to 12 @ max).

**Comment by sickcat99** [comment]
Are these issues not getting fixed any more?
Dtron does not update. Ltron reads 7 now when it should change to max

**Comment by madcowfred** [comment]
Skills don't normally get updated since it's slow. Now they probably have been.
