### ISSUE TITLE
Subnav doesn't push down the main content if not default size

### ISSUE THREAD

**Issue by Raijinili** [madcowfred/padherder-issues#815]
The `#subnav` can take up a second line if the filter is complex and the screen isn't wide enough. For example, my default filter excludes material monsters and Zero/Done priority, which means my filter is "Priority = (Low, Medium, High); Type = (Attacker, Balanced, Devil, Dragon, God, Healer, Machine, Physical)". This pushes "Expand Evolutions" and "Collapse Evolutions" to the second line, but `#container` doesn't get pushed down, so part of it is hidden.

**Comment by madcowfred** [comment]
Made some changes to cap the width of the filter list, hopefully that helps.
