### ISSUE TITLE
Suggestion: Group tpa, rows etc into one box

### ISSUE THREAD

**Issue by sickcat99** [madcowfred/padherder-issues#819]
It would be easier to read if the tpa, rows etc are grouped into one box. It's late and hard to explain but here's an example of what I mean
![image](https://cloud.githubusercontent.com/assets/7051547/11604635/26f7df8e-9ae7-11e5-8767-5df85ab75144.png)

**Comment by madcowfred** [comment]
On Monsters pages or Teams pages?

**Comment by Raijinili** [comment]
It'd be harder to browse. Visual counting is faster than reading.

If this is implemented, please make it optional.

**Comment by sickcat99** [comment]
It would be nice as an additional view along side how it is currently laid out. On the team pages.

**Comment by madcowfred** [comment]
You're in luck, that was added with #577 :)

**Comment by sickcat99** [comment]
Amazing!
