### ISSUE TITLE
Queen Metal/Gold dragons are being imported as monsters, not food for skillups

### ISSUE THREAD

**Issue by jgoldshlag** [madcowfred/padherder-issues#821]
It would be nice in general to never add an enhance type monster to my monsters as well, so this sort of thing doesn't happen in the future (from JSON imports at least)

**Comment by madcowfred** [comment]
Import JSON will now just always skip adding enhance/evolve/awoken material types. Well, unless their max_level is >20 (snoooow gloooobe dragoooons).
