### ISSUE TITLE
Sticker Girl Courier Tier (first evo) max level is incorrect

### ISSUE THREAD

**Issue by FaxCelestis** [madcowfred/padherder-issues#822]
IE: #424, Light Courier Fuu is reported as having max level 15 in PADH but in-game has max level of 50.

**Comment by madcowfred** [comment]
Confused about this - 424 has max_level=50 and has had for at least a few weeks :\

**Comment by FaxCelestis** [comment]
Looks like it might be through JSON additions only? It's only affecting my newly-added courier-level sticker girls, not my existing ones or those obtained through evo. IDK, Here is a screen.
![capture6](https://cloud.githubusercontent.com/assets/7397366/11787174/30d730ea-a23f-11e5-9081-2808da79fee5.PNG)

**Comment by FaxCelestis** [comment]
OH, DURR. Okay so JSON is setting the TARGET level to 15, though the actual max level is 50.

**Comment by FaxCelestis** [comment]
Bug is a little more pervasive than that. Updating a card via JSON doesn't update the Target Level (or change the Target Evo when updating two or more evolution stages on the same card).

**Comment by madcowfred** [comment]
Ah, I see what's going on - if it changed the monster type of a card identified via cuid it would forget to update target_level also.
