### ISSUE TITLE
API doesn't include cuid for monsters

### ISSUE THREAD

**Issue by jgoldshlag** [madcowfred/padherder-issues#831]
I'm working on an all-in-one https/dns proxy and padherder importer for iOS folks, and it looks like you added some stuff to use the cuid stuff in the JSON, but that field isn't exposed in the API. Any chance you can add it?

**Comment by madcowfred** [comment]
Monster API objects will now have a 'pad_id' field, this is the PADherder name for 'cuid' from JSON. Should make matching monsters easier.

**Comment by jgoldshlag** [comment]
Thanks Freddie!
