### ISSUE TITLE
Gungho Collab PEM cards

### ISSUE THREAD

**Issue by zably** [madcowfred/padherder-issues#832]
Some new cards available in NA, #2106-2121.  Can you also add them to sets?  I'm not sure if you want to make a new sets category for them, PDX lumps them in with the standard Gungho collab cards (#662-665 and #1519-1523), but you don't have those in sets either.

Also, Awoken Freyr was released, he's #2392.

**Comment by madcowfred** [comment]
p.s. if I added a way for mysterious users to manage sets for me via the website, would you be interested in doing so? Current method is annoying and I barely play PAD these days :\

**Comment by zably** [comment]
Yeah, definitely!  I sorta had a feeling you were busy, but since you replied to a few previous posts asking to help with something about the code being messy, I wasn't sure there was anything I could do other than post issues.
