### ISSUE TITLE
Adding Rinshia breaks things.

### ISSUE THREAD

**Issue by lidav6** [madcowfred/padherder-issues#834]
After trying to edit in Rinshia as a sub onto one of my teams, when I pressed save changes, nothing happened. When I reloaded the page, the team didn't load. When I clicked on a different team, it loaded, and after I edited Rinshia out of the team, the team loaded.

 Also, after adding rinshia to my box, my monsters don't load. I added rinshia manually, not with Padlistener or anything else.

**Comment by madcowfred** [comment]
New awoken skills sure make PADherder unhappy. Fixed.
