### ISSUE TITLE
Gigas eats Goblins (Food page)

### ISSUE THREAD

**Issue by bjnord** [madcowfred/padherder-issues#838]
On the Food page, could you add Gigas, whose skill (Attack Stance - Fire) matches Samurai Goblin (No. 57)? It would be helpful to have a count of Red Goblin (No. 56) which need to be evo'd. Thanks!

**Comment by madcowfred** [comment]
Hm, I think evolved goblins weren't added to food as they drop a LOT from a wide variety of dungeons. It's much easier to just grind them (many of the levels they drop from are reasonably efficient XP) than deal with evolving imo.
