### ISSUE TITLE
Kodama, Hamahime, Neneko

### ISSUE THREAD

**Issue by kidoblivious** [madcowfred/padherder-issues#84]
I know i'm a freak for keeping one of each of them and giving them some levels, but i've maxed two of them now, and expected them to join my other (foolish) project like my max skill black knight at the top of the listing with MAX on them but they just sit pretty on their 30 levels, is this what you expect to be happening? :)

**Comment by madcowfred** [comment]
There's a completely arbitrary minimum max level of 50 for MAX right now, I don't really remember why :monkey_face:

**Comment by madcowfred** [comment]
I've changed the minimum max level to 10, that should hopefully cover everything.
