### ISSUE TITLE
Currently cannot add Latent Awakenings to Friend Leader & other issues on the My Teams tab

### ISSUE THREAD

**Issue by 0rangeSoda** [madcowfred/padherder-issues#842]
In the team simulator/tab there currently isn't an option to add latent awakenings to the friend leader. Also as an additional suggestion, would it be possible to directly show the numerical value of each latent awakening such as when mousing over the icons? (In terms of reduced percent and increased raw stats)

Additionally, pressing the "Show Maxed Stats" button REMOVES all existing latent awakenings

**Comment by madcowfred** [comment]
Fixed the "Show Maxed Stats" thing and added some slightly more descriptive latent tooltips. I completely forgot about friend latent things, I'll try to get that done a bit later today.

**Comment by madcowfred** [comment]
Added friend latent awakenings stuff for teams.
