### ISSUE TITLE
Suggestion: Make 'done' priority an option, or give ability to ignore it in sort/filter

### ISSUE THREAD

**Issue by akiSa** [madcowfred/padherder-issues#843]
It'd be nice to not see snowglobes etc alongside, or rather even higher than my actually high priority cards, and to see the 'done' cards actually stay in their priorities, just a peeve of mine.

**Comment by madcowfred** [comment]
Username in top right->My Account, find "Done position" and change it to "Normal position".

**Comment by akiSa** [comment]
Out of all the times I looked in account settings, I never noticed that. Thanks
