### ISSUE TITLE
Feature: Pre-uevo awakenings

### ISSUE THREAD

**Issue by Raijinili** [madcowfred/padherder-issues#845]
It's possible to have a higher awakening count than the monster's max awakenings. This info is in the PAD JSON. It is also useful to be able to keep track of pre-awakenings, since PAD won't tell you. (Monsters must have at least one awoken skill to be able to gain awakenings.)

Request:
- For a monster's details page, it currently shows:
  
  ```
  MAX
  2
  1
  0
  ```
  
  I want it to show:
  
  ```
  0
  1
  2
  3 (MAX)
  4
  5
  6
  7
  8
  9
  ```
- Show the extra awakenings in Evo preview.
- Friend leaders should not be affected.

Extension: It's possible to show potential max (i.e. max at chosen eventual evolution).

```
    0
    1
    2
    3 (MAX)
    4
    5
    6
    7 (Uevo)
    8
    9
```

**Comment by madcowfred** [comment]
Huh, I didn't realise this was possible. I'll see how annoying it is to change this.

**Comment by madcowfred** [comment]
Added the ability to set 0-9 awakenings, API support, and displays '3 (MAX)' for the max. Displaying '6 (Evo)' or something ended up being truly horrible to implement so it's not happening :hear_no_evil:

**Comment by Raijinili** [comment]
JSON upload doesn't set hidden awakening count.

By the way, the max is 10, I believe.
