### ISSUE TITLE
Latent Awakenings

### ISSUE THREAD

**Issue by DanCathers** [madcowfred/padherder-issues#846]
Dropdown options are all listed as object Object.  Skill Delay Resist is not an option.

**Comment by JHunz** [comment]
I believe the [object Object] display happens when you've already set a latent on a monster and go back in to edit later

**Comment by ngamber** [comment]
It appears for me on a monster with no existing latents.

**Comment by theblumeanie** [comment]
I think there's a related bug with imports. I did an import recently and now all my monsters are unavailable and some of my teams aren't able to be displayed. I did some testing and it appears that if I add a card that has SDR latents to a team it becomes unviewable. I'm not sure how to remove the latents now that I've done the import. 

Edit: I manually removed the cards with SDR from the import file, reset my account, and imported the file. This fixed the issue.

**Comment by madcowfred** [comment]
This should be fixed now, I forgot that the PAD Wiki is rarely updated and used that for latent information :(
