### ISSUE TITLE
Bug: Adding creatures at level <> 1 adds another creature

### ISSUE THREAD

**Issue by mstephans** [madcowfred/padherder-issues#85]
I just added two creatures at level 3 and 4. The result was the creatures I submitted entered at lvl 1 and two Agdrails (the default) added at lvl 3 and 4. This was using the green Add Monster button.

**Comment by madcowfred** [comment]
I definitely can't reproduce this. What browser/OS/etc?

**Comment by mstephans** [comment]
I can't repro either now. :-) I think what I did was change the level, the pick the monster number and hit enter.Then I saw that the level was 1, changed the level again, and then hit enter. Because the form is reset when choosing a new creature number and upon hitting enter (I think?) this results in the situation described. Maybe have the form default to blank (or "Choose creature") and an alert generated if someone hits add while that's up? It wasn't intuitive to me that I had to pick the monster number/name first or it would reset the form.
