### ISSUE TITLE
[Import] Update of Isis to Awoken Isis / evolution tree

### ISSUE THREAD

**Issue by styloplume** [madcowfred/padherder-issues#850]
Hey, first thank you so much for everything you've fixed recently.

So, I evolved Isis to her awoken form in game, and then imported my new box.
Everything is fine except for her evolution tree which was set to reverse evo + awoken isis evo.

Setting the evo target to "None" fixes the issue but there must be something to fix there.

Keep up the awesome work !

**Comment by ngamber** [comment]
This exists elsewhere kinda: 

http://pad.allthings.moe/lookup/

**Comment by madcowfred** [comment]
This should be fixed now.
