### ISSUE TITLE
Joker #669 active skill missing

### ISSUE THREAD

**Issue by TheBaddest** [madcowfred/padherder-issues#865]
They updated this quite a while ago, the base form of Joker (#669) has the Killing Joke skill without needing to evolve. http://imgur.com/mcXWOaf

His active skill description also needs updating. Currently it only shows "Activate a random skill. This includes:"

Eastern Seven-Star Formation, Southern Seven-Star Formation, Western Seven-Star Formation, Northern Seven-Star Formation, Heat Breath, Hell Ball, Earth Ball, Orb Refresh, Change the World or Ultra Gravity.

**Comment by madcowfred** [comment]
Both should be fixed now.
