### ISSUE TITLE
Suggestion: 2279 Vigorous Hunt Gods, Umisachi & Yamasachi

### ISSUE THREAD

**Issue by eidle020** [madcowfred/padherder-issues#871]
When you have this card in your box it still says there is 1 alternate evolution is available but I believe this should count as a final evolution for U&Y.

**Comment by JHunz** [comment]
All super ults behave this way currently

**Comment by eidle020** [comment]
Yea, that's why this is a suggestion. I'm just putting it out there as a possible change I would like to see. Yea, I know U&Y have an alternate evo, but so does technically every other card. I just think the super ult evo should be regarded as a final evo, and therefore on padherder say "none" instead of "1 alternate evolution available" you can still pick the previous evo from the edit list if you want to revert and re-evo later.

**Comment by ngamber** [comment]
They're distinct evolutions, so the current wording is correct as is

**Comment by zably** [comment]
There's an option in settings so you can disable the text if you wish.

**Comment by eidle020** [comment]
Alright thanks
