### ISSUE TITLE
I can not edit or add some monsters to my database. Feb 24, 2016

### ISSUE THREAD

**Issue by KittraKat** [madcowfred/padherder-issues#872]
As of today, when I click the edit pencil it does nothing on a lot of my monsters. Also when I tried to re-enter (add) that monster to update it that way; it opens and lets me put in the number but all the drop-downs have a red circle with diagonal line through them, so I can Not those monsters or add them.

I was first trying to update    #1707. Twilight Sorcerer, Chester
Then I tried to add   #1707. Twilight Sorcerer, Chester. It would not let me add him either.

Same with  #1781. Holy Night Santa Claus, Hera. Can not edit or add.

But the ones I can edit with the pencil I can also add. Example is #1112. Karmic Destroyer, Shiva.

Kittra

**Comment by ardaniel** [comment]
Same here (for Pollux and Wee Jas, among others); looks like, if you open your dev console in Chrome or what have you, "Uncaught TypeError: Cannot read property 'keys' of undefined."

**Comment by madcowfred** [comment]
Oops. Should be fixed now :(

**Comment by ardaniel** [comment]
Verified fixed on my end. Thanks, Fred.

**Comment by mistak75014** [comment]
Yeah fixed, thanks !

**Comment by KittraKat** [comment]
Thank you very much works now for me also :))
