### ISSUE TITLE
Aurora Sakuya evo to Green Gleaming Sakuya showing wrong evolution materials

### ISSUE THREAD

**Issue by iSleipnir** [madcowfred/padherder-issues#877]
When the Green Gleaming (2077) evolution option is chosen for Kirrin of the Aurora (752), the wrong evo materials and icon is displayed. Instead of Green Gleaming evo, the Sacred Gleam (1218) evo is shown instead. 

Here is an image showing the selected evo, and the wrong evo mats display:
http://i.imgur.com/rH8TWw1.png

**Comment by madcowfred** [comment]
This is how it's meant to work. If you click the ">" thing, it will expand and show you that there's actually 2 steps to take - from 752 to 1218, then 1218 to 2077. See the evolution chart here: http://www.puzzledragonx.com/en/monster.asp?n=752
