### ISSUE TITLE
Dark Leige, Vampire Duke not showing on Sets page

### ISSUE THREAD

**Issue by AppoPi** [madcowfred/padherder-issues#878]
![sets page](https://cloud.githubusercontent.com/assets/9878066/13512220/2a388a1a-e14e-11e5-9e37-859a77c3a949.png)
![dark liege vampire duke](https://cloud.githubusercontent.com/assets/9878066/13512219/2a33ea64-e14e-11e5-826d-5986cb695977.png)

For whatever reason, Dark Liege, Vampire Duke does not appear on my sets page, even though it is in My Monsters list.

https://www.padherder.com/user/AppoPi/monsters/

**Comment by HappyNoms** [comment]
Affects a few other cards, I think.
Seems to be in collection, are present on teams in several cases.
Don't notice any effects so far other than minor Set display bug / quirk.

For me, am noticing Sets are missing:
Vampire, CaoCao, Indra, Red Ogre, Green Ogre,Artemis.

https://www.padherder.com/user/HappyNoms/sets/

**Comment by madcowfred** [comment]
This should be fixed now.
