### ISSUE TITLE
Skill level doesn't reset to zero upon active skill change

### ISSUE THREAD

**Issue by DreadPirateShawn** [madcowfred/padherder-issues#879]
Max-skilled non-Awoken Pandora (skill level 6), evo'ed to Awoken Pandora, and she showed up as skill level 6/5 in list view, and in edit view the skill level appeared blank (none of the numbers were pre-selected -- makes sense).

Minor issue, since it didn't really break anything, and I was able to select a fixed skill level just fine.

**Comment by wmedlar** [comment]
Looks like this is no longer the case. Are you still experiencing this issue?

**Comment by DreadPirateShawn** [comment]
Nope, looks like this has been fixed. Confirmed with Horus and Pandora. Closing.
