### ISSUE TITLE
Alraune #1101 not showing up in My Sets

### ISSUE THREAD

**Issue by bjnord** [madcowfred/padherder-issues#887]
PADherder username "Dunamos"

I have #1101 World Tree Sprite, Alraune:
![alraune](https://cloud.githubusercontent.com/assets/854790/13938155/0cde749e-ef99-11e5-9604-90c0af650cd3.png)
and she doesn't show up on the "My Sets" page on the "Healer Girls" row:
![my-sets](https://cloud.githubusercontent.com/assets/854790/13938168/2117760e-ef99-11e5-94c9-fcfb869a6b9f.png)
Pretty sure she used to? I tried adding a duplicate monster but she still doesn't show up.

**Comment by madcowfred** [comment]
This should be fixed now.

**Comment by bjnord** [comment]
Confirmed; thanks!
