### ISSUE TITLE
Add Light Ninja to Food page for uuvo Baal

### ISSUE THREAD

**Issue by bjnord** [madcowfred/padherder-issues#888]
Similar to how #554 Mid Dark Ninja shows up on the Food page (to evolve to High Dark Ninja) for #628 Archangel Lucifer,

Please add #552 Mid Light Ninja to the Food page (to evolve to High Light Ninja) for #2506 King's Gaze Demon Lord, Baal -- the ultimate-ultimate evo for Baal.

Thanks!

**Comment by madcowfred** [comment]
Updated.
