### ISSUE TITLE
"Favourite" checkbox for teams does not update correctly

### ISSUE THREAD

**Issue by rgajrawala** [madcowfred/padherder-issues#895]
Steps to replicate A:
1) Select a favourite team.
2) Click the "Edit Team" button.
3) Select a non-favourite team.
4) Click the "Edit Team" button.
5) The "Favourite" checkbox will be checked even though the team is a non-favourite team.

Steps to replicate B:
1) Select a non-favourite team.
2) If the "Favourite" checkbox is un-checked, check and then un-check the checkbox. If the "Favourite" checkbox is checked, un-check the checkbox.
3) Select a favourite team.
4) Click the "Edit Team" button.
5) The "Favourite" checkbox will not be checked even though the team is a favourite team.

**Comment by madcowfred** [comment]
Thanks for the excellent bug report, both issues should be fixed now :)

**Comment by rgajrawala** [comment]
No problem. Confirming that both issues are fixed.
