### ISSUE TITLE
Can't add Rukia

### ISSUE THREAD

**Issue by p0ye** [madcowfred/padherder-issues#896]
It's not possible to add [2678. Rukia Kuchiki](http://puzzledragonx.com/en/monster.asp?n=2678) nor [2679. Squad 13 Lieutenant, Rukia Kuchiki](http://puzzledragonx.com/en/monster.asp?n=2679)  manually or with PadHelper. (other Bleach collabs cards seem fine)

**Comment by madcowfred** [comment]
Hm, I just added a 2678 to my account - her name is in Japanese but everything else seemed ok. I've just updated all of the Bleach collab with NA data, hopefully that fixes it.

**Comment by p0ye** [comment]
Yep it's fixed now! Thank you
