### ISSUE TITLE
NA/EU Awakenings Mass Update 

### ISSUE THREAD

**Issue by TheBaddest** [madcowfred/padherder-issues#899]
http://www.puzzledragonx.com/en/news.asp?nid=518

All of the older ultimates got one or two new awakenings. 
No missing awakenings for the new/recent ultimates.

**Comment by madcowfred** [comment]
Which ones in particular are missing awakenings?

**Comment by TheBaddest** [comment]
I should have phrased the second sentence better; no problems with the new ultimates for NA/EU.

The missing awakenings: for example RD Ares, GL Artemis, and LR Apollo are missing two additional awakenings: Devil Killer and SBR, for a total of 6 awakenings.
http://puu.sh/oiDhU/9040aac3f4.
Will update with monster numbers later if you need those.

Just curious, do you need to manually update every single monster? Because there are 50+ monsters that need updating.

**Comment by madcowfred** [comment]
Nah, there's just some other issues preventing a site update atm. Should be fixed shortly!

**Comment by TheBaddest** [comment]
Wow that's quick. Thanks.

**Comment by madcowfred** [comment]
Staff told me it was broken yesterday, I was super busy with real work and only just got to it. Should be good now.
