### ISSUE TITLE
Late Bloom Dragons labeled as "Bad Dragons"

### ISSUE THREAD

**Issue by pfayze** [madcowfred/padherder-issues#9]
These are usually referred to as Late Blooms Dragons:
Salamander, Ifrit
Sea Serpent, Leviathan
Dragonette, Fafnir
Ivory Dragon, Divinegon
Basilisk, Tiamat

**Comment by madcowfred** [comment]
When I was adding the feature I asked what they were called and got several different names for them. If there's an official source (GungHo, amusingly poorly machine translated or otherwise) I'm happy to rename but otherwise.. ehh.

**Comment by jarch3r** [comment]
You could name them Gungtrolled.

**Comment by pfayze** [comment]
Puzzledragonx now calls them Late Bloomer Dragons: http://www.puzzledragonx.com/en/monster.asp?n=112

**Comment by thismightberyan** [comment]
In all fairness, they are pretty bad.

**Comment by dumdummuoi** [comment]
GungHo's NA PAD page on Facebook calls them Late Bloomer Dragons: https://www.facebook.com/notes/puzzle-dragons-north-america-gungho/ultimate-fusions-642/794870683874859

**Comment by madcowfred** [comment]
Aww. At least they're not actually bad now. Renamed and closing this poor old issue.
