### ISSUE TITLE
Adding levels to My Sets

### ISSUE THREAD

**Issue by tevvie** [madcowfred/padherder-issues#90]
I was wondering if a level indicator could be added to the my sets page. Sharing the set page is much easier when asking for help with making a team, and if it had level and skill level already displayed on it, it would be the most ideal tool to show off all the important monsters in your box.

**Comment by madcowfred** [comment]
Sounds good, added.

**Comment by tevvie** [comment]
Thank you so much. Im loving the change and the speed it was added!
