### ISSUE TITLE
monsters info needs update

### ISSUE THREAD

**Issue by gundamftw** [madcowfred/padherder-issues#905]
please refers to this update:
http://puzzledragonx.com/en/news.asp?nid=516

**Comment by JHunz** [comment]
What do you think needs updating, exactly?  None of those changes have hit the NA server

**Comment by gundamftw** [comment]
All the actives of the older Shonen Sunday characters have been boosted, I have a Recca, and his CD had decreased to 8 instead of 10

**Comment by zhurai** [comment]
People that play on JP servers use PADHerder too, you know.

**Comment by madcowfred** [comment]
Can you check if the skill updates are in now?

**Comment by gundamftw** [comment]
I checked most of them, everything seems update now except ushio&tora 2465, he has 5 awakenings now instead of 4

**Comment by madcowfred** [comment]
Should alll be fixed now.
