### ISSUE TITLE
Cant change time zone (inaccurate)

### ISSUE THREAD

**Issue by ghost** [madcowfred/padherder-issues#907]
after entering my friend ID, starter, etc. padherder assigned me to a group (group D)
However, that group that i was assigned's activities are 1 hour off, so the event is Ending when the site tells me that it is about to start.

on the full desktop site i see no option to change time zones

on the mobile site, i can CHANGE time zones, but it doesnt 'stick' (always lists America/Chicago)

In addition, the Canada/Regina time zone is missing (GMT-6 with No DST option ever [no change month to month in time])

**Comment by madcowfred** [comment]
Dupe #886 (mostly)
