### ISSUE TITLE
Icon for #2766 Yuna improperly scaled in My Teams section

### ISSUE THREAD

**Issue by tateMode** [madcowfred/padherder-issues#908]
In the "My Teams" section, the icon for #2766 Unwavering Summoner, Yuna is improperly scaled. Please refer to image.

![yuna_bug](https://cloud.githubusercontent.com/assets/1639764/15463620/74100b2a-207f-11e6-9575-d30b91723a06.png)

**Comment by madcowfred** [comment]
Should be fixed now.

**Comment by tateMode** [comment]
Yep; thank you!
