### ISSUE TITLE
Batman Collab's Robin points to the wrong info

### ISSUE THREAD

**Issue by wparks** [madcowfred/padherder-issues#91]
BAO Robin and his upgraded form are not filled out correctly in padherder, but they point to the correct page in puzzledragonx.com

http://www.puzzledragonx.com/en/monster.asp?n=673
http://www.puzzledragonx.com/en/monster.asp?n=674

**Comment by wparks** [comment]
Likewise with BAO Batman 677 and 678

http://www.puzzledragonx.com/en/monster.asp?n=677
http://www.puzzledragonx.com/en/monster.asp?n=678

**Comment by madcowfred** [comment]
This is because PDX is dumb and only has the monsters under the JP monster IDs... which are not the same for US. I'm not sure I want to add a hack specifically to deal with this.

**Comment by wparks** [comment]
How are you getting data from PDX for padherder? Is there an API?  Also, how is PDX getting his data? Or is just done by hand, if you happen to know...?

**Comment by madcowfred** [comment]
Looks like PDX has fixed this.
