### ISSUE TITLE
"Proxy Auto Wifi" doesn't work with PAD v9.0.3 (NA version)

### ISSUE THREAD

**Issue by arnaudjolly** [madcowfred/padherder-issues#912]
When using "Auto iptable" proxy mode, all the process work.
But when back home, with "Auto WiFi proxy" settings, Pad start screen leads to a 401 connection error when clicking on "start".

**Comment by jgoldshlag** [comment]
That sounds like a bug in padlistener, which is by a different guy. You can report it at https://github.com/Neraud/PADListener

**Comment by arnaudjolly** [comment]
You're completely right! That's a mistake. You can close this issue as it's pure nonsense.
Happy coding and keep the good work.
