### ISSUE TITLE
monsters with 10 million experience curve are not displaying their level properly

### ISSUE THREAD

**Issue by gundamftw** [madcowfred/padherder-issues#915]
seraphis(2890) and miru(2968) are both locked to level 1 and "1" exp needed no matter how I change them.

**Comment by madcowfred** [comment]
This should now be fixed

**Comment by gundamftw** [comment]
There's still a bug, I manual evolved my miru into her ultimate form, but then she was reset back to level 1

**Comment by JHunz** [comment]
The PDX data we scraped from has it incorrectly listed as a normal (non-ult) evo.  The curve itself should be fine now
