### ISSUE TITLE
Horus armor Ace and Bastet armor Ace evolutions missing

### ISSUE THREAD

**Issue by gundamftw** [madcowfred/padherder-issues#921]
2927, 2929

They have been added to the game a month ago in jp

**Comment by ryuujinzero** [comment]
Both 2927 and 2929 are already in, however 2927 wasn't properly linked to 995. 2929 was already linked to 1613 and should already work, and I added the 995 -> 2927 link. If it doesn't work, try removing the monster and readding it, then try again.

**Comment by gundamftw** [comment]
it still buggy.  I added 494 Bastet and set final evolution to 2929 Bastet armor Ace, but the evolution chain displaying on the right side is still wrong, It's showing 495->888->495, the correct order should be  495->1613->2929.  But then when I ignored that display and keep clicking evolve, the evolution is corrected again after the 2nd evolution.

**Comment by ryuujinzero** [comment]
#966
