### ISSUE TITLE
Some of the 60x60 images are actually 98x98.

### ISSUE THREAD

**Issue by Raijinili** [madcowfred/padherder-issues#924]
Here's the list: 2719 2764 2765 2767 2768 2770 2771 2772 2773 2774 2775 2776 2777 2778 2779 2780 2781 2782 2783 2784 2785 2786 2787 2788 2789 2790 2791 2792 2793 2794 2795 2796 2797 2798 2804 2805

Sample: http://www.padherder.com//static/img/monsters/60x60/2780.44d34674ceb3.png

**Comment by madcowfred** [comment]
Fixed via your pull request that I forgot about :disappointed:
