### ISSUE TITLE
Apocalypse uevo missing awoken skills

### ISSUE THREAD

**Issue by styloplume** [madcowfred/padherder-issues#933]
Hey there ! Apocalypse's uevo does not have any awoken skills, hope you can update this soon :)

**Comment by DreadPirateShawn** [comment]
![screen shot 2016-07-21 at 7 53 32 am](https://cloud.githubusercontent.com/assets/1418951/17027341/534799c2-4f18-11e6-8277-3d91878d9459.png)

**Comment by JHunz** [comment]
Look again

**Comment by DreadPirateShawn** [comment]
Yaaay, fixed now.
