### ISSUE TITLE
New 9.2 patch awakenings missing

### ISSUE THREAD

**Issue by DreadPirateShawn** [madcowfred/padherder-issues#934]
In today's 9.2 patch (NA), there appear to be new awakenings, eg Hatsume now has two killer awakenings, but these aren't reflected in PADherder yet.

**Comment by ryuujinzero** [comment]
PADherder pulls it's data from PDX. If PDX hasn't updated yet, PADHerder can't be updated until it is.

**Comment by DreadPirateShawn** [comment]
Bah, makes sense -- and the admins are currently "busy catching pidgeys". Sigh. :-)

**Comment by JHunz** [comment]
I believe these are all sorted out now
