### ISSUE TITLE
Filter has incorrect default behavior

### ISSUE THREAD

**Issue by weschao** [madcowfred/padherder-issues#935]
With the addition of the new awakenings (yay, thanks!), if your default filter does not include any awakenings, it defaults to selecting the entire set of awakenings except the last ten. Clearing cookies, closing and reopening the browser, and resetting your default filter do not help.

You can kind of work around the issue by setting your default filter to include one awakening, and then de-selecting it once the page loads, but that's pretty cumbersome.

Reproduced in Chrome 51.0.2704.103 and Firefox 47.0.1.

**Comment by DreadPirateShawn** [comment]
To be clear, repro steps appear to be:
1. expand filter drop-down
2. click "Reset" (at which point all monsters appear)
3. click "Save as default"
4. click "My Monsters" tab, see that a filter is re-applied and only a handful of monsters are visible

As a minor tweak of the above workaround, open the filter drop-down and click "Reset" every time after the page loads. (Bigger target button that way, is all. Still cumbersome.)

Also, not sure if this is useful info, but for me it defaults to selecting "the entire set of awakenings except the last six" -- attaching screenshot for reference.

![screenshot_issue935](https://cloud.githubusercontent.com/assets/1418951/17082465/398d39a6-5134-11e6-8575-ff24529282ec.png)

**Comment by nickjmh** [comment]
This has been happening to me as well.

**Comment by JHunz** [comment]
There are two possibilities on your next page load:
1) It will be fixed and you won't have to do anything
2) You will need to reset your filters and save as default one more time, at which point it will stick

**Comment by bjnord** [comment]
2) worked for me. Thanks!!

**Comment by weschao** [comment]
Thanks for the fix!
