### ISSUE TITLE
Leader Skill issue in My teams (Kanna #2148)

### ISSUE THREAD

**Issue by andrew-howes** [madcowfred/padherder-issues#943]
In the My Teams section, Kanna's leader skill is not calculating attack values correctly. The old leader skill appears to be in use (1.5x HP for Dragon Types, 3.5x Attack for God types) instead of the new version (1.5 HP, 3.5x attack for Dragon and god types). 

Example: https://www.padherder.com/user/newershadow/teams/#244593 - Kanna and Apocalypse get both leader skills applied, as Dragon/God types, while most of the rest that are just Dragon get only one skill applied. 
Update summary where the leader skill changed: https://www.facebook.com/notes/puzzle-dragons-north-america-gungho/new-ultimate-evolutions-and-skill-improvements/1339326262762629

**Comment by JHunz** [comment]
Aside from Grodin, whose new leader skill hasn't been loaded yet, the rest in that update should be fixed
