### ISSUE TITLE
"Ready to evolve" filter doesn't include valid UUevo

### ISSUE THREAD

**Issue by DreadPirateShawn** [madcowfred/padherder-issues#944]
I have "Wise and Moral Goddess, Sarasvati" and all the evo mats to evolve her.

With the filter "Have all evolve materials", she shows up as expected.
![screenshot_issue944_haveevomats](https://cloud.githubusercontent.com/assets/1418951/17647057/c7d70dd2-6196-11e6-88d5-ecec907d8d28.png)

But with both filter "Ready to evolve" and "Have all evolve materials", she does not appear.
![screenshot_issue944_haveevomatsandreadytoevolve](https://cloud.githubusercontent.com/assets/1418951/17647059/cd12e51e-6196-11e6-8180-03fd810d6723.png)

She is only at level 37, but she does not need to be max level to be evolved. Shouldn't she appear in the list as "Ready to evolve" and "Have all evolve materials"?

**Comment by DreadPirateShawn** [comment]
PS: It occurs to me, this is a North America account, and Sarasvati's next evo isn't actually released in NA... is this just an invisible data point that's factored into "Ready to evolve"? Is that why Sarasvati's "evo" wand icon has a red background in the first screenshot above, rather than a green icon?

**Comment by ryuujinzero** [comment]
It is as you said. If a monster is set to jpOnly, it won't appear under the 'Ready to Evolve' filter option on accounts set to the NA server. To verify this, I set my Shiva Dragon's evolution to 鍛煉神・シヴァ＝ドラゴン (his uuvo) on my NA PADherder. While it does show up as green when no filters are used, it doesn't show up at all under "Ready to Evolve".
