### ISSUE TITLE
KABOOM!

### ISSUE THREAD

**Issue by ryuujinzero** [madcowfred/padherder-issues#946]
When attempting to add a new monster through Add Monster or Bulk Add, Kaboom message appears. 

http://i.imgur.com/NAPqk2o.png?1

**Comment by DreadPirateShawn** [comment]
Similarly, attempting to evo a monster (Sarasvati in particular) replaces that monster row entry with:

```
Something has gone horribly wrong, please try reloading the page. (500:
```

**Comment by DreadPirateShawn** [comment]
...and if you attempt to logout, the "Kaboom" message appears, and now any login attempt returns to the "Kaboom".

**Comment by madcowfred** [comment]
Everything broke very badly due to the database server disk filling up. Oops.
