### ISSUE TITLE
Summery Tourist Chester (#2291) is missing his sixth Awoken Skill

### ISSUE THREAD

**Issue by afeldspar** [madcowfred/padherder-issues#947]
Summery Tourist, Chester [http://puzzledragonx.com/en/monster.asp?n=2291] has six Awoken Skills: 
- TPA
- SBR
- Time Extend
- SBR
- SBR
- SBR

PadHerder only lists the first five of these, however.

**Comment by madcowfred** [comment]
Fixed.
