### ISSUE TITLE
Resting Norn Urd and Paradise Norn Urd are missing their last two Awoken Skills

### ISSUE THREAD

**Issue by afeldspar** [madcowfred/padherder-issues#948]
Resting Norn, Urd [http://puzzledragonx.com/en/monster.asp?n=2288] and Paradise Norn, Urd [http://puzzledragonx.com/en/monster.asp?n=2288] have the same set of eight Awoken Skills:
- TPA
- Skill Boost
- Enhanced Water
- SBR
- Enhanced Water
- Enhanced Hearts
- Enhanced Water
- Time Extend

PadHerder only lists the first six of these, however.

**Comment by madcowfred** [comment]
I've updated all of the goofy Norns, should all be right now. Probably.
