### ISSUE TITLE
Prophetic Norn, Skuld has a different leader skill

### ISSUE THREAD

**Issue by afeldspar** [madcowfred/padherder-issues#949]
Prophetic Norn, Skuld [http://puzzledragonx.com/en/monster.asp?n=2714] is listed as having the same Leader skill as her earlier forms, [http://puzzledragonx.com/en/monster.asp?n=1673] and [http://puzzledragonx.com/en/monster.asp?n=1674], _Blue-Green Divine Clock_.   However, her leader skill is actually the following:

_Destiny Carving Divine Clock_: 3.5x ATK for Water Att., 2x RCV for Wood Att.; 1.5x ATK for Att. erasing 5 Orbs with enhanced

Note that puzzledragonx.com actually hasn't updated this either, but I'm looking at the skill description in PAD itself (I can get a screenshot if needed, but it would mean juggling a few devices.  Let me know if it's needed.)

**Comment by zably** [comment]
Most data is grabbed from PDX at the moment, so until they update, there's not much that can be done.

**Comment by ryuujinzero** [comment]
Fixed.
