### ISSUE TITLE
Shining Lance Wielder, Odin has a changed Leader Skill

### ISSUE THREAD

**Issue by afeldspar** [madcowfred/padherder-issues#950]
Shining Lance Wielder, Odin [http://puzzledragonx.com/en/monster.asp?n=1423] used to have the leader skill _Robe of Protection_, whose effect was '80% all damage reduction when HP is full'.

However, he now has the skill _Wind of Asgard_.

The official description is "Greatly reduces damage when HP is full; ATK increases with 4+ linked Wood Orbs, up to 3.5x".  A more detailed description, which seems accurate in its specific numbers, was given in the comments on the PADX page:

_Wind of Asgard_: 80% all damage reduction when HP is full. ATK x1.5 when simultaneously clearing 4 connected Wood orbs. ATK x0.5 for each additional orb, up to ATK x3.5 at 8 connected orb.

The PADX page actually has not been updated to reflect the new leader skill, either.

**Comment by zably** [comment]
Same as #949, I can't fix it until PDX is updated.

**Comment by ryuujinzero** [comment]
Fixed.
