### ISSUE TITLE
Bastet  Evo Chain

### ISSUE THREAD

**Issue by mteh2** [madcowfred/padherder-issues#952]
The Bastet Evo Chain is messed up atm. Acestet evoes from G/D Bastet in the game and here it evoes from G/L bastet

**Comment by mteh2** [comment]
I think at least, I set my Bastet to evo to Ace and it had me go through G/L bastet

**Comment by DreadPirateShawn** [comment]
Confirmed, I'm seeing the same thing.
![issue952_padherder](https://cloud.githubusercontent.com/assets/1418951/18806143/995e58f6-81d6-11e6-97b5-11fa44462abe.png)
![issue953_puzzledragonx](https://cloud.githubusercontent.com/assets/1418951/18806144/9cce2890-81d6-11e6-843e-03d2d49f5cc1.png)

**Comment by leewz** [comment]
No need to confirm. Padherder's data is wrong.

**Comment by ryuujinzero** [comment]
#966
