### ISSUE TITLE
Card #3088 missing

### ISSUE THREAD

**Issue by w00kie** [madcowfred/padherder-issues#954]
Admittedly it's also kinda broken on padx: http://www.puzzledragonx.com/en/monster.asp?n=3088

It should be an evolution of #1772 Valkyrie Rose.

**Comment by TheBaddest** [comment]
In the same vein, #3090 also does not have a proper evolution path. It should be #2745's ultimate evolution .

**Comment by ryuujinzero** [comment]
Duplicate of #966
