### ISSUE TITLE
EXP/Miscellaneous Issues

### ISSUE THREAD

**Issue by mistresscc** [madcowfred/padherder-issues#955]
Achtros/Deighk/Deightros all have a max level/EXP value of 1, and when attempting to set their level higher than 1 the EXP remains at 1. 

In addition, Ace's evolution is currently backwards. You have to input Ace evo'd form (2926) and it will show Ace's base form (2978) as the evolution. The materials are the same. From the Ace Descended dungeon, Ouka (2930), Mizuha (2933), & Enju (2936) do not currently have their uvos up.

**Comment by madcowfred** [comment]
The XP thing should be fixed, the Ace evo is a hot mess :( Closing this for now and leaving #957 for the other.
