### ISSUE TITLE
Achtros & Deighk Still broken

### ISSUE THREAD

**Issue by zedekblue** [madcowfred/padherder-issues#963]
So I'm new enough to github that I don't know if commenting on a closed issue will reopen it, so I'm just making a new one. Referencing #962 

Achtros & Deighk still have broken XP curves. Pepper was fixed, but these two are still having issues.   

![bug](https://cloud.githubusercontent.com/assets/17040113/19504687/73dffca4-9579-11e6-8fbb-c8d5d71dc523.png)

**Comment by mistresscc** [comment]
![capture](https://cloud.githubusercontent.com/assets/22142284/21460244/f2321aba-c8fa-11e6-9286-15bc448798d1.PNG)
Achtros, Deighk, and Deightros all have this issue for me.

**Comment by madcowfred** [comment]
This should be fixed now.
