### ISSUE TITLE
Suggestion: Pengdra field to something more common

### ISSUE THREAD

**Issue by sickcat99** [madcowfred/padherder-issues#965]
Pengdras aren't really a way to leave things nowadays with Pengdra village no longer being a guerilla dungeon so could we have some sort of metal in there instead? Such as King or Super king?

**Comment by zedekblue** [comment]
Hovering over the Pengdra number will show kings & super kings, on-color and off-color. 
Being able to change the default could be cool, though.

**Comment by sickcat99** [comment]
Forgot you could do that! Change the default would be a nice to have. Especially on my mobile where it doesn't allow me to hover over the pengdra label

**Comment by ryuujinzero** [comment]
Duplicate of issue #190
