### ISSUE TITLE
No Monsters?

### ISSUE THREAD

**Issue by Gannonball09** [madcowfred/padherder-issues#97]
None of my monsters are showing up in my list. The materials for them are still there. But not the monsters. I tried logging out and logging back in and that didn't work. Thanks for all the help! :)

**Comment by madcowfred** [comment]
What is your account name? What browser? Have you done something silly like turn Javascript off?

**Comment by Gannonball09** [comment]
I cannot view it on Internet Explorer at work for some reason. Just switched to Chrome. Lol. Works fine! Scared me at first though!

**Comment by madcowfred** [comment]
Looks like I left some debug timing calls in and IE was throwing up at the mere sight of them, fixed now.
