### ISSUE TITLE
Ra evo chain is broken

### ISSUE THREAD

**Issue by DreadPirateShawn** [madcowfred/padherder-issues#982]
When Ra (id 496) is set with target evo "Awoken Ra" (id 2012), the evo chain is correct:

![ra-evo_target-awoken_ra](https://cloud.githubusercontent.com/assets/1418951/21285002/1d9fb550-c3e1-11e6-80e8-c43e1dd05e9d.png)

However when Ra is set with target evo "Reincarnated Ra" (id 3273), the evo chain is weird -- it doesn't include Awoken Ra, and doesn't actually reach Reincarnated Ra:

![ra-evo_target-reincarnated_ra](https://cloud.githubusercontent.com/assets/1418951/21285006/3dbf8a40-c3e1-11e6-82d4-6a420462849e.png)

**Comment by ryuujinzero** [comment]
Most of the Reincarnated monsters have this issue, as referenced in #961

**Comment by DreadPirateShawn** [comment]
Ahh my apologies, I saw "padheader" in the title of that ticket and thought it was just an issue with the header or some such, didn't pull it up to read it. I know I know, seems silly in retrospect, but might be worth adjusting the title -- I did try to look for a preexisting ticket, I swear! :-)

**Comment by ryuujinzero** [comment]
No problem!
