### ISSUE TITLE
Full Hollow, Ichigo Kurosaki

### ISSUE THREAD

**Issue by Murdurus** [madcowfred/padherder-issues#988]
There seems to be a problem when adding Full Hollow, Ichigo Kurosaki into teams. After adding him onto the team, it would cause the team to no longer be edited or show who is on the team although the team will still remain on the list of teams.

**Comment by ryuujinzero** [comment]
Unable to reproduce this issue in Firefox 42 and 50.1.0, Edge 20, IE 11, or Chrome 55 with both JP and NA.

**Comment by Murdurus** [comment]
Hm, that's odd. I'm still having the same problem and I tried it on Chrome as well and the same issue came up. Every other team works fine outside of the ones with Full Hollow, Ichigo Kurosaki. If the problem can't be reproduced, I guess it's just an anomaly for just me.

**Comment by JHunz** [comment]
Can you link your teams page?

**Comment by Raijinili** [comment]
@Murdurus 
Your A.Ichigo team has no FHIK. Your Sephiroth team has subs 1 and 4 empty (even in the in-page data). Which team did you add FHIK to?

**Comment by Raijinili** [comment]
Looks like team pages are not gracefully handling missing Awoken Skills, ~in particular the sprites~. Padherder doesn't have the Material Killers in yet, and the page load crashes.

Workaround: Lower your Ichigo's number of awakenings. You can then get into the team page.

Edit: It's not the sprites.

**Comment by Murdurus** [comment]
Ah, okay, yeah, lowering the awakenings down to 7 fixed the problem, thank you! I ended up deleting Ichigo and re-added him to my monsters to get my teams to start working again, otherwise, I would be unable to edit them and they behaved pretty inconsistently, sometimes causing it so that I wouldn't be able to select my other teams.

**Comment by ryuujinzero** [comment]
#989

**Comment by Raijinili** [comment]
If it's causing other teams to break, then there are probably multiple places in the code where there's no null check for awakenings.

**Comment by Raijinili** [comment]
Unknown awakenings should no longer crash Teams. Unfortunately, they simply don't show up.
