### ISSUE TITLE
Stop being a jerk and change links to wiki! :P

### ISSUE THREAD

**Issue by Clessasaur** [madcowfred/padherder-issues#99]
I figure it'd be easier to remind you here.

**Comment by tevvie** [comment]
dont do this please. the wiki is so much uglier.

**Comment by madcowfred** [comment]
This will show up as an account option at some point once I sort out some of the code that builds links.

**Comment by TheMidgardWatcher** [comment]
Stop being a jerk and do not use wiki! :P

PS Agreed with tevvie - wiki so much uglier!

**Comment by madcowfred** [comment]
Closing this ancient bug since the wiki is largely dead now. RIP.
