### ISSUE TITLE
Style Change cards

### ISSUE THREAD

**Issue by Kodeplay10** [madcowfred/padherder-issues#991]
This issues has existed for a while and I thought I'd report it.

The style-change cards from the Brave Hero series (Shotel, Claymore, Masamune, Kopis, Zweihander) have the incorrect sub attribute, with it being the same as their main att instead of the att their skill transforms them into.

**Comment by ryuujinzero** [comment]
Thanks for your submission. This is still being worked on as a part of issue #911. The typings are correct for team multipliers, it's just the card image that is incorrect.
