### ISSUE TITLE
Reincarnation/Crossover Evolution paths wrong

### ISSUE THREAD

**Issue by wyung** [madcowfred/padherder-issues#992]
For example,
padherder lists Ace Horus' evo path as Horus > R/R Horus > Ace Horus.
but puzzledragonx lists it as Horus > R/L Horus > Ace Horus.
Revo Horus also lists it as Horus > R/R Horus with no drop down to Revo Horus.

This issue doesn't happen if you are already one evo from the desired card.

**Comment by ryuujinzero** [comment]
These are ongoing issues. Please see issues #961 and #966.
