### ISSUE TITLE
Anavalk (#3088) not in padherder

### ISSUE THREAD

**Issue by mzhaodev** [madcowfred/padherder-issues#993]
I am unable to add [No. 3088 Divine Law Goddess Armor, Ana](http://puzzledragonx.com/en/monster.asp?n=3088) (evolves from No. 1727 Divine Law Goddess, Valkyrie Rose) to my monsters - padherder doesn't seem to recognize it as a monster.

**Comment by ryuujinzero** [comment]
Refer to #966
