### ISSUE TITLE
lucifer skillup... mid dark ninja?

### ISSUE THREAD

**Issue by seebs** [madcowfred/padherder-issues#997]
Lucifer shows mid dark ninja as the monster I'd need to collect to skill him up. I don't think that works?

**Comment by ryuujinzero** [comment]
The food page is for evolving skill up materials. It doesn't say Mid Dark Ninja skills Lucifer, rather it helps collect the evo materials required to evolve Mid Dark Ninja into the skill up fodder that skills Lucifer.

**Comment by seebs** [comment]
... i didn't realize that mid dark ninja evolved into a skillup fodder, nevermind. Thanks.
