### ISSUE TITLE
Team Build Stuck in Limbo

### ISSUE THREAD

**Issue by Quinret** [madcowfred/padherder-issues#998]
I can't seem to access or remove one of my team builds. I'm able to favorite and move that team's tab, even between team groups, and attempting to re-create the error allows me normal access to the subsequent team.

**Comment by ryuujinzero** [comment]
Does this team have any monsters on it that have the 7c or Guard Break awakenings?

**Comment by Quinret** [comment]
I re-tested the original team build again, and sure enough, fully awakening an evolved Xiahou Dun re-created the error. It must have been the 7c awakening. I take it this bug is known and on the to-do list?

**Comment by ryuujinzero** [comment]
Yep.

**Comment by madcowfred** [comment]
This should be fixed now.
